---
permalink: online-help-96-97/concept_what_nvme_is.html 
sidebar: sidebar 
keywords: nvme, protocol, nonvolatile, memory, express, transport, online, help 
summary: Nonvolatile Memory Express （ NVMe ）プロトコルは、不揮発性ストレージメディアへのアクセスに使用する転送プロトコルです。 
---
= NVMe とは
:icons: font
:imagesdir: ../media/


[role="lead"]
Nonvolatile Memory Express （ NVMe ）プロトコルは、不揮発性ストレージメディアへのアクセスに使用する転送プロトコルです。

NVMe over Fabrics （ NVMeoF ）は仕様で定義された NVMe の拡張機能であり、 PCIe 以外の接続経由による NVMe ベースの通信を実現します。このインターフェイスを使用すると、外部のストレージエンクロージャをサーバに接続できます。

NVMe は、フラッシュテクノロジから高性能な永続的メモリテクノロジまで、不揮発性メモリを搭載したストレージデバイスに効率的にアクセスできるように設計されています。そのため、ハードディスクドライブ用に設計されたストレージプロトコルのような制限はありません。フラッシュデバイスとソリッドステートデバイス（ SSD ）は、不揮発性メモリ（ NVM ）の一種です。NVM では停電時にもデータが失われません。NVMe はそのメモリにアクセスするための手段です。

NVMe のメリットには、データ転送の速度、生産性、スループット、容量の向上があります。具体的には次のような特性があります。

* NVMe は最大 64 、 000 のキューを使用できるように設計されています。
+
各キューには、最大 64 、 000 個のコマンドを同時に保持できます。

* NVMe は、複数のハードウェアベンダーとソフトウェアベンダーでサポートされています
* フラッシュテクノロジを使用すると NVMe の生産性が向上し、応答時間が短縮されます
* NVMe では、 SSD に送信される「検索」ごとに複数のデータ要求を行うことができます。
+
NVMe は「要求」のデコードにかかる時間が短く、マルチスレッドプログラムでスレッドロックを必要としません。

* CPU レベルでのボトルネックを防止する機能をサポートし、システムの拡張に応じて並外れた拡張性を実現します

