---
permalink: online-help-96-97/concept_metrocluster_switchover_switchback.html 
sidebar: sidebar 
keywords: system, manafer, switchover, switchback, metrocluster, cluster, site, online, help 
summary: System Manager 9.6 以降では、 MetroCluster スイッチオーバー / スイッチバックの処理を使用して別のクラスタサイトのタスクをテイクオーバーできます。メンテナンス時や災害からのリカバリ時に便利な機能です。 
---
= MetroCluster のスイッチオーバーとスイッチバック
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager 9.6 以降では、 MetroCluster スイッチオーバー / スイッチバックの処理を使用して別のクラスタサイトのタスクをテイクオーバーできます。メンテナンス時や災害からのリカバリ時に便利な機能です。

スイッチオーバー処理を使用すると、通常は別のクラスタ（サイト B ）が実行するタスクをクラスタ（サイト A ）がテイクオーバーできます。スイッチオーバー後、テイクオーバーされたクラスタ（サイト B ）を停止して、メンテナンスや修復を実施できます。メンテナンスが完了し、サイト B が稼働して修復タスクが完了したら、スイッチバック処理を開始して修復されたクラスタ（サイト B ）で通常のタスクを再開できます。

System Manager では、リモートクラスタサイトのステータスに基づいて 2 種類のスイッチオーバー処理がサポートされます。

* ネゴシエート（計画的）スイッチオーバー：この処理は、クラスタで計画的なメンテナンスを実施する場合や、ディザスタリカバリの手順をテストする場合に開始します。
* 計画外スイッチオーバー：この処理は、クラスタ（サイト B ）で災害が発生し、別のサイトまたはクラスタ（サイト A ）が災害の影響を受けたクラスタのタスクをテイクオーバーして修理とメンテナンスを実施する場合に開始します。


どちらのスイッチオーバー処理も、 System Manager で実行する手順は同じです。スイッチオーバーを開始すると、処理が可能かどうかが判断され、ワークロードが適宜調整されます。
