---
permalink: online-help-96-97/concept_license_types_entitlement_risk.html 
sidebar: sidebar 
keywords: license, types, entitlement, risk, cluster, online, help 
summary: さまざまなライセンスタイプと関連する使用権のリスクを理解しておくと、クラスタのライセンスに関連するリスクを管理する際に役立ちます。 
---
= ライセンスタイプおよび使用権のリスク
:icons: font
:imagesdir: ../media/


[role="lead"]
さまざまなライセンスタイプと関連する使用権のリスクを理解しておくと、クラスタのライセンスに関連するリスクを管理する際に役立ちます。



== ライセンスタイプ

パッケージには、クラスタにインストールされる次のライセンスタイプが 1 つ以上含まれます。

* ノードロックライセンスまたは標準ライセンス
+
ノードロックライセンスは、特定のシステムシリアル番号（別名「 _controller serial number_ 」）を持つノードに対して発行されます。このライセンスは、シリアル番号が一致するノードに対してのみ有効です。

+
ノードロックライセンスをインストールすると、ライセンスされた機能の使用権がノードに対して与えられます。ライセンスされた機能をクラスタで使用するには、少なくとも 1 つのノードで、その機能のライセンスが有効になっている必要があります。ライセンスされた機能の使用権がないノードでその機能を使用すると、ライセンス違反になる可能性があります。

+
ONTAP 8.2 以降のリリースでは、 Data ONTAP 8.2 より前にインストールされたライセンスは標準ライセンスとして扱われます。したがって、 ONTAP 8.2 以降のリリースでは、クラスタ内のノードはすべて自動的に、以前ライセンスされた機能が含まれているパッケージの標準ライセンスを保有していることになります。

* マスターライセンスまたはサイトライセンス
+
マスターライセンスまたはサイトライセンスは、特定のシステムシリアル番号に関連付けられません。サイトライセンスをインストールすると、クラスタ内のすべてのノードで、ライセンスされた機能を使用できるようになります。

+
マスターライセンスがあるクラスタからノードを削除した場合、そのノードはサイトライセンスを保持できず、ライセンスされた機能を使用できなくなります。マスターライセンスのあるクラスタにノードを追加した場合、そのノードには自動的にサイトライセンスが付与され、ライセンスされた機能を使用できるようになります。

* デモライセンスまたは一時ライセンス
+
デモライセンスまたは一時ライセンスは、一定期間が経過すると失効します。このライセンスを使用すると、ライセンスを購入せずに特定のソフトウェア機能を試すことができます。一時ライセンスはクラスタ規模のライセンスであり、ノードの特定のシリアル番号には関連付けられません。

+
パッケージの一時ライセンスがあるクラスタからノードを削除した場合、そのノードは評価用ライセンスを保持できません。

* 容量ライセンス（ ONTAP Select および FabricPool のみ）
+
ONTAP Select インスタンスのライセンスは、ユーザが管理するデータの量に応じて選択できます。たとえば、 10TB の容量ライセンスを購入した場合、 ONTAP Select で最大 10TB のデータを管理できます。システムに接続されたストレージ容量が ONTAP Select のライセンスで管理可能な容量を超えると、 ONTAP Select は動作しなくなります。デフォルトでは、 ONTAP Select インスタンスに接続できるストレージ容量は最大 2TB です。この容量を超える場合は、容量ライセンス（ 5TB の容量ライセンスや 10TB の容量ライセンスなど）を購入してインストールする必要があります。

+
ONTAP 9.2 以降では、 FabricPool 対応アグリゲートでサードパーティのストレージ階層（ AWS など）を使用する場合に容量ライセンスが必要になります。FabricPool の容量ライセンスでは、クラウド階層ストレージに格納できるデータの量が定義されています。





== 使用権のリスク

使用権のリスクは、ノードロックライセンスがさまざまな方法でインストールされることが原因で発生します。ノードロックライセンスがすべてのノードにインストールされている場合は、使用権のリスクは発生しません。

使用権のリスクレベルは、特定の条件に応じて、高、中、なし、または不明のいずれかになります。

* リスクが高い
+
** 特定のノードでライセンスが使用されているにもかかわらず、そのノード上にノードロックライセンスがインストールされていない場合
** クラスタにインストールされていたデモライセンスが失効し、いずれかのノードでライセンスが使用されている場合


+
[NOTE]
====
クラスタにサイトライセンスがインストールされている場合、使用権のリスクが高になることはありません。

====
* 中リスク
+
クラスタ内のノードに、サイトライセンスがインストールされておらず、ノードロックライセンスが一部のノードにのみインストールされている場合

* リスクなし
+
使用状況に関係なく、ノードロックライセンスがすべてのノードにインストールされている場合やサイトライセンスがクラスタにインストールされている場合は、使用権のリスクは発生しません。

* 不明です
+
API が、クラスタまたはクラスタ内のノードに関連付けられた使用権のリスクに関連するデータを取得できないことがある場合、そのリスクは不明です。


