---
permalink: online-help-96-97/concept_considerations_when_moving_volumes.html 
sidebar: sidebar 
keywords: move, volume, considerations, recommendations, configuration, system 
summary: ボリュームを移動するときは、移動するボリュームやシステム構成に応じて、さまざまな考慮事項や推奨事項について検討する必要があります。ここでは、ボリュームの移動に関する考慮事項を示します。 
---
= ボリュームを移動する際の考慮事項
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームを移動するときは、移動するボリュームやシステム構成に応じて、さまざまな考慮事項や推奨事項について検討する必要があります。ここでは、ボリュームの移動に関する考慮事項を示します。

* インライン重複排除が有効になっているボリュームをオールフラッシュで最適化されたアグリゲートまたは Flash Pool アグリゲートから HDD アグリゲートに移動した場合、移動後のボリュームではインライン重複排除が無効になります。
* バックグラウンド重複排除およびインライン圧縮が有効になっているボリュームをオールフラッシュによる最適化が実装されたアグリゲートから HDD アグリゲートに移動した場合、移動後のボリュームではバックグラウンド圧縮、バックグラウンド重複排除、およびインライン圧縮が自動的に有効になります。
* バックグラウンド圧縮が有効になっているボリュームを HDD アグリゲートからオールフラッシュで最適化されたアグリゲートに移動した場合、移動後のボリュームではバックグラウンド圧縮が無効になります。
* ボリュームを Flash Pool アグリゲートから Flash Pool アグリゲート以外のアグリゲートに移動した場合、キャッシングポリシーおよび保持優先度は無効になります。
* ボリュームを Flash Pool アグリゲート以外のアグリゲートから Flash Pool アグリゲートに移動した場合、デフォルトのキャッシングポリシーとデフォルトの保持優先度は自動的にボリュームに割り当てられます。

