---
permalink: online-help-96-97/concept_roles_delete.html 
sidebar: sidebar 
keywords: system, manager, create, manage, role, online, help, svm, edit 
summary: System Manager を使用して、ロールを作成および管理できます。 
---
= System Manager - ONTAP 9.7 以前を使用して、ロールを作成して管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、ロールを作成および管理できます。



== ロールを追加します

System Manager を使用してアクセス制御ロールを追加し、そのロールのユーザがアクセスできるコマンドまたはコマンドディレクトリを指定できます。また、ロールに付与するコマンドやコマンドディレクトリへのアクセスレベルを制御したり、環境でコマンドやコマンドディレクトリを指定するクエリを指定したりすることもできます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* SVM User Details] ペインで、 [* Roles] をクリックします。
. [ 追加（ Add ） ] をクリックします。
. [ 役割の追加 *] ダイアログボックスで、役割名を指定し、役割属性を追加します。
. [ 追加（ Add ） ] をクリックします。




== ロールを編集します

System Manager を使用して、アクセス制御ロールのコマンドまたはコマンドディレクトリへのアクセスを変更して、指定したコマンドセットのみにユーザのアクセスを制限できます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* SVM User Details] ペインで、 [* Roles] をクリックします。
. 変更するロールを選択し、 * 編集 * をクリックします。
. ロール属性を変更し、 * 変更 * をクリックします。




== ロールウィンドウ

ロールウィンドウを使用して、ユーザアカウントに関連付けられているロールを管理できます。



=== コマンドボタン

* * 追加 * 。
+
Add Role ダイアログボックスを開きます。このダイアログボックスでは、アクセス制御ロールを作成し、そのロールのユーザがアクセスできるコマンドまたはコマンドディレクトリを指定できます。

* * 編集 * 。
+
ロールの編集ダイアログボックスを開きます。このダイアログボックスで、ロール属性を追加または変更できます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





=== ロールのリスト

ロールリストには、ユーザに割り当てることができるロールのリストが表示されます。



=== [ 役割属性 ] 領域

詳細領域には、選択したロールがアクセスできるコマンドやコマンドディレクトリ、アクセスレベル、コマンドやコマンドディレクトリを環境で送信するクエリなど、ロールの属性が表示されます。

* 関連情報 *

https://docs.netapp.com/us-en/ontap/authentication/index.html["管理者認証と RBAC"^]
