---
permalink: online-help-96-97/concept_system_manager_enhancements.html 
sidebar: sidebar 
keywords: ontap, system, manager, enhancement, features 
summary: ここでは、 System Manager の今回のリリースで追加または変更された機能を示します。 
---
= ONTAP System Manager の機能拡張
:icons: font
:imagesdir: ../media/


[role="lead"]
ここでは、 System Manager の今回のリリースで追加または変更された機能を示します。



== ONTAP 9.6 で追加された機能と機能拡張

[NOTE]
====
OnCommand システムマネージャは、 ONTAP システムマネージャとして知られています。

====
* MetroCluster のスイッチオーバーとスイッチバックの処理
+
System Manager 9.6 以降では、 MetroCluster スイッチオーバー / スイッチバックの処理を使用して別のクラスタサイトのタスクをテイクオーバーできます。メンテナンス時や災害からのリカバリ時に便利な機能です。

* ファイルアクセスをトレースします
+
新しい Trace File Access ウィンドウでは、 CIFS プロトコルまたは NFS プロトコルを使用して SVM 上のファイルや共有へのアクセスでユーザが問題に直面した場合の問題を診断できます。

* 暗号化された SnapMirror
+
System Manager 9.6 以降では、ローカルクラスタの IPspace のパスフレーズを生成し、リモートクラスタでピア関係を作成するときに同じパスフレーズを使用できます。セキュリティ上の理由から、パスフレーズは変更可能です。

* FlexCache の機能
+
FlexCache ボリュームの作成、編集、表示、削除を行う機能が System Manager に追加されました。

* Fabric Pool の機能拡張
+
Alibaba Cloud と Google Cloud を、クラウド階層として使用するオブジェクトストアとして使用できるようになりました。また、 System Manager では「すべて」の階層化ポリシーがサポートされるようになりました。これにより、すべてのデータをクラウドに階層化するように指定できます。ボリュームのクラウドレイテンシを表示するために、 Volume 360 ページの Volume Performance タブが強化されました。

* FlexGroup の機能拡張
+
System Manager 9.6 以降では、ボリュームの名前変更やサイズ変更など、既存の FlexGroup ボリュームのプロパティを編集できます。

* SnapLock ボリュームの機能拡張
+
ストレージ QoS ポリシーグループを作成または変更する場合、パフォーマンスベースでのオールフラッシュで最適化に加えて、 ONTAP Select Premium システムに最小スループット制限を設定できます。





== ONTAP 9.5 で追加された機能と機能拡張

* ボリューム暗号化
+
FlexVol または FlexGroup ボリュームの編集時にボリューム暗号化を有効にできるようになりました。また、この機能が強化され、ボリュームのデータ暗号化キーを変更するためのキー変更オプションがサポートされるようになりました。

* クラスタの更新
+
System Manager 9.5 以降では、 MetroCluster 構成のクラスタを更新できます。クラスタの更新以外の処理は、すべて両方のクラスタで実行する必要があります。

* ボリュームレプリケーションポリシー
+
System Manager 9.5 で、 StrictSync および Sync という 2 つのポリシーが追加されました。これらのポリシーを使用して RPO ゼロのレプリケーションを実現でき、レプリケーションで障害が発生した場合にプライマリ IO を制限するかどうかは関係ありません。保護タブを使用してボリューム保護を有効にすることもできます。

* SVM DR
+
Storage Virtual Machine （ SVM ）ディザスタリカバリ（ DR ）は、 SVM レベルのディザスタリカバリ機能で、 SVM のコンスティチュエントボリュームに含まれるデータおよび SVM の設定をリカバリすることができます。System Manager を使用して、 SVM 間のミラー関係やミラーとバックアップ関係を作成および管理できます。

* L2/L3 アプリケーションが表示されます
+
ONTAP 9.5 以降の System Manager では、 Applications ページのさまざまなホスト名に L2/L3 アプリケーションが表示されます。ホスト名をクリックすると、 L2 Cockpit インターフェイスで新しいウィンドウが開きます。また、各アプリケーションについて、 System Manager に IOPS とレイテンシの測定値も表示されます。

* 仮想 IP のサポート
+
ONTAP 9.5 以降の System Manager には、仮想 IP （ VIP ） LIF に関する情報が表示されます。ただし、 VIP LIF の作成、削除、管理は System Manager では行えません。

* NVMe サブシステムのライセンス要件
+
ONTAP 9.5 以降では、 NVMe がライセンスされます。System Manager はライセンス要件をサポートしています。

* NVMeoF サブシステムのサポート
+
System Manager では、 FreeBSD カーネルに属する独立したカーネルオブジェクトである NVMe over Fabrics （ NVMeoF ）サブシステムの使用がサポートされます。NVMeoF は仕様で定義された NVMe の拡張機能であり、 PCIe 以外の接続経由による NVMe ベースの通信を実現します。このインターフェイスを使用すると、 NVMe を引き続き基本的な通信メカニズムとして使用しながら、外部のストレージエンクロージャを直接またはスイッチ経由でサーバに接続できます。NVMeoF サブシステムは、 SAN コンポーネント、 WAFL 、および RAS コンポーネントと連携します。

* NVMe マルチパスがサポートされます
+
ONTAP 9.5 以降では、 NVMe プロトコルを使用する HA ペアの各ノードに対して、少なくとも 1 つの LIF が設定されている必要があります。ノードに対して LIF を 2 つ定義することもできます。ONTAP 9.5 にアップグレードするときは、 NVMe プロトコルを使用する HA ペアの各ノードに対して少なくとも 1 つの LIF が定義されていることを確認する必要があります。

* FlexGroup の対象となるアグリゲート
+
FlexGroup を作成すると、アグリゲートがベストプラクティスに従ってデフォルトで選択されます。オールフラッシュで最適化されたストレージシステムの場合はシンプロビジョニングがデフォルトで有効になり、その他のストレージシステムの場合はシックプロビジョニングがデフォルトで有効になります。ベストプラクティスに従ったデフォルトの構成を変更する場合は、対象となる FabricPool アグリゲートのリストから選択することができます。

* パブリック SSL 証明書による認証
+
System Manager 9.5 以降では、 SVM に関連付けられているパブリック SSL 証明書の確認が可能です。証明書の詳細、シリアル番号、開始日、および有効期限を確認できます。証明書をクリップボードにコピーしたり、証明書の詳細を E メールで送信したりすることもできます。また、 SVM に vsadmin ユーザアカウントを追加すると、 HTTP をアプリケーションとして使用して証明書で認証するログイン方法が自動的に組み込まれます。

* qtree は、 FlexVol ではディレクトリとして表示されます
+
FlexVol に qtree とボリュームの両方が含まれている場合、 qtree はディレクトリとして表示されます。

* FlexCache ボリューム
+
FlexCache ボリュームは、 System Manager に FlexGroup として表示されます。親ボリュームの詳細は、 360 ページに表示されます。





== ONTAP 9.4 で追加された機能と機能拡張

* NVMe プロトコル
+
NVM Express （ NVMe ）プロトコルが ONTAP でサポートされるようになりました。 System Manager で設定できます。NVMe はブロックアクセス用の代替プロトコルで、既存の iSCSI プロトコルや FC プロトコルと同様です。

* アグリゲートの推奨構成の提示
+
ストレージの推奨事項に基づいてアグリゲートを作成できます。ストレージシステムの構成が System Manager で分析され、作成するアグリゲートの数、利用可能なノード、利用可能なスペアディスクなど、ストレージの推奨事項が提示されます。

* FabricPool 対応アグリゲートの機能拡張
+
FabricPool 対応アグリゲートが強化され、次の機能がサポートされるようになりました。

+
** 外部の大容量階層のメニュー用の新しい UI ナビゲーションです
** 新しい「 Auto 」キャッシングポリシー
** アクセス頻度の低いコールドデータのサポート
** 外部の大容量階層である StorageGRID 用のオブジェクトストアの証明書がサポートされます
** 外部の大容量階層である Microsoft Azure Blob Storage がサポートされるようになりました
** 詳細については、クラスタダッシュボードの容量タブを参照してください
** ONTAP Select をサポートします
** コマンドラインインターフェイス（ CLI ）を使用して作成された StorageGRID 、 Amazon AWS S3 、および Microsoft Azure Blob Storage 以外の外部の大容量階層の表示


* FlexGroup ボリュームの機能拡張
+
FlexGroup ボリュームの機能拡張と新機能は次のとおりです。

+
** ボリュームの暗号化、 Storage Efficiency 、 QoS などの高度なオプションのサポート
** ボリュームを保護します
** 詳細については、クラスタダッシュボードの保護タブを参照してください


* シングルノードクラスタの停止を伴う更新をサポートします
+
System Manager 9.4 以降では、シングルノードクラスタの更新が可能です。シングルノードクラスタの更新には停止が伴うため、更新中はクライアントデータを使用できません。

* Snapshot コピーの設定がサポートされます
+
既存の Snapshot ポリシーにスケジュールを設定することで、 Snapshot コピーを設定できます。ONTAP 9.4 以降では、 FlexVol ボリュームの Snapshot コピーを最大 1024 個まで保持できます。

* Storage Efficiency の機能拡張
+
使用済み論理スペースの割合と論理スペースのレポートのステータスが、 System Manager の Volumes （ボリューム）ウィンドウに表示されるようになりました。

* SMB マルチチャネルがサポートされます
+
SMB プロトコルを有効にして、パフォーマンスの向上、フォールトトレランス、耐障害性を実現するために、 SMB3.0 セッションと転送接続の間に複数のチャネルを確立することができます。





== ONTAP 9.3 で追加された機能と機能拡張

* Web サービスでの SAML 認証のサポート
+
ONTAP 9.3 以降では、 Security Assertion Markup Language （ SAML ）認証を使用して Web サービスに多要素認証（ MFA ）を設定できます。SAML 認証は、 Service Processor Infrastructure （ spi ）、 ONTAP API 、および System Manager に使用できます。

* アプリケーション対応データ管理
+
アプリケーション対応のデータ管理機能により、ストレージのセットアップが簡易化され、主要なアプリケーションについて、関連するデータを提供することで数分でデータを提供できるようになります。

* GUI とナビゲーションが変更されました
+
グラフィカルユーザインターフェイス（ GUI ）が改良され、操作がよりわかりやすくなりました。

* ONTAP システムと SolidFire システム間の保護関係解除のサポート
+
ONTAP 9.3 以降では、 System Manager を使用して ONTAP システムと SolidFire ストレージシステムの間の SnapMirror 関係を解除できます。

* クラスタピアリングおよび SVM ピアリングの簡易化
+
System Manager の機能が強化され、クラスタ間および SVM 間のピア関係の設定が簡単になりました。

* 設定済みテンプレートを使用した SVM のプロビジョニングがサポートされます
+
ONTAP 9.3 以降では、設定済みテンプレートを使用して SVM を作成およびプロビジョニングできます。

* クラスタダッシュボードの機能拡張
+
クラスタダッシュボードが強化され、ハンドヘルドデバイスでさまざまな情報を表示できるようになりました。


