---
permalink: online-help-96-97/concept_types_data_protection_relationships.html 
sidebar: sidebar 
keywords: data, protection, relationship, asynchronous, replication, type, sychronous, online, help 
summary: データ保護とバックアップの要件に応じて、 ONTAP System Manager は、事故、悪意ある行為、または災害からデータを保護できるように、さまざまな種類の保護関係を提供します。 
---
= データ保護関係のタイプ
:icons: font
:imagesdir: ../media/


[role="lead"]
データ保護とバックアップの要件に応じて、 ONTAP System Manager は、事故、悪意ある行為、または災害からデータを保護できるように、さまざまな種類の保護関係を提供します。



== 非同期レプリケーションタイプ

* ミラー関係 *

ミラー関係は非同期ディザスタリカバリを提供します。データ保護ミラー関係により、 1 つのボリューム上にあるデータの Snapshot コピーを定期的に作成し、それらの Snapshot コピーを通常は別のクラスタ上にあるパートナーボリューム（デスティネーションボリューム）にコピーして、保持することができます。ソースボリューム上のデータが破損した場合や失われた場合には、デスティネーションボリューム上のミラーコピーを使用して、最新の Snapshot コピー時点のデータをすぐに使用およびリストアすることができます。

ミラー関係では ONTAP 、デスティネーションクラスタで実行されている ONTAP のバージョンは、ソースクラスタと同じかそれ以降のバージョンである必要があります。ただし、バージョンに依存しないミラー関係は ONTAP のバージョンには依存しません。そのため、 ONTAP バージョンに依存 ONTAP しないミラー関係は、ソースクラスタよりも新しいバージョンの ONTAP を実行しているデスティネーションクラスタや、ソースクラスタよりも古いバージョンの ONTAP を実行しているデスティネーションクラスタとの間でも作成できます。また、ソースクラスタよりも古いバージョンの ONTAP を使用することもできます。

[NOTE]
====
* ミラー関係を有効にするには、 SnapMirror のライセンスが必要です。
* バージョンに依存しないミラー関係機能を使用できるのは ONTAP 8.3 以降のみです。Data ONTAP 8.3 以前のボリュームとの間でバージョンに依存しないミラー関係を作成することはできません。


====
* バックアップ関係 *

バックアップ関係は、ストレージ効率に優れたバックアップを長期保持します。バックアップ関係により、ボリュームの選択した Snapshot コピーをデスティネーションボリュームにバックアップし、保持することができます。

[NOTE]
====
バックアップ関係を有効にするには、 SnapMirror または SnapVault のライセンスが必要です。

====
* ミラーとバックアップ関係 *

ミラーとバックアップ関係は、ソースボリュームのデータを定期的にデスティネーションボリュームに転送してデータを保護したり、ソースボリュームのバックアップを作成してデータを長期間保持できます。

[NOTE]
====
* ミラーとバックアップ関係を有効にするには、 SnapMirror のライセンスが必要です。
* ミラーとバックアップ関係機能を使用できるのは ONTAP 8.3.2 以降のみです。Data ONTAP 8.3.2 以前のボリュームとの間でミラーとバックアップ関係を作成することはできません。


====


== 同期レプリケーションポリシー（ SnapMirror Synchronous ライセンスが必要）

* StrictSync *

StrictSync レプリケーションポリシーでは、初期化後にレプリケーションに失敗した場合にソースボリュームの入出力（ I/O ）が制限されます。StrictSync レプリケーションポリシーによるデータ保護では、ソースボリュームとデスティネーションボリュームが常に最新の状態に保たれます。

[NOTE]
====
* デスティネーションが Data Protection Optimization （ DPO ）でない場合は、ソースクラスタとデスティネーションクラスタに SnapMirror ライセンスが、ソースクラスタに SnapMirror Synchronous ライセンスが必要です。
* デスティネーションが DPO の場合は、ソースクラスタに SnapMirror Synchronous ライセンスと SnapMirror ライセンスが、デスティネーションクラスタに DPO ライセンスが必要です。


====
* 同期 *

Sync レプリケーションポリシーでは、初期化後にレプリケーションに失敗した場合にソースボリュームの I/O は制限されず、デスティネーションボリュームにデータが転送されなくなります。ソースボリュームとデスティネーションボリュームを最新の状態に保つには、再同期処理を実行する必要があります。

[NOTE]
====
* デスティネーションが Data Protection Optimization （ DPO ）でない場合は、ソースクラスタとデスティネーションクラスタに SnapMirror ライセンスが、ソースクラスタに SnapMirror Synchronous ライセンスが必要です。
* デスティネーションが DPO の場合は、ソースクラスタに SnapMirror Synchronous ライセンスと SnapMirror ライセンスが、デスティネーションクラスタに DPO ライセンスが必要です。


====