---
permalink: online-help-96-97/concept_how_maximum_throughput_limit_works.html 
sidebar: sidebar 
keywords: maximum, throughput, limit, works, objective, storage, qos, policy, group, iops, mbps, online, help 
summary: ストレージ QoS ポリシーグループには、 1 つのサービスレベル目標、つまり最大スループット制限を指定できます。最大スループット制限は IOPS 、 Mbps 、またはその両方の単位で定義します。ポリシーグループ内のすべてのワークロードのスループットの合計がこの値を超えることはできません。 
---
= 最大スループット制限の仕組み
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ QoS ポリシーグループには、 1 つのサービスレベル目標、つまり最大スループット制限を指定できます。最大スループット制限は IOPS 、 Mbps 、またはその両方の単位で定義します。ポリシーグループ内のすべてのワークロードのスループットの合計がこの値を超えることはできません。

あるポリシーグループに最大スループットを指定すると、ストレージ QoS は、そのポリシーグループ内のすべてのワークロードの合計スループットが指定の最大スループットを超えることがないように、クライアント処理を制御します。

たとえば ' ポリシーグループ untested_apps を作成し ' 最大スループットとして 300 Mbps を指定したとしますこのポリシーグループに 3 つのボリュームを割り当てます。3 つのボリュームを合わせたスループットが 300Mbps を超えることはできません。

[NOTE]
====
あるポリシーグループ内の各ワークロードの合計スループットは、最大スループットを 10% までは超えることができます。このような例外的な状況は、あるワークロードのスループットが急激に変化した場合（「 a_workload bursty_」 とも呼ばれます）に発生することがあります。

====
最大スループットの指定については、次の点に注意してください。

* クラスタの利用率が低下する可能性があるため、この制限を低く設定しないでください。
* 制限を適用しないワークロードに対して確保しておくべき最低限のスループット量を考慮する。
+
たとえば、クリティカルでないワークロードを制限することで、クリティカルなワークロードに必要なスループットを確保できます。

* 拡張用のスペースを用意したい場合もあります。
+
たとえば、平均的な利用率が 500IOPS の場合は、制限を 1 、 000IOPS に指定することが考えられます。


