---
permalink: online-help-96-97/concept_how_you_use_ssd_storage_pools.html 
sidebar: sidebar 
keywords: ssd, stprage, pool, flash, aggregate, assign, allocate, online, help 
summary: SSD を複数の Flash Pool アグリゲートで共有できるようにするには、 SSD をストレージプールに追加します。ストレージプールに追加した SSD は、スタンドアロンのエンティティとしては管理できなくなります。その SSD からストレージを割り当てるには、ストレージプールを使用する必要があります。 
---
= SSD ストレージプールを使用する
:icons: font
:imagesdir: ../media/


[role="lead"]
SSD を複数の Flash Pool アグリゲートで共有できるようにするには、 SSD を a_storage pool_ に追加します。ストレージプールに追加した SSD は、スタンドアロンのエンティティとしては管理できなくなります。その SSD からストレージを割り当てるには、ストレージプールを使用する必要があります。

特定のハイアベイラビリティ（ HA ）ペア用にストレージプールを作成できます。作成したら、そのストレージプールから、同じ HA ペアが所有する 1 つ以上の Flash Pool アグリゲートに割り当て単位を追加できます。アグリゲートに割り当てるディスクがアグリゲートを所有するノードに所有されている必要があるのと同様に、ストレージプールは、そのストレージプールが所属するいずれかのノードに所有されている Flash Pool アグリゲートにのみストレージを提供できます。

システムの Flash Pool キャッシュの量を拡張するには、ストレージプールに SSD を追加します。 SSD は、そのストレージプールを使用する Flash Pool キャッシュの RAID タイプの最大 RAID グループサイズまで追加できます。既存のストレージプールに SSD を追加すると、 Flash Pool アグリゲートに割り当て済みの割り当て単位も含めて、ストレージプールの割り当て単位が拡張されます。

ストレージプールに使用できるスペア SSD は 1 本のみです。スペア SSD を用意しておけば、ストレージプール内の SSD に障害が発生した場合に、正常に機能しない SSD のパーティションを ONTAP で再構築できます。割り当て単位をスペア容量として確保する必要はありません。 ONTAP は、ストレージプール内のパーティショニングされていない完全な SSD のみを SSD のスペアとして使用できます。

アグリゲートからディスクを削除できないのと同様に、いったんストレージプールに追加した SSD は削除できません。ストレージプール内の SSD を単独のドライブとして再度使用するには、ストレージプールの割り当て単位が割り当てられている Flash Pool アグリゲートをすべて破棄してから、ストレージプールを破棄する必要があります。
