---
permalink: online-help-96-97/concept_requirements_best_practices_for_using_ssd_storage_pools.html 
sidebar: sidebar 
keywords: requirements, best, practices, ssd, storage, flash, pool, aggregate, online, help 
summary: 一部のテクノロジは、 SSD ストレージプールを使用する Flash Pool アグリゲートと組み合わせることができません。 
---
= SSD ストレージプールを使用する際の要件およびベストプラクティス
:icons: font
:imagesdir: ../media/


[role="lead"]
一部のテクノロジは、 SSD ストレージプールを使用する Flash Pool アグリゲートと組み合わせることができません。

次のテクノロジは、 SSD ストレージプールをキャッシュストレージに使用する Flash Pool アグリゲートでは使用できません。

* MetroCluster
* SyncMirror 機能
+
ミラーされたアグリゲートとストレージプールを使用する Flash Pool アグリゲートは一緒に使用できますが、 Flash Pool アグリゲートはミラーできません。

* 物理 SSD
+
Flash Pool アグリゲートでは、 SSD ストレージプールまたは物理 SSD のどちらか一方を使用できますが、両方は使用できません。



SSD ストレージプールは次のルールに従う必要があります。

* SSD ストレージプールには SSD のみを含めることができます。 HDD は SSD ストレージプールに追加できません。
* SSD ストレージプール内のすべての SSD は、同じハイアベイラビリティ（ HA ）ペアに所有されている必要があります。
* ストレージプール内でルートデータのパーティショニング用にパーティショニングされた SSD は使用できません。


単一のストレージプールから RAID タイプが異なる 2 つのキャッシュにストレージを提供し、ストレージプールのサイズを RAID 4 の最大 RAID グループサイズよりも大きく拡張した場合、 RAID 4 割り当て単位内の余分なパーティションは使用されません。このため、ストレージプール内のキャッシュ RAID タイプは統一することを推奨します。

ストレージプールから割り当てられているキャッシュ RAID グループの RAID タイプは変更できません。最初の割り当て単位を追加する前にキャッシュの RAID タイプを設定すると、あとから変更できません。

ストレージプールを作成したり、 SSD を既存のストレージプールに追加したりするときは、同じサイズの SSD を使用する必要があります。障害発生時に適切なサイズのスペア SSD がない場合、 ONTAP では、より大容量の SSD を使用して障害の発生した SSD を交換できます。ただし、交換後の SSD はストレージプール内の他の SSD と同じサイズに調整されるため、 SSD の容量が失われることになります。

ストレージプールに使用できるスペア SSD は 1 本のみです。HA ペアの両方のノードが所有する Flash Pool アグリゲートにストレージプールが割り当て単位を提供する場合は、どちらのノードでもスペア SSD を所有できます。ただし、 HA ペアの一方のノードが所有する Flash Pool アグリゲートにのみストレージプールが割り当て単位を提供する場合は、その同じノードがスペア SSD を所有する必要があります。
