---
permalink: online-help-96-97/concept_considerations_for_when_to_use_ssd_storage_pools.html 
sidebar: sidebar 
keywords: considerations, ssd, storage, pool, restrictions, online, help 
summary: SSD ストレージプールにはさまざまな利点がありますが、 SSD ストレージプールと専用 SSD のどちらを使用するかを決定する際には、考慮すべき制限事項がいくつかあります。 
---
= SSD ストレージプールを使用するケースに関する考慮事項
:icons: font
:imagesdir: ../media/


[role="lead"]
SSD ストレージプールにはさまざまな利点がありますが、 SSD ストレージプールと専用 SSD のどちらを使用するかを決定する際には、考慮すべき制限事項がいくつかあります。

SSD ストレージプールは、 2 つ以上の Flash Pool アグリゲートにキャッシュを提供する場合にのみ効果を発揮します。SSD ストレージプールには次のようなメリットがあります。

* Flash Pool アグリゲートで使用される SSD のストレージ利用率の向上
+
SSD ストレージプールは、複数の Flash Pool アグリゲートでパリティ SSD を共有できるため、パリティに必要な SSD の全体的な割合が下がります。

* HA パートナー間でのスペアの共有
+
ストレージプールは HA ペアによって所有されるため、 HA パートナーのいずれかに所有される 1 つのスペアが、必要に応じて SSD ストレージプール全体のスペアとして機能します。

* SSD パフォーマンスの利用率が向上します
+
SSD が提供するハイパフォーマンスによって、 HA ペアの両方のコントローラからのアクセスがサポートされます。



SSD ストレージプールを使用する際のこのような利点について、以下の欠点も含めて、その利用コストと比較する必要があります。

* 障害の切り分けが困難
+
1 本の SSD の損失が、そのパーティションに含まれるすべての RAID グループに影響します。この場合、影響を受ける SSD を含む SSD ストレージプールからキャッシュが割り当てられているすべての Flash Pool アグリゲートで、 1 つ以上の RAID グループが再構築されます。

* パフォーマンスの分離が困難
+
Flash Pool キャッシュのサイズを適切に設定しないと、共有している Flash Pool アグリゲート間のキャッシュで競合が発生する可能性があります。このリスクは、適切なキャッシュのサイジングと QoS 管理によって軽減されます。

* 管理の柔軟性の低下
+
ストレージをストレージプールに追加すると、そのストレージプールから 1 つ以上の割り当て単位を含むすべての Flash Pool キャッシュのサイズが拡張されます。追加の容量の配分方法は指定できません。


