---
permalink: online-help-96-97/concept_benefits_storage_efficiency.html 
sidebar: sidebar 
keywords: benefit, storage, efficiency, flexcone, flexvol, snapshot, copy, deduplication, data, compression, snapmirror, online, help, classic 
summary: Storage Efficiency を使用すると、低コストで最大限のデータを格納し、スペースを節約しつつ、急増するデータに対応することができます。RAID-DP 、 FlexVol 、 Snapshot コピー、重複排除、データ圧縮などのテクノロジを使用できます。 SnapMirror 、 FlexClone を使用してストレージ利用率を高め、ストレージコストを削減これらのテクノロジを組み合わせて使用すると、パフォーマンスが向上します。 
---
= Storage Efficiency の利点
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Efficiency を使用すると、低コストで最大限のデータを格納し、スペースを節約しつつ、急増するデータに対応することができます。RAID-DP 、 FlexVol 、 Snapshot コピー、重複排除、データ圧縮などのテクノロジを使用できます。 SnapMirror 、 FlexClone を使用してストレージ利用率を高め、ストレージコストを削減これらのテクノロジを組み合わせて使用すると、パフォーマンスが向上します。

* Serial Advanced Technology Attachment （ SATA ）ドライブなどの高密度ディスクドライブと RAID-DP テクノロジを組み合わせると、効率と読み取りパフォーマンスが向上します。
* RAID-DP は、ダブルパリティの RAID6 実装であり、二重のディスクドライブ障害からシステムを保護します。
* シンプロビジョニングを使用すると、必要に応じて他のアプリケーションですぐに使用できる未割り当ての共通ストレージスペースを維持できます。
+
FlexVol テクノロジに基づいています。

* Snapshot コピーは、データボリュームのある時点における読み取り専用のコピーで、最小限のストレージスペースしか消費しません。
+
連続して作成された 2 つの Snapshot コピーで異なるのは、 2 つのコピーの間に追加または変更されたブロックのみです。この増分ブロックを使用することで、コピーによって消費されるストレージ容量が制限されます。

* 重複排除は、 FlexVol ボリューム内の冗長データブロックを排除して、ストレージスペースを節約します。
* データ圧縮は、より少ないスペースにより多くのデータを格納し、 Volume SnapMirror 転送でデータをレプリケートするために必要な時間と帯域幅を削減する機能です。
+
要件やストレージシステムの設定に基づいて圧縮形式（インラインまたはバックグラウンド）を選択する必要があります。インライン圧縮では、データが圧縮可能かどうかが確認されたあとにデータが圧縮され、ボリュームにデータが書き込まれます。バックグラウンド圧縮は、すべてのデータがボリュームに書き込まれたあとに、ファイルが圧縮可能かどうかに関係なく、すべてのファイルに対して実行されます。

* SnapMirror テクノロジは、ローカルエリア、ワイドエリア、およびファイバチャネルの各ネットワークでデータをレプリケートするための柔軟な解決策です。
+
企業のデータ保護戦略を実行する場合に、このソリューションは重要な要素として機能します。データを 1 つ以上のストレージシステムにレプリケートすることで、本番用サイトに障害が発生した場合のダウンタイムコストを最小限に抑えることができます。SnapMirror テクノロジを使用すると、データのバックアップ先を複数のデータセンターからディスクに統合することもできます。

* FlexClone テクノロジは、データボリューム、ファイル、および LUN を瞬時の仮想コピーとしてコピーします。
+
FlexClone ボリューム、ファイルまたは LUN は、 FlexVol 、別の FlexClone ボリューム、ファイル、または LUN の、任意の時点の書き込み可能なイメージです。このテクノロジを使用すると、スペースを効率的に使用し、親とクローンで変更されたデータのみを格納できます。

* ユニファイドアーキテクチャは、マルチプロトコルサポートを統合して、ファイルベースとブロックベースの両方のストレージを単一のプラットフォームで実現します。
+
FlexArray 仮想化を使用すると、ストレージインフラ全体を 1 つのインターフェイスを通して仮想化し、ネットアップ以外のシステムでも上記の効率化をすべて実現できます。


