---
permalink: online-help-96-97/concept_how_system_manager_calculates_hot_spares.html 
sidebar: sidebar 
keywords: system, manager, hot, spares, disk, storage, raid, online, help 
summary: ホットスペアは、ストレージシステムに割り当てられているものの、どの RAID グループでも使用されていないディスクです。ホットスペアはデータを含んでおらず、 RAID グループで障害が発生した場合にその RAID グループに割り当てられます。System Manager は、最大のディスクをホットスペアとして使用します。 
---
= System Manager とホットスペアとの相互運用性 - ONTAP 9.7 以前
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホットスペアは、ストレージシステムに割り当てられているものの、どの RAID グループでも使用されていないディスクです。ホットスペアはデータを含んでおらず、 RAID グループで障害が発生した場合にその RAID グループに割り当てられます。ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）では、最大のディスクをホットスペアとして使用します。

RAID グループに複数のディスクタイプがある場合、それぞれのディスクタイプでサイズの一番大きなディスクがホットスペアとして確保されます。たとえば、 RAID グループに SATA ディスクと SAS ディスクがそれぞれ 10 本ずつある場合、最大サイズの SATA ディスクと最大サイズの SAS ディスクがホットスペアになります。

最大サイズのディスクがパーティショニングされている場合、パーティショニングされている RAID グループとされていない RAID グループそれぞれにホットスペアが提供されます。最大サイズのディスクがパーティショニングされていない場合、 1 本のスペアディスクが提供されます。

ディスクグループにルートパーティションがある場合は、最大サイズのパーティショニングされていないディスクがホットスペアとして確保されます。同じサイズのパーティショニングされていないディスクを使用できない場合、スペアルートパーティションはルートパーティショングループのホットスペアとして確保されます。

1 本のスペアディスクを複数の RAID グループのホットスペアとして使用することができます。System Manager は ' ノード・レベルでオプション raid.min_spare_count に設定した値に基づいてホット・スペア数を計算しますたとえば、 SSD RAID グループに 10 個の SSD があり、オプション「 raid.min_spare_count 」がノードレベルで「 1 」に設定されている場合、 System Manager は 1 個の SSD をホットスペアとして残し、他の 9 個の SSD を SSD 関連の操作に使用します。同様に、 HDD RAID グループに HDD が 10 台あり、オプション「 raid.min_spare_count 」がノードレベルで「 2 」に設定されている場合、 System Manager は 2 本の HDD をホットスペアとして残し、他の 8 本を HDD 関連の処理に使用します。

アグリゲートの作成、編集、およびアグリゲートへの HDD または SSD の追加を行う際に、 System Manager は、 RAID グループにホットスペアルールを適用します。ホットスペアルールは、ストレージプールの作成時、または既存のストレージプールへのディスクの追加時にも使用されます。

System Manager には、ホットスペアルールの例外があります。

* MSATA またはマルチディスクキャリアのディスクの場合、ホットスペアの数は、ノードレベルで設定した値の 2 倍、かつ 2 本を下回ることがないようにする必要があります。
* ディスクがアレイ LUN または仮想ストレージアプライアンスの一部である場合、ホットスペアは使用されません。

