---
permalink: online-help-96-97/concept_nvme_namespaces.html 
sidebar: sidebar 
keywords: NVMe, protocol, namespace, subsystem, provision, nvm, logical, block, fc, lun, iscsi, storage, virtual, machine 
summary: NVMe ネームスペースは、論理ブロックにフォーマット可能な不揮発性メモリ（ NVM ）の容量です。ネームスペースは、 Storage Virtual Machine で NVMe プロトコルが設定されている場合に使用され、 FC および iSCSI プロトコルの LUN に相当します。 
---
= NVMe ネームスペース
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMe ネームスペースは、論理ブロックにフォーマット可能な不揮発性メモリ（ NVM ）の容量です。ネームスペースは、 Storage Virtual Machine で NVMe プロトコルが設定されている場合に使用され、 FC および iSCSI プロトコルの LUN に相当します。

NVMe ホストには、 1 つ以上のネームスペースがプロビジョニングされて接続されます。各ネームスペースがさまざまなブロックサイズをサポートできます。

NVMe プロトコルは、複数のコントローラ経由でネームスペースへのアクセスを提供します。ほとんどのオペレーティングシステムでサポートされている NVMe ドライバを使用すると、 Solid State Drive （ SSD ；ソリッドステートドライブ）ネームスペースは標準ブロックデバイスとして表示され、そのままでファイルシステムとアプリケーションを導入できます。

ネームスペース ID （ NSID ）は、コントローラがネームスペースへのアクセスを提供するために使用する識別子です。ホストまたはホストグループに対して NSID を設定する場合は、ホストからボリュームへのアクセスも設定します。論理ブロックは一度に 1 つのホストグループにのみマッピングでき、同じホストグループに複数の NSID が割り当てられることはありません。



== NVMe ネームスペースの NVMe サブシステムのプロビジョニング

NVMe サブシステムには、 1 つ以上の NVMe コントローラ、ネームスペース、 NVM サブシステムポート、 NVM ストレージメディア、およびコントローラと NVM ストレージメディア間のインターフェイスが含まれます。NVMe ネームスペースを作成する際、 NVMe サブシステムをネームスペースにマッピングする方法を次の中から選択できます。

* * なし（デフォルト） *
+
NVMe サブシステムをネームスペースにマッピングしません。

* * 既存サブシステム *
+
既存の NVMe サブシステムを選択してネームスペースにマッピングします。NVMe サブシステムはホスト OS と SVM のフィールドに基づいて表示されます。NVMe サブシステムの名前にポインタを合わせると、サブシステムに関する詳細が表示されます。

* * 新しいサブシステム *
+
新しい NVMe サブシステムを作成してネームスペースにマッピングします。ホスト OS と SVM にサブシステムが作成されます。



サブシステムをプロビジョニングするには、次の詳細情報を指定します。

* * NVMe サブシステム名 *
+
NVMe サブシステムの名前では大文字と小文字が区別されます。1~96 文字で指定する必要があり、特殊文字を使用できます。

* * ホスト OS *
+
サブシステムの作成先であるホストの OS タイプ。

* * ホスト NQN *
+
コントローラに接続するホスト NVMe の修飾名。サブシステムには複数のホストを接続できるため、この列では値をカンマで区切って指定できます。


