---
permalink: online-help-96-97/concept_minimum_number_hot_spares_you_should_have.html 
sidebar: sidebar 
keywords: minimum, number, hot, spares, disks, requirement, technical, support, online, help 
summary: 十分なスペアを用意しておかないと、ディスクで障害が発生したときにスペアを利用できず、 RAID グループがデグレード状態になる危険が高まります。コントローラが停止した場合にテクニカルサポートに重要な情報（コアファイル）を提供するためにも、スペアディスクが必要です。 
---
= ディスクに最低限必要なホットスペアの数
:icons: font
:imagesdir: ../media/


[role="lead"]
十分なスペアを用意しておかないと、ディスクで障害が発生したときにスペアを利用できず、 RAID グループがデグレード状態になる危険が高まります。コントローラが停止した場合にテクニカルサポートに重要な情報（ a_core file_ ）を提供するためにも、スペアディスクが必要です。

MSATA ディスクまたはマルチディスクキャリアのディスクの場合、安定した状態では 4 つのホットスペアを用意し、 MSATA ホットスペアの数が 2 つを下回ることがないようにする必要があります。

SSD で構成される RAID グループの場合は、少なくとも 1 つのスペアディスクを用意しておく必要があります。

それ以外の ONTAP ディスクタイプについては、ストレージシステムに設置されているディスクの種類ごとに、少なくとも 1 つの一致するホットスペアまたは適切なホットスペアを用意しておく必要があります。ただし、すべてのディスクに対して 2 つのホットスペアを用意しておくと、ディスク障害に対する最良の保護を実現できます。2 つ以上のホットスペアを用意すると、次のような利点があります。

* データディスクのホットスペアが 2 つ以上あれば、必要に応じて ONTAP でそのディスクを Maintenance Center に割り当てることができます。
+
ONTAP では、 Maintenance Center を使用して疑いのあるディスクをテストし、問題のあるディスクをオフラインにします。

* ホットスペアが 2 つあれば、 1 つのディスクに障害が発生し、そのディスクを交換する前に別のディスクに障害が発生しても、スペアディスクを使用できます。


1 本のスペアディスクを複数の RAID グループのホットスペアとして使用することができます。ただし、これらの RAID グループのいずれかのディスクで障害が発生すると、スペアディスクを交換するまでの間にさらにディスクに障害が発生した場合や、コアファイル用に使用できるスペアディスクがありません。したがって、スペアを複数用意することを推奨します。
