---
permalink: online-help-96-97/concept_quota_limits.html 
sidebar: sidebar 
keywords: quota, limit, disk, space, files 
summary: クォータタイプごとにディスクスペース制限を適用するか、ファイル数を制限できます。クォータの制限を指定しない場合、何も適用されません。 
---
= クォータ制限
:icons: font
:imagesdir: ../media/


[role="lead"]
クォータタイプごとにディスクスペース制限を適用するか、ファイル数を制限できます。クォータの制限を指定しない場合、何も適用されません。

クォータには、ソフトクォータとハードクォータがあります。ソフトクォータ原因 Data ONTAP では、指定された制限を超過すると通知が送信されますが、ハードクォータでは、指定された制限を超過すると書き込み処理が失敗します。

ハードクォータを設定すると、システムリソースにハードリミットが適用されます。実行することで制限値を超えてしまう処理は、すべて失敗します。以下の設定でハードクォータを作成します。

* ディスク制限パラメータ
* ファイル制限パラメータ


ソフトクォータを設定すると、リソース使用量が特定のレベルに達したときに警告メッセージが送信されますが、データアクセス処理には影響しません。そのため、クォータを超過する前に適切な処理を実行できます。ソフトクォータは以下の設定で構成されます。

* ディスク制限しきい値パラメータ
* ディスクのソフトリミットパラメータ
* ファイルのソフトリミットパラメータ


しきい値クォータとソフトディスククォータを使用すると、管理者はクォータについての通知を複数受け取ることができます。通常、書き込みが失敗し始める前にしきい値によって「最終警告」が通知されるようにするため、管理者はディスク制限のしきい値をディスク制限よりもわずかに小さい値に設定します。

* * ディスク容量のハードリミット *
+
ハードクォータに適用されるディスクスペース制限。

* * ディスク容量のソフトリミット *
+
ソフトクォータに適用されるディスクスペース制限。

* * しきい値制限 *
+
しきい値クォータに適用されるディスクスペース制限。

* * ファイルのハードリミット *
+
ハードクォータの最大ファイル数。

* * ファイルソフトリミット *
+
ソフトクォータの最大ファイル数。


