---
permalink: online-help-96-97/concept_how_snapmirror_relationships_work.html 
sidebar: sidebar 
keywords: snapmirror, relationship, data, protection, mirror, destination, cluster, online, help 
summary: データを保護するために、クラスタ内のデスティネーションに対するデータ保護ミラー関係を作成することができます。災害に対する保護を強化するために、別の場所にある異なるクラスタ内のデスティネーションに対するミラー関係も作成できます。 
---
= SnapMirror 関係の仕組み
:icons: font
:imagesdir: ../media/


[role="lead"]
データを保護するために、クラスタ内のデスティネーションに対するデータ保護ミラー関係を作成することができます。災害に対する保護を強化するために、別の場所にある異なるクラスタ内のデスティネーションに対するミラー関係も作成できます。

データ保護ミラーは、 1 つ以上のデスティネーションボリュームにレプリケートできるソースボリュームで構成されます。データ保護ミラー関係はそれぞれ独立しており、他のデータ保護ミラー関係には依存しません。

[NOTE]
====
デスティネーションボリューム ONTAP で、ソースボリュームと同じかそれ以降のバージョンの ONTAP が実行されている必要があります。

====
デスティネーションボリュームは、 Snapshot コピーを使用して更新されます。ソースボリュームからディステーションボリュームへの Snapshot コピーの転送は、スケジュールに従って自動で行われるか手動で行われるため、ミラーコピーは非同期的に更新されます。

データ保護ミラー関係は、ソースボリュームと同じアグリゲートにあるデスティネーション、および同じ Storage Virtual Machine （ SVM ）または異なる SVM にあるデスティネーションに対して作成できます。保護を強化するには、別のアグリゲートにあるデスティネーションに対する関係を作成します。これにより、ソースボリュームのアグリゲートで障害が発生してもデータをリカバリできます。ただし、これらの構成は、クラスタの障害に対する保護にはなりません。

クラスタの障害からデータを保護するには、ソースボリュームとは異なるクラスタにあるデスティネーションボリュームを指定してデータ保護ミラー関係を作成します。ソースボリュームが配置されているクラスタで障害が発生した場合、ソースボリュームが再び使用できるようになるまで、ユーザクライアントにクラスタピアのデスティネーションボリュームへの転送を指示できます。
