---
permalink: online-help-96-97/concept_how_you_update_cluster_nondisruptively.html 
sidebar: sidebar 
keywords: update, cluster, nondisruptively, plan, perpare, perform, system, manager, online, help 
summary: System Manager を使用して、クラスタを特定のバージョンの ONTAP に無停止で更新できます。無停止での更新では、 ONTAP イメージを選択し、クラスタを更新する準備ができているかどうかを確認してから、更新を実行します。 
---
= クラスタを無停止で更新
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して、クラスタを特定のバージョンの ONTAP に無停止で更新できます。無停止での更新では、 ONTAP イメージを選択し、クラスタを更新する準備ができているかどうかを確認してから、更新を実行します。

無停止での更新では、クラスタをオンラインにしたまま更新が実行され、更新中もデータの提供が継続され



== 更新の計画と準備

クラスタの更新の計画および準備として、クラスタを更新する新しいバージョンの ONTAP イメージをネットアップサポートサイトから取得し、ソフトウェアイメージを選択して、検証を実行する必要があります。更新前の検証では、クラスタを選択したバージョンに更新する準備ができているかどうかを確認します。

検証でエラーや警告が報告された場合は、修復アクションを実行してそれらを解決し、クラスタコンポーネントを更新する準備ができているかどうかを確認する必要があります。たとえば、更新前の検証で、オフラインアグリゲートがクラスタ内に存在するという警告が表示された場合は、アグリゲートページに移動して、すべてのオフラインアグリゲートのステータスをオンラインに変更する必要があります。



== 更新を実行しています

クラスタを更新すると、クラスタ全体またはハイアベイラビリティ（ HA ）ペアのノードが更新されます。更新の一環として、クラスタを更新する準備ができているかどうかの更新前検証がもう一度実行されます。

クラスタ内のノード数に応じて、ローリング更新または一括更新が実行されます。

* * ローリング更新 *
+
1 つのノードをオフラインにして更新し、その間、パートナーノードがそのノードのストレージをテイクオーバーします。

+
ローリング更新は、 2 つ以上のノードで構成されるクラスタに対して実行されます。8 ノード未満のクラスタの場合、これが唯一の更新方法です。

* * バッチ更新 *
+
それぞれ複数の HA ペアを含む 2 つのバッチにクラスタを分けて更新します。

+
一括更新は、 8 つ以上のノードで構成されるクラスタに対して実行されます。このようなクラスタでは、一括更新かローリング更新のどちらかを実行できます。8 ノード以上のクラスタの場合、これがデフォルトの更新方法です。



* 関連情報 *

xref:task_updating_cluster_nondisruptively.adoc[クラスタを無停止で更新]
