---
permalink: online-help-96-97/concept_thin_provisioning_for_greater_efficiencies_using_flexvol_volumes.html 
sidebar: sidebar 
keywords: thin, provisioning, greater, efficiencies, flexvol, volume, online, help, lun 
summary: シンプロビジョニングでは、ボリュームや LUN を特定のアグリゲート内に作成する場合に、それらに対して事前にスペースが割り当てられません。スペースは、ボリュームまたは LUN にデータが書き込まれるときに割り当てられます。 
---
= FlexVol ボリュームを使用したシンプロビジョニングによる効率化
:icons: font
:imagesdir: ../media/


[role="lead"]
シンプロビジョニングでは、ボリュームや LUN を特定のアグリゲート内に作成する場合に、それらに対して事前にスペースが割り当てられません。スペースは、ボリュームまたは LUN にデータが書き込まれるときに割り当てられます。

アグリゲートの未使用のスペースは、他のボリュームや LUN に使用できます。シンプロビジョニングを使用すると、プロビジョニングとスペース再生が必要に応じて行われるため、ストレージ利用率が向上し、ストレージコストを削減できます。

FlexVol ボリュームは、その包含アグリゲートを他の FlexVol ボリュームと共有できます。したがって、 1 つのアグリゲートが、そのアグリゲートに含まれる FlexVol ボリュームで使用されるすべてのストレージのソースとして共有されます。フレキシブルボリュームは、所属するディスクの制限に制約されなくなります。FlexVol ボリュームのサイズは、ディスクのサイズではなく、格納するデータの量に基づいて変更できます。この柔軟性により、ストレージシステムのパフォーマンスと容量利用率を最大限に高めることができます。FlexVol ボリュームはシステム内の使用可能なすべての物理ストレージにアクセスできるため、ストレージ利用率の向上が可能です。

500GB のボリュームが割り当てられていますが、実際のデータは 100GB だけで、残りの 400GB にはデータが格納されていません。この未使用の容量はビジネスアプリケーションに割り当てられていますが、このアプリケーションで 400GB すべてが必要になることはありません。未使用の状態で割り当てられている 400GB は余剰な容量であり、当面は無駄になってしまいます。

シンプロビジョニングを使用すると、ストレージ管理者は 500GB をビジネスアプリケーションにプロビジョニングしますが、 100GB だけをデータに使用しています。シンプロビジョニングが異なるのは、未使用の 400GB を他のアプリケーションで使用できる点です。このアプローチでは、アプリケーションが透過的に拡張され、アプリケーションで必要となった場合にのみ物理ストレージが完全に割り当てられます。残りのストレージは、必要に応じて空きプールに残ります。
