---
permalink: online-help-96-97/concept_what_snapvault_backup_is.html 
sidebar: sidebar 
keywords: baseline, transfer, defined, snapvault, snapshot, copy, online, help 
summary: SnapVault バックアップは、プライマリデータを使用できない場合にデータのリストアに使用できる FlexVol ボリューム上の Snapshot コピーの集まりです。Snapshot コピーは、 Snapshot ポリシーに基づいて作成されます。SnapVault バックアップでは、スケジュールおよび SnapVault ポリシールールに基づいて Snapshot コピーがバックアップされます。 
---
= SnapVault バックアップとは
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapVault バックアップは、プライマリデータを使用できない場合にデータのリストアに使用できる FlexVol ボリューム上の Snapshot コピーの集まりです。Snapshot コピーは、 Snapshot ポリシーに基づいて作成されます。SnapVault バックアップでは、スケジュールおよび SnapVault ポリシールールに基づいて Snapshot コピーがバックアップされます。

SnapVault バックアップは、テープバックアップのオフロードにも使用できるディスクツーディスクのバックアップ解決策です。システムでデータの消失や破損が発生した場合、 SnapVault のセカンダリボリュームからバックアップデータをリストアできます。従来のテープによるバックアップ / リストア操作に比べてダウンタイムを短縮でき、不確定要素も削減されます。

SnapVault バックアップの説明には、次の用語が使用されます。

* * ベースライン転送 *
+
プライマリストレージの最初の完全バックアップ。セカンダリシステム上の対応するボリュームに格納されます。

* * セカンダリボリューム *
+
プライマリボリュームのデータのバックアップ先のボリューム。このボリュームは、カスケード構成やファンアウト構成では、セカンダリまたはターシャリ（およびそれ以降）のデスティネーションにもなります。SnapVault セカンダリシステムには、長期のデータ保存と予期されるリストアに備えて、複数の Snapshot コピーが維持されます。

* * 増分転送 *
+
2 回目以降のセカンダリシステムへのバックアップ。前回の転送以降に行われたプライマリデータに対する変更内容のみが含まれます。

* * SnapMirror ラベル *
+
Snapshot コピーを識別する属性。 SnapVault バックアップで Snapshot コピーを選択して保持します。各 SnapVault ポリシーでは、プライマリボリュームの Snapshot コピーを選択するルールと、指定した SnapMirror ラベルに一致する Snapshot コピーを転送するルールを設定します。

* * Snapshot コピー *
+
ソースボリューム上のバックアップイメージ。手動で作成することも、割り当てたポリシーのスケジュールに従って自動的に作成することもできます。ベースライン Snapshot コピーには保護対象のソースデータ全体のコピーが含まれ、以降の Snapshot コピーにはソースデータの差分コピーが含まれます。Snapshot コピーは、ソースボリュームのほか、別の Storage Virtual Machine （ SVM ）またはクラスタのデスティネーションボリュームにも格納できます。

+
Snapshot コピーには、各ソースシステム上のボリュームデータの状態がキャプチャされます。SnapVault 関係とミラー関係では、このデータがデスティネーションボリュームに転送されます。

* * 主音量 *
+
バックアップするデータを含むボリューム。カスケード構成またはファンアウト構成では、チェーン内での SnapVault ソースの位置に関係なく、 SnapVault バックアップにバックアップされるボリュームがプライマリボリュームとなります。カスケードチェーン構成で、 A から B へのミラー関係が確立され、 B から C への SnapVault 関係が確立されている場合、 B はチェーン内のセカンダリデスティネーションですが、 SnapVault バックアップのソースとして機能します。

* * SnapVault 関係 *
+
プライマリボリュームとセカンダリボリュームの間のバックアップ関係。 SnapVault 関係として設定されます。



* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]
