---
permalink: online-help-96-97/reference_windows_window.html 
sidebar: sidebar 
keywords: storage, virtual, machine, svm, cluster, online, help, user, tab, command, buttons, group 
summary: Windows ウィンドウを使用して、クラスタ上の各 Storage Virtual Machine （ SVM ）の Windows ローカルユーザとローカルグループのリストを管理できます。Windows のローカルユーザおよびローカルグループは、認証やネームマッピングに使用できます。 
---
= System Manager - ONTAP 9.7 以前のバージョンの Windows ウィンドウ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP システムマネージャクラシック（ ONTAP 9.7 以前で使用可能）を使用して、 Windows ウィンドウを使用できます。Windows ウィンドウを使用して、クラスタの各 Storage Virtual Machine （ SVM ）の Windows ローカルユーザとローカルグループのリストを管理できます。Windows のローカルユーザおよびローカルグループは、認証やネームマッピングに使用できます。



== [ ユーザー ] タブ

ユーザタブを使用して、 SVM に対してローカルな Windows ユーザを表示できます。



== コマンドボタン

* * 作成 * 。
+
Create User ダイアログボックスを開きます。このダイアログボックスで、 SVM に格納されたデータへの SMB 接続を介したアクセスの許可に使用できる Windows ローカルユーザアカウントを作成できます。

* * 編集 * 。
+
ユーザの編集ダイアログボックスを開きます。このダイアログボックスで、グループメンバーシップやフルネームなど、 Windows のローカルユーザプロパティを編集できます。また、ユーザアカウントを有効または無効にすることもできます。

* * 削除 *
+
ユーザの削除ダイアログボックスを開きます。このダイアログボックスで、不要になった Windows ローカルユーザアカウントを SVM から削除できます。

* * グループに追加 *
+
[ グループの追加 ] ダイアログボックスを開きます。このダイアログボックスでは、グループに関連付けられている権限をユーザアカウントに割り当てることができます。

* * パスワードの設定 *
+
[ パスワードのリセット ] ダイアログボックスを開きます。このダイアログボックスで、 Windows ローカルユーザのパスワードをリセットできます。パスワードのリセットは、たとえば、パスワードが漏れた場合やパスワードを忘れた場合などに行います。

* * 名前を変更 *
+
[ ユーザー名の変更 ] ダイアログボックスを開きます。このダイアログボックスで、 Windows ローカルユーザーアカウントの名前をわかりやすい名前に変更できます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== ユーザリスト

* * 名前 *
+
ローカルユーザの名前が表示されます。

* * 氏名 *
+
ローカルユーザのフルネームが表示されます。

* * アカウントが無効になっています *
+
ローカルユーザアカウントが有効になっているか無効になっているかが表示されます。

* * 概要 *
+
このローカルユーザの概要を表示します。





== ユーザーの詳細領域

* * グループ *
+
ユーザが属しているグループのリストが表示されます。





== [ グループ ] タブ

SVM に対してローカルな Windows グループを追加、編集、削除するには、グループタブを使用します。



== コマンドボタン

* * 作成 * 。
+
Create Group ダイアログボックスを開きます。このダイアログボックスで、 SVM に格納されたデータへの SMB 接続を介したアクセスの認証に使用できる Windows ローカルグループを作成できます。

* * 編集 * 。
+
グループの編集ダイアログボックスを開きます。このダイアログボックスで、グループに割り当てられた権限やグループの概要など、 Windows ローカルグループのプロパティを編集できます。

* * 削除 *
+
グループの削除ダイアログボックスを開きます。このダイアログボックスで、不要になったローカル Windows グループを SVM から削除できます。

* * メンバーを追加 *
+
[ メンバーの追加 ] ダイアログボックスが開きます。このダイアログボックスで、ローカルまたは Active Directory ユーザー、または Active Directory グループをローカル Windows グループに追加できます。

* * 名前を変更 *
+
[ グループ名の変更 ] ダイアログボックスを開きます。このダイアログボックスで、 Windows ローカルグループの名前をわかりやすい名前に変更できます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== グループリスト（ Groups List ）

* * 名前 *
+
ローカルグループの名前が表示されます。

* * 概要 *
+
このローカルグループの概要が表示されます。





== グループの詳細領域

* * 特権 *
+
選択したグループに関連付けられている権限のリストが表示されます。

* * ユーザー *
+
選択したグループに関連付けられているローカルユーザのリストが表示されます。



* 関連情報 *

xref:task_creating_local_user_group.adoc[Windows ローカルグループを作成します]

xref:task_editing_local_windows_group_properties.adoc[Windows ローカルグループのプロパティを編集します]

xref:task_adding_user_accounts_to_windows_local_group.adoc[Windows ローカルグループへのユーザアカウントの追加]

xref:task_renaming_local_windows_group.adoc[Windows ローカルグループの名前変更]

xref:task_deleting_local_windows_group.adoc[Windows ローカルグループを削除する]

xref:task_creating_local_windows_user_accounts.adoc[Windows ローカルユーザアカウントの作成]

xref:task_editing_local_windows_user_properties.adoc[Windows ローカルユーザのプロパティを編集する]

xref:task_assigning_group_memberships_to_user_account.adoc[ユーザアカウントへのグループメンバーシップの割り当て]

xref:task_renaming_local_windows_user.adoc[Windows ローカルユーザの名前変更]

xref:task_changing_password_for_windows_local_users.adoc[Windows ローカルユーザのパスワードをリセットする]

xref:task_deleting_local_windows_user_account.adoc[Windows ローカルユーザアカウントを削除する]
