---
permalink: online-help-96-97/reference_export_policies.html 
sidebar: sidebar 
keywords: export, policy, window, online, help, command, button, assigned, exports 
summary: Export Policies ウィンドウを使用して、エクスポートポリシーおよび関連するエクスポートルールに関する情報を作成、表示、および管理できます。 
---
= [ エクスポートポリシー ] ウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
Export Policies ウィンドウを使用して、エクスポートポリシーおよび関連するエクスポートルールに関する情報を作成、表示、および管理できます。



== エクスポートポリシー

Export Policies ウィンドウを使用して、 Storage Virtual Machine （ SVM ）に対して作成されたエクスポートポリシーを表示および管理できます。

* * コマンドボタン *
+
** 作成
+
Create Export Policy ダイアログボックスを開きます。このダイアログボックスで、エクスポートポリシーを作成し、エクスポートルールを追加できます。また、既存の SVM からエクスポートルールをコピーすることもできます。

** 名前を変更する
+
ポリシーの名前変更ダイアログボックスが開き、選択したエクスポートポリシーの名前を変更できます。

** 削除
+
Delete Export Policy ダイアログボックスを開きます。このダイアログボックスで、選択したエクスポートポリシーを削除できます。

** 更新
+
ウィンドウ内の情報を更新します。







== [ エクスポートルール ] タブ

Export Rules タブでは、特定のエクスポートポリシーに対して作成されたエクスポートルールに関する情報を表示できます。ルールを追加、編集、削除することもできます。

* * コマンドボタン *
+
** 追加（ Add ）
+
Create Export Rule ダイアログボックスを開きます。このダイアログボックスで、選択したエクスポートポリシーにエクスポートルールを追加できます。

** 編集
+
Modify Export Rule ダイアログボックスが開き、選択したエクスポートルールの属性を変更できます。

** 削除
+
Delete Export Rule ダイアログボックスを開きます。このダイアログボックスで、選択したエクスポートルールを削除できます。

** 上に移動します
+
選択したエクスポートルールのルールインデックスを上に移動します。

** 下に移動します
+
選択したエクスポートルールのルールインデックスを下に移動します。

** 更新
+
ウィンドウ内の情報を更新します。



* * エクスポートルールリスト *
+
** ルールインデックス
+
エクスポートルールを処理する優先度を指定します。[ 上へ移動 ] ボタンと [ 下へ移動 ] ボタンを使用して、優先度を選択できます。

** クライアント
+
ルールを適用するクライアントを指定します。

** アクセスプロトコル
+
エクスポートルールに対して指定されているアクセスプロトコルが表示されます。

+
アクセスプロトコルを指定しなかった場合、デフォルト値の「 any 」が考慮されます。

** 読み取り専用ルール
+
読み取り専用アクセスのセキュリティタイプを 1 つ以上指定します。

** 読み取り / 書き込みルール
+
読み取り / 書き込みアクセスのセキュリティタイプを 1 つ以上指定します。

** スーパーユーザアクセス
+
スーパーユーザアクセスのセキュリティタイプを 1 つ以上指定します。







== [ 割り当て済みオブジェクト ] タブ

割り当て済みオブジェクトタブでは、選択したエクスポートポリシーに割り当てられているボリュームと qtree を表示できます。ボリュームが暗号化されているかどうかも確認できます。
