---
permalink: online-help-96-97/reference_snmp_window.html 
sidebar: sidebar 
keywords: snmp, window, command, button, protocol, trap, hosts, settings, online, help 
summary: SNMP ウィンドウでは、システムの現在の SNMP 設定を確認できます。また、システムの SNMP 設定の変更、 SNMP プロトコルの有効化、およびトラップホストの追加もできます。 
---
= SNMP ウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
SNMP ウィンドウでは、システムの現在の SNMP 設定を確認できます。システムの SNMP 設定の変更、 SNMP プロトコルの有効化、およびトラップホストの追加も行うことができます。



== コマンドボタン

* * 有効 / 無効 *
+
SNMP を有効または無効にします。

* * 編集 * 。
+
SNMP 設定の編集ダイアログボックスを開きます。このダイアログボックスで、ストレージシステムの SNMP コミュニティを指定し、トラップを有効または無効にすることができます。

* * トラップホストのテスト *
+
設定済みのすべてのホストにテストトラップを送信して、テストトラップがすべてのホストに到達するかどうか、および SNMP が正しく設定されているかどうかを確認します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== 詳細

詳細領域には、ストレージシステムの SNMP サーバとトラップホストに関する次の情報が表示されます。

* * SNMP *
+
SNMP が有効になっているかどうかが表示されます。

* * トラップ *
+
SNMP トラップが有効になっているかどうかが表示されます。

* * 場所 *
+
SNMP サーバのアドレスが表示されます。

* * 連絡先 *
+
SNMP サーバの連絡先の詳細が表示されます。

* * トラップホスト IP アドレス *
+
トラップホストの IP アドレスが表示されます。

* * コミュニティ名 *
+
SNMP サーバのコミュニティ名が表示されます。

* * セキュリティ名 *
+
SNMP サーバのセキュリティ形式が表示されます。



* 関連情報 *

xref:task_setting_snmp_information.adoc[SNMP 情報の編集]

xref:task_enabling_or_disabling_snmp_traps.adoc[SNMP トラップの有効化または無効化]
