---
permalink: online-help-96-97/reference_storage_pools_window.html 
sidebar: sidebar 
keywords: storage, pools, window, online, help, command, button 
summary: ストレージプールウィンドウを使用して、 SSD の専用キャッシュ（ストレージプールとも呼ばれます）を作成、表示、および管理できます。ストレージプールはルート以外のアグリゲートに関連付けて SSD キャッシュを提供したり、 Flash Pool アグリゲートに関連付けてサイズを拡張したりできます。 
---
= ストレージプールウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Pools （ストレージプール）ウィンドウを使用して、 SSD の専用キャッシュ（ _ ストレージプール _ ）を作成、表示、管理できます。ストレージプールはルート以外のアグリゲートに関連付けて SSD キャッシュを提供したり、 Flash Pool アグリゲートに関連付けてサイズを拡張したりできます。

このページは、オールフラッシュで最適化されたノードを含むクラスタでは使用できません。



== コマンドボタン

* * 作成 * 。
+
ストレージプールの作成ダイアログボックスを開きます。このダイアログボックスで、ストレージプールを作成できます。

* * ディスクの追加 *
+
Add Disks （ディスクの追加）ダイアログボックスを開きます。このダイアログボックスでは、ストレージプールにキャッシュディスクを追加できます。

* * 削除 *
+
選択したストレージプールを削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== ストレージプールのリスト

* * 名前 *
+
ストレージプールの名前が表示されます。

* * 合計キャッシュ *
+
ストレージプールの合計キャッシュサイズが表示されます。

* * スペアキャッシュ *
+
ストレージプールの利用可能なスペアキャッシュサイズが表示されます。

* * 使用キャッシュ（ % ） *
+
ストレージプールの使用済みキャッシュサイズの割合が表示されます。

* * 割り当て単位 *
+
ストレージプールのサイズ拡張に使用できる合計キャッシュサイズの最小割り当て単位が表示されます。

* * 所有者 *
+
ストレージプールが関連付けられている HA ペアまたはノードの名前が表示されます。

* * 状態 *
+
ストレージプールの状態が表示されます。正常、デグレード、作成、削除、再割り当て、 成長する。

* * は正常です *
+
ストレージプールが正常であるかどうかが表示されます。





== [ 詳細 ] タブ

選択したストレージプールに関する詳細情報が表示されます。これには、名前、健常性、ストレージタイプ、ディスク数、合計キャッシュ、 スペアキャッシュ、使用済みキャッシュサイズ（割合）、および割り当て単位。このタブには、ストレージプールによってプロビジョニングされるアグリゲートの名前も表示されます。



== Disks （ディスク）タブ

選択したストレージプール内のディスクに関する詳細情報が表示されます。これには、名前、ディスクタイプ、使用可能なサイズ、合計サイズなどの情報が含まれます。

* 関連情報 *

xref:task_adding_disks_to_storage_pool.adoc[ストレージプールにディスクを追加しています]

xref:task_creating_storage_pool.adoc[ストレージプールを作成します]

xref:task_deleting_storage_pools.adoc[ストレージプールを削除する]
