---
permalink: online-help-96-97/reference_svm_relationships_window.html 
sidebar: sidebar 
keywords: svm, relationship, window, command, button, online, help, mirror 
summary: SVM 関係ウィンドウを使用して、ミラー関係や、 SVM 間のミラーとバックアップ関係を作成および管理できます。 
---
= SVM Relationships ウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM 関係ウィンドウを使用して、ミラー関係や、 SVM 間のミラーとバックアップ関係を作成および管理できます。



== コマンドボタン

* * 作成 * 。
+
SVM のディザスタリカバリページを開きます。このページで、ミラー関係を作成したり、デスティネーションボリュームからミラーとバックアップ関係を作成したりできます。

* * 編集 * 。
+
関係のスケジュールとポリシーを編集できます。

+
ミラーとバックアップ関係またはバージョンに依存しないミラー関係については、ポリシーのタイプを変更することで関係のタイプを変更できます。

* * 削除 *
+
関係を削除できます。

* * 操作 *
+
次のオプションが用意されています。

+
** * 初期化 *
+
SVM 関係を初期化して、ソース SVM からデスティネーション SVM へのベースライン転送を実行できます。

** * アップデート *
+
ソース SVM からデスティネーション SVM にデータを更新できます。

** * デスティネーション SVM をアクティブ化 *
+
デスティネーション SVM をアクティブ化できます。

** * ソース SVM から再同期 *
+
解除した関係の再同期を開始できます。

** * デスティネーション SVM から再同期（逆再同期） *
+
デスティネーション SVM からソース SVM に関係を再同期できます。

** * ソース SVM を再アクティブ化 *
+
ソース SVM を再アクティブ化できます。



* * 更新 *
+
ウィンドウ内の情報を更新します。





== SVM 関係のリスト

* * ソース Storage Virtual Machine *
+
関係におけるデータのミラー元でありバックアップ元であるボリュームを含む SVM が表示されます。

* * デスティネーション Storage Virtual Machine *
+
関係におけるデータのミラー先でありバックアップ先であるボリュームを含む SVM が表示されます。

* * は正常です *
+
関係が正常であるかどうかが表示されます。

* * 関係の状態 *
+
Snapmirrored 、 Uninitialized 、 Broken Off など、関係の状態が表示されます。

* * 転送ステータス *
+
関係のステータスが表示されます。

* * 関係タイプ *
+
ミラー、ミラーとバックアップなど、関係のタイプが表示されます。

* * 遅延時間 *
+
遅延時間は、現在の時刻と、デスティネーションシステムに正常に転送された最後の Snapshot コピーのタイムスタンプとの差です。ソースシステムとデスティネーションシステムのクロックが同期されていないかぎり、遅延時間は常に、最後に成功した転送の時間以上になります。遅延時間の計算ではタイムゾーンの時差が自動的に含められます。

* * ポリシー名 *
+
関係に割り当てられているポリシーの名前が表示されます。

* * ポリシータイプ *
+
関係に割り当てられているポリシーのタイプが表示されます。ポリシーのタイプは、 StrictSync 、 Sync 、非同期ミラー、非同期バックアップ、非同期ミラーバックアップのいずれかです。





== 詳細領域

* * 詳細タブ *
+
選択した関係に関する、ソースクラスタとデスティネーションクラスタ、 SVM に関連付けられている保護関係、データ転送率、関係の状態、ネットワーク圧縮率、データ転送の状態、現在のデータ転送の種類、前回のデータ転送の種類などの一般的な情報が表示されます。 最新の Snapshot コピー、最新の Snapshot コピーのタイムスタンプ、 ID 保持のステータス、保護されているボリュームの数。

* * ［ 保険契約の詳細 ］ タブ *
+
選択した保護関係に割り当てられているポリシーに関する詳細が表示されます。


