---
permalink: online-help-96-97/reference_name_mapping_window.html 
sidebar: sidebar 
keywords: name, map, window, command, button, online, help, group 
summary: ネームマッピングウィンドウを使用して、ネームマッピングエントリを指定し、異なるプラットフォームのユーザをマッピングできます。 
---
= ネームマッピングウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
ネームマッピングウィンドウを使用して、ネームマッピングエントリを指定し、異なるプラットフォームのユーザをマッピングできます。



== ネームマッピング

ネームマッピングを作成して使用することにより、 UNIX ユーザから Windows ユーザ、 Windows ユーザから UNIX ユーザ、 Kerberos ユーザから UNIX ユーザへのマッピングが可能です。



== コマンドボタン

* * 追加 * 。
+
ネームマッピングエントリの追加ダイアログボックスを開きます。このダイアログボックスで、 Storage Virtual Machine （ SVM ）上にネームマッピングを作成できます。

* * 編集 * 。
+
ネームマッピングエントリの編集ダイアログボックスを開きます。このダイアログボックスで、 SVM のネームマッピングを編集できます。

* * 削除 *
+
ネームマッピングエントリの削除ダイアログボックスを開きます。このダイアログボックスで、ネームマッピングエントリを削除できます。

* * スワップ *
+
ネームマッピングエントリのスワップ（ Swap Name Mapping Entries ）ダイアログボックスを開きます。このダイアログボックスでは、選択した 2 つのネームマッピングエントリの位置を切り替えることができます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== ネームマッピングのリスト

* * 位置 *
+
優先順位リスト内でのネームマッピングの位置を示します。ネームマッピングは、優先順位リストの順序に従って適用されます。

* * パターン *
+
照合するユーザ名のパターンを示します。

* * 交換 *
+
変換後のユーザ名のパターンを示します。

* * 方向 *
+
ネームマッピングの方向を示します。Kerberos から UNIX へのネームマッピングの場合は krb_unix 、 Windows から UNIX へのネームマッピングの場合は win_unix 、 UNIX から Windows へのネームマッピングの場合は unix_win になります。





== コマンドボタン

* * 追加 * 。
+
Add Group Mapping Entry ダイアログボックスを開きます。このダイアログボックスで、 SVM に対するグループマッピングを作成できます。

* * 編集 * 。
+
Edit Group Mapping Entry ダイアログボックスを開きます。このダイアログボックスで、 SVM のグループマッピングを編集できます。

* * 削除 *
+
Delete Group Mapping Entries ダイアログボックスを開きます。このダイアログボックスで、グループマッピングエントリを削除できます。

* * スワップ *
+
Swap Group Mapping Entries ダイアログボックスを開きます。このダイアログボックスで、選択した 2 つのグループマッピングエントリの位置を切り替えることができます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== グループマッピングのリスト

* * 位置 *
+
優先順位リスト内でのグループマッピングの位置を示します。グループマッピングは、優先順位リストの順序に従って適用されます。

* * パターン *
+
照合するユーザ名のパターンを示します。

* * 交換 *
+
変換後のユーザ名のパターンを示します。

* * 方向 *
+
グループマッピングの方向を示します。Kerberos から UNIX へのグループマッピングの場合は「 krb_unix 」、 Windows から UNIX へのグループマッピングの場合は「 win_unix 」、 UNIX から Windows へのグループマッピングの場合は「 unix_win 」です。


