---
permalink: online-help-96-97/reference_service_processors_window.html 
sidebar: sidebar 
keywords: command, button, service, processor, window, ipv4, online, help, ipv6, ip, address 
summary: サービスプロセッサウィンドウを使用して、 IP アドレス、ネットワークマスク（ IPv4 ）、プレフィックス長（ IPv6 ）、ゲートウェイなどのサービスプロセッサ属性を表示および変更したり、サービスプロセッサの IP ソースを設定したりできます。 
---
= サービスプロセッサウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
サービスプロセッサウィンドウを使用して、 IP アドレス、ネットワークマスク（ IPv4 ）、プレフィックス長（ IPv6 ）、ゲートウェイなどのサービスプロセッサ属性を表示および変更したり、サービスプロセッサの IP ソースを設定したりできます。



== コマンドボタン

* * 編集 * 。
+
サービスプロセッサの編集ダイアログボックスを開きます。このダイアログボックスで、サービスプロセッサの IP アドレス、ネットワークマスク（ IPv4 ）またはプレフィックス長（ IPv6 ）、およびゲートウェイの情報を変更できます。

* * グローバル設定 *
+
Global Settings ダイアログボックスを開きます。このダイアログボックスでは、すべてのサービスプロセッサの IP アドレスのソースを、 DHCP 、サブネット、または手動のいずれかとして設定できます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== サービスプロセッサのリスト

* * ノード *
+
サービスプロセッサが配置されているノードを指定します。

* * IP アドレス *
+
サービスプロセッサの IP アドレスを指定します。

* * ステータス *
+
サービスプロセッサのステータスを示します。オンライン、オフライン、デーモンオフライン、ノードオフライン、デグレード、 リブートされたか、不明です。

* * MAC アドレス *
+
サービスプロセッサの MAC アドレスを指定します。





== 詳細領域

サービスプロセッサリストの下の領域には、 IP アドレス、ネットワークマスク（ IPv4 ）、プレフィックス長（ IPv6 ）、ゲートウェイ、 IP ソース、 MAC アドレス、ファームウェアバージョン、ファームウェアの自動更新が有効かどうかなどの一般的な詳細情報。

* 関連情報 *

xref:task_setting_up_network_when_ip_address_range_is_disabled.adoc[IP アドレス範囲を無効にした状態でのネットワークの設定]
