---
permalink: online-help-96-97/reference_qtrees_window.html 
sidebar: sidebar 
keywords: qtree, online, help, window, command, button 
summary: Qtrees window では、 qtree に関する情報を作成、表示、および管理できます。 
---
= Qtrees window
:icons: font
:imagesdir: ../media/


[role="lead"]
Qtrees window では、 qtree に関する情報を作成、表示、および管理できます。



== コマンドボタン

* * 作成 * 。
+
qtree の作成ダイアログボックスを開きます。このダイアログボックスで、新しい qtree を作成できます。

* * 編集 * 。
+
qtree の編集ダイアログボックスを開きます。このダイアログボックスで、セキュリティ形式を変更したり、 qtree 上の oplock （便宜的ロック）を有効または無効にしたりできます。

* * エクスポートポリシーの変更 *
+
エクスポートポリシーダイアログボックスを開きます。このダイアログボックスで、新規または既存のエクスポートポリシーに 1 つ以上の qtree を割り当てることができます。

* * 削除 *
+
選択した qtree を削除します。

+
このボタンは、選択した qtree のステータスが正常な場合にのみ有効になります。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== qtree のリスト

qtree のリストには、 qtree が属するボリュームと qtree の名前が表示されます。

* * 名前 *
+
qtree の名前が表示されます。

* * 音量 *
+
qtree が属するボリュームの名前が表示されます。

* * セキュリティ形式 *
+
qtree のセキュリティ形式を示します。

* * ステータス *
+
qtree の現在のステータスを示します。

* * oplocks *
+
qtree に対して oplock の設定が有効になっているか無効になっているかを示します。

* * エクスポートポリシー *
+
qtree が割り当てられているエクスポートポリシーの名前が表示されます。





== 詳細領域

* * 詳細タブ *
+
選択した qtree に関する詳細情報が表示されます。これには、 qtree が含まれているボリュームのマウントパス、エクスポートポリシーの詳細、エクスポートポリシールールなどの情報が含まれます。



* 関連情報 *

xref:task_creating_qtrees.adoc[qtree の作成]

xref:task_deleting_qtrees.adoc[qtree を削除します]

xref:task_editing_qtrees.adoc[qtree を編集中です]
