---
permalink: online-help-96-97/reference_quotas_window.html 
sidebar: sidebar 
keywords: quota, window, create, display, manage, information, online, help 
summary: クォータウィンドウを使用して、クォータに関する情報を作成、表示、および管理できます。 
---
= クォータウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
クォータウィンドウを使用して、クォータに関する情報を作成、表示、および管理できます。



== タブ

* * ユーザー定義クォータ *
+
ユーザー定義クォータ * タブを使用して、作成したクォータの詳細を表示したり、クォータを作成、編集、または削除することができます。

* * クォータレポート *
+
クォータレポートタブを使用して、スペースとファイルの使用状況を表示したり、アクティブなクォータのスペースとファイルの制限を編集したりできます。

* * ボリュームのクォータステータス *
+
ボリュームのクォータステータスタブを使用して、クォータのステータスを表示したり、クォータのオン / オフを切り替えたり、クォータのサイズを変更したりできます。





== コマンドボタン

* * 作成 * 。
+
クォータの作成ウィザードを開きます。このウィザードで、クォータを作成できます。

* * 制限の編集 *
+
制限の編集ダイアログボックスを開きます。このダイアログボックスで、選択したクォータの設定を編集できます。

* * 削除 *
+
選択したクォータをクォータのリストから削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== ユーザ定義のクォータのリスト

クォータのリストには、各クォータの名前とストレージの情報が表示されます。

* * 音量 *
+
クォータが適用されるボリュームを示します。

* * qtree *
+
クォータに関連付けられている qtree を示します。「すべての qtree 」は、クォータがすべての qtree に関連付けられていることを示します。

* * タイプ *
+
クォータのタイプがユーザ、グループ、またはツリーのいずれであるかを示します。

* * ユーザー / グループ *
+
クォータに関連付けられているユーザまたはグループを示します。「 all users 」は、クォータがすべてのユーザに関連付けられていることを示します。「すべてのグループ」は、そのクォータがすべてのグループに関連付けられていることを示します。

* * クォータターゲット *
+
クォータの割り当て先のターゲットのタイプを示します。qtree 、ユーザ、またはグループです。

* * スペースのハードリミット *
+
ハードクォータに適用されるディスクスペース制限を示します。

+
このフィールドはデフォルトでは非表示になっています。

* * スペースソフトリミット *
+
ソフトクォータに適用されるディスクスペース制限を示します。

+
このフィールドはデフォルトでは非表示になっています。

* * しきい値 *
+
しきい値クォータに適用されるディスクスペース制限を示します。

+
このフィールドはデフォルトでは非表示になっています。

* * ファイルハードリミット *
+
ハードクォータの最大ファイル数を示します。

+
このフィールドはデフォルトでは非表示になっています。

* * ファイルソフトリミット *
+
ソフトクォータの最大ファイル数を指定します。

+
このフィールドはデフォルトでは非表示になっています。





== 詳細領域

クォータのリストの下の領域には、クォータの詳細が表示されます。これには、クォータエラー、スペースの使用量と制限、ファイルの使用量と制限などの情報が含まれます。

* 関連情報 *

xref:task_creating_quotas.adoc[クォータの作成]

xref:task_deleting_quotas.adoc[クォータの削除]

xref:task_editing_quota_limits.adoc[クォータ制限を編集しています]

xref:task_activating_or_deactivating_quotas.adoc[クォータをアクティブ化または非アクティブ化する]

xref:task_resizing_quotas.adoc[クォータのサイズ変更]
