---
permalink: online-help-96-97/reference_nvme_namespaces_window.html 
sidebar: sidebar 
keywords: nvme, namespace, command, button, subsystems, protocol, online, help 
summary: 'NVMe の [ 名前空間 ] ウィンドウを使用して、 NVMe プロトコルのネームスペースと関連するサブシステムをセットアップおよび管理できます。既存のネームスペースは、ネームスペースパスを使用して検索できます。' 
---
= NVMe ネームスペースウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMe の [ 名前空間 ] ウィンドウを使用して、 NVMe プロトコルのネームスペースと関連するサブシステムをセットアップおよび管理できます。既存のネームスペースは、ネームスペースパスを使用して検索できます。



== コマンドボタン

* * 作成 * 。
+
NVMe ネームスペースの作成ダイアログボックスを開きます。このダイアログボックスで、新しいネームスペースを設定して NVMe サブシステムにマッピングできます。

* * 編集 * 。
+
ネームスペースのマッピングを編集できます。

* * 削除 *
+
選択したネームスペースを削除します。

* * その他のアクション *
+
選択したネームスペースのクローンを作成し、既存のサブシステムに関連付けることができます。サブシステムにマッピングしないようにすることもできます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== NVMe リスト

* * ステータス *
+
ネームスペースがオンラインかオフラインかが表示されます。

* * 名前空間パス *
+
新しいネームスペースへのパスを「 /vol/ volume 」 / 「 / file 」形式で指定します。ネームスペースパスはクリック可能なリンクです。リンクをクリックすると、ネームスペースの詳細が表示されます。

* * NVMe サブシステム *
+
ネームスペースに関連付けられているサブシステムの名前。サブシステムが接続されていない場合、このカラムの値は「 None 」と表示されます。マッピングされていないネームスペースのリストは、 NVMe サブシステムのこの列を「 None 」でフィルタリングすることで確認できます。

* * SVM *
+
ネームスペースが作成されている SVM の名前。SVM 名はクリック可能なリンクです。リンクをクリックすると、既存の SVM ダッシュボードページが表示されます。

+
ONTAP 9.5 以降では、 SVM に関連付けられた HA ペアの各ノードに対して、少なくとも 1 つの NVMe LIF が設定されている必要があります。ペアの各ノードに対して作成できる NVMe LIF の数は 2 つまでです。

* * 名前空間 ID*
+
コントローラがネームスペースへのアクセスを提供するために使用する一意の識別子。これはユーザが入力するのではなく、新しいネームスペースが作成されるとシステムによって生成されます。

* * 合計容量 *
+
ネームスペースの合計サイズが表示されます。

* * 使用済みスペース *
+
ネームスペース内の使用済みスペースが表示されます。

* * % 使用済み *
+
ネームスペース内で使用されているスペースが表示されます。このフィールドの値は、合計スペースと使用済みスペースから計算されます。





== 詳細領域（ Details Area ）

ネームスペースを選択すると、選択したネームスペースに関する情報が表示されます。ネームスペースを編集、削除、クローニングすることもできます。

* *** 概要 * タブ **
+
選択したネームスペースに関する全般的な情報が表示されます。これには、ネームスペースのスペース割り当てとパフォーマンスが図やグラフで表されます。

+
概要タブでは、 SVM とボリュームの名前をクリック可能なリンクとして使用できます。リンクをクリックすると、 SVM およびボリュームのページが表示されます。ホストの数は 1 つ以上ですが、デフォルトでは 2 つのホスト名が表示されます。表示されるホスト名が 3 つ以上の場合は、リンクをクリックして追加のホストにアクセスできます。

+
概要タブには、ネームスペースの合計スペースと使用済みスペースの詳細、およびレイテンシ、 IOPS 、スループットなどの詳細を表示するパフォーマンスチャートも表示されます。

* * ステータス *
+
ネームスペースのステータス。「オンライン」または「オフライン」のいずれかです。

* * ホスト NQN *
+
ホストの NVMe Qualified Name （ NQN ）は、識別と認証を目的としたホストを一意に表す名前です。複数の NQN 値をカンマで区切って指定できます。ホスト NQN は <nqn.ny-mm> で始まり、残りの検証はイニシエータ修飾名（ IQN ）と同じです。

* * ホスト OS *
+
ネームスペースのホストオペレーティングシステム。 Hyper-V 、 Linux 、 VMware 、 Windows 、 Xen のいずれかです。

* * 音量 *
+
ネームスペースがホストされているボリューム名が表示されます。

* * 読み取り専用 *
+
ネームスペースが読み取り専用かどうかが表示されます。

* * ノード *
+
ネームスペースを所有するノード。

* * ブロックサイズ *
+
ストレージブロックのサイズ。

* * リストアにアクセスできません *
+
サブシステムのマッピング解除が失敗して一部のデータが残った場合、マッピング解除されたネームスペースはリストアできません。


