---
permalink: online-help-96-97/reference_snapshot_policies_window.html 
sidebar: sidebar 
keywords: snapshot, policies, window, command, buttons, online, help 
summary: Snapshot Policies ウィンドウを使用して、 Snapshot ポリシーの追加、編集、削除など、 Snapshot ポリシータスクを管理できます。 
---
= Snapshot ポリシーウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshot Policies ウィンドウを使用して、 Snapshot ポリシーの追加、編集、削除など、 Snapshot ポリシータスクを管理できます。



== コマンドボタン

* * 作成 * 。
+
Create Snapshot Policy ダイアログボックスを開きます。このダイアログボックスでは、バックアップスケジュールを追加したり、ポリシーで保持する Snapshot コピーの最大数を指定したりできます。

* * 編集 * 。
+
Edit Snapshot Policy ダイアログボックスを開きます。このダイアログボックスで、 Snapshot コピーを作成する頻度と保持する Snapshot コピーの最大数を変更できます。

* * 削除 *
+
削除ダイアログボックスを開きます。このダイアログボックスで、選択した Snapshot ポリシーを削除できます。

* * として表示
+
Snapshot ポリシーをリストまたはツリーとして表示できます。

* * ステータス *
+
選択した Snapshot ポリシーを有効または無効にするために使用できるメニューを開きます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== Snapshot ポリシーリスト

* * ポリシー / スケジュール名 *
+
Snapshot ポリシーとポリシー内のスケジュールの名前を示します。

* * Storage Virtual Machine *
+
Snapshot コピーが属する Storage Virtual Machine （ SVM ）の名前を示します。

* * ステータス *
+
Snapshot ポリシーのステータスを示します。有効または無効にできます。

* * 保持するスナップショットの最大数 *
+
保持する Snapshot コピーの最大数を指定します。

* * SnapMirror ラベル *
+
バックアップスケジュールで生成される Snapshot コピーの SnapMirror ラベル属性の名前を示します。


