---
permalink: online-help-96-97/reference_qos_policy_groups_window.html 
sidebar: sidebar 
keywords: quality, service, qos, policy, groups, window, online, help 
summary: ストレージ QoS （サービス品質）は、パフォーマンス目標の達成に伴うリスクへの対応に役立ちます。ストレージ QoS を使用すると、ワークロードのスループットを制限したり、ワークロードのパフォーマンスを監視したりできます。QoS ポリシーグループウィンドウを使用して、ポリシーグループを管理したりそれらの情報を表示したりできます。 
---
= QoS ポリシーグループウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ QoS （サービス品質）は、パフォーマンス目標の達成に伴うリスクへの対応に役立ちます。ストレージ QoS を使用すると、ワークロードのスループットを制限したり、ワークロードのパフォーマンスを監視したりできます。QoS ポリシーグループウィンドウを使用して、ポリシーグループを管理したりそれらの情報を表示したりできます。



== コマンドボタン

* * 作成 * 。
+
Create QoS Policy Group ダイアログボックスを開きます。このダイアログボックスで、新しいポリシーグループを作成できます。

* * 編集 * 。
+
[Edit QoS Policy Group] ダイアログボックスが開き、選択したポリシーグループを変更できます。

* * 削除 *
+
選択したポリシーグループを削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== QoS ポリシーグループのリスト

QoS ポリシーグループのリストには、各ポリシーグループの名前と最大スループットが表示されます。

* * 名前 *
+
QoS ポリシーグループの名前が表示されます。

* * 最小スループット *
+
ポリシーグループに対して指定されている最小スループット制限が表示されます。

+
最小スループット値を指定していない場合は、値として自動的に「 None 」が表示され、この値では大文字と小文字が区別されます。

* * 最大スループット *
+
ポリシーグループに対して指定されている最大スループット制限が表示されます。

+
最大スループット値を指定しなかった場合は、値として自動的に「無制限」と表示され、大文字と小文字が区別されます。

* * ストレージオブジェクト数 *
+
ポリシーグループに割り当てられているストレージオブジェクトの数が表示されます。





== 詳細領域

QoS ポリシーグループのリストの下の領域には、選択したポリシーグループに関する詳細情報が表示されます。

* * ［ 割り当て済みストレージオブジェクト ］ タブ *
+
選択したポリシーグループに割り当てられているストレージオブジェクトの名前とタイプが表示されます。


