---
permalink: online-help-96-97/reference_ldap_client_window_svm.html 
sidebar: sidebar 
keywords: ldap, client, window, command, button, online, help, nfs, cifs, list 
summary: LDAP クライアントウィンドウを使用すると、 Storage Virtual Machine （ SVM ）レベルで、 NFS と CIFS 間のユーザ認証、ファイルアクセス認証、ユーザ検索、およびマッピングサービス用の LDAP クライアントを作成できます。 
---
= LDAP クライアントウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
LDAP クライアントウィンドウを使用すると、 Storage Virtual Machine （ SVM ）レベルで、 NFS と CIFS 間のユーザ認証、ファイルアクセス認証、ユーザ検索、およびマッピングサービス用の LDAP クライアントを作成できます。



== コマンドボタン

* * 追加 * 。
+
LDAP クライアントの作成および設定を行うための Create LDAP Client ダイアログボックスを開きます。

* * 編集 * 。
+
LDAP クライアント設定を編集できる Edit LDAP Client ダイアログボックスを開きます。アクティブな LDAP クライアントを編集することもできます。

* * 削除 *
+
LDAP クライアント設定を削除するための Delete LDAP Client （複数可）ダイアログボックスを開きます。アクティブな LDAP クライアントを削除することもできます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== LDAP クライアントリスト

LDAP クライアントの詳細を表形式で表示します。

* * LDAP クライアント構成 *
+
指定した LDAP クライアント設定の名前を表示します。

* * Storage Virtual Machine *
+
LDAP クライアント設定ごとに SVM の名前を表示します。

* * スキーマ *
+
LDAP クライアントごとにスキーマを表示します。

* * 最小バインドレベル *
+
LDAP クライアントごとに最小バインドレベルを表示します。

* * Active Directory ドメイン *
+
LDAP クライアント設定ごとに Active Directory ドメインを表示します。

* * LDAP サーバ *
+
LDAP クライアント設定ごとに LDAP サーバを表示します。

* * 優先される Active Directory サーバ *
+
LDAP クライアント設定ごとに優先される Active Directory サーバを表示します。


