---
permalink: online-help-96-97/reference_shares_window.html 
sidebar: sidebar 
keywords: command, buttons, shares, window, online, help 
summary: 共有の管理や共有に関する情報の表示には、共有ウィンドウを使用できます。 
---
= 共有ウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
共有の管理や共有に関する情報の表示には、共有ウィンドウを使用できます。



== コマンドボタン

* * 共有の作成 *
+
共有を作成できる [ 共有の作成 ] ダイアログボックスを開きます。

* * ホームディレクトリを作成 *
+
Create Home Directory Share ダイアログボックスを開きます。このダイアログボックスで、新しいホームディレクトリ共有を作成できます。

* * 編集 * 。
+
設定の編集ダイアログボックスを開きます。このダイアログボックスで、選択した共有のプロパティを変更できます。

* * 共有を停止 *
+
選択したオブジェクトが共有されないようにします。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== 共有リスト

共有リストには、各共有の名前とパスが表示されます。

* * 共有名 *
+
共有の名前が表示されます。

* * パス *
+
共有されている既存のフォルダ、 qtree 、またはボリュームの完全なパス名が表示されます。パスの区切り文字には、スラッシュまたはバックスラッシュを使用できますが、 ONTAP では、いずれの区切り文字もスラッシュとして表示されます。

* * ホームディレクトリ *
+
ホームディレクトリ共有の名前が表示されます。

* * コメント *
+
共有の追加の説明がある場合に表示されます。

* * 共有の継続的な可用性 *
+
共有が継続的可用性に対して有効になっているかどうかが表示されます。System Manager 9.6 以降では、 FlexGroup ボリュームに対して継続的可用性がサポートされます。





== 詳細領域

共有リストの下の領域には、共有プロパティと各共有のアクセス権が表示されます。

* * プロパティ *
+
** 名前
+
共有の名前が表示されます。

** oplock ステータス
+
共有で便宜的ロック（ oplock ）を使用するかどうかを示します。

** 参照可能
+
Windows クライアントから共有を参照できるかどうかを示します。

** Snapshot を表示します
+
クライアントで Snapshot コピーを表示できるかどうかを示します。

** 共有の継続的な可用性
+
共有が継続的に利用できるように有効になっているか無効になっているかを示します。System Manager 9.6 以降では、 FlexGroup ボリュームに対して継続的可用性がサポートされます。

** ABE ：アクセスベースの列挙
+
共有で Access-Based Enumeration が有効になっているかどうかを示します。

** BranchCache
+
共有で BranchCache が有効になっているかどうかを示します。

** SMB 暗号化
+
SMB 3.0 を使用したデータ暗号化が Storage Virtual Machine （ SVM ）レベルまたは共有レベルで有効になっているかどうかを示します。SMB 暗号化が SVM レベルで有効になっている場合は、すべての共有に SMB 暗号化が適用され、（ SVM レベルで）「有効」という値が表示されます。

** 以前のバージョン
+
クライアントで以前のバージョンを表示してリストアできるかどうかを指定します。



* * 共有アクセス制御 *
+
共有のドメインユーザ、ドメイングループ、ローカルユーザ、およびローカルグループのアクセス権が表示されます。



* 関連情報 *

xref:task_creating_cifs_share.adoc[CIFS 共有を作成する]

xref:task_stopping_share_access.adoc[共有アクセスを停止しています]

xref:task_editing_share_settings.adoc[共有設定を編集しています]
