---
permalink: online-help-96-97/reference_how_flash_cache_modules_work.html 
sidebar: sidebar 
keywords: flash, cache, module, storage, system, online, free, hardware 
summary: Flash Cache モジュールを使用すると、ストレージシステムのパフォーマンスが向上します。Flash Cache モジュールの使用による影響は、 Hardware Cache ウィンドウに表示されます。 
---
= Flash Cache モジュールの仕組み
:icons: font
:imagesdir: ../media/


[role="lead"]
Flash Cache モジュールを使用すると、ストレージシステムのパフォーマンスが向上します。Flash Cache モジュールの使用による影響は、 Hardware Cache ウィンドウに表示されます。

Flash Cache モジュールとディスクは、ストレージシステムのワークロード要件に基づいて設定することができます。Flash Cache モジュールとディスクで処理する読み取りワークロード（読み取り操作の数）を特定することで、ストレージシステムのパフォーマンスを分析できます。

ストレージシステムのブート時や、テイクオーバー後にストレージシステムに制御が戻った時点では、 Flash Cache モジュールにはデータが格納されていません。そのため、ストレージシステムのその時点のデータ読み取り要求はすべてディスクで処理されます。

Flash Cache モジュールには、データ読み取り要求が処理されるに従って少しずつデータが取り込まれます。データ読み取り要求の処理は、 Flash Cache モジュールの方がディスクよりも高速であるため、 Flash Cache モジュールを利用するとストレージシステムのパフォーマンスが向上します。

Flash Cache モジュールで処理されるデータ読み取り要求は、ディスクで処理されるデータ読み取り要求に代わるものであるため、ストレージシステムのパフォーマンスがどの程度向上するかは、代わりに処理されるディスク読み取りによって決まります。ストレージシステムのパフォーマンスに対する Flash Cache モジュールの影響を判断するには、 Flash Cache モジュールにデータが含まれている場合に、 Hardware Cache ウィンドウに読み取りワークロードのグラフを表示する必要があります。
