---
permalink: online-help-96-97/reference_cluster_peers_window.html 
sidebar: sidebar 
keywords: cluster, peer, window, command, button, online, help 
summary: クラスタピアウィンドウを使用してピアクラスタ関係を管理し、クラスタ間でデータを移動できます。 
---
= クラスタピアウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタピアウィンドウを使用してピアクラスタ関係を管理し、クラスタ間でデータを移動できます。



== コマンドボタン

* * 作成 * 。
+
クラスタピアリングの作成ダイアログボックスを開きます。このダイアログボックスで、リモートクラスタとの関係を作成できます。

* * 編集 * 。
+
ドロップダウンメニューに次のオプションが表示されます。

+
** * ローカルクラスタのパスフレーズ *
+
Edit Local Cluster Passphrase （ローカルクラスタのパスフレーズの編集）ダイアログボックスを開きます。このダイアログボックスで、ローカルクラスタを検証する新しいパスフレーズを入力できます。

** * ピアクラスタのネットワークパラメータ *
+
Edit Peer Cluster Network Parameters ダイアログボックスを開きます。このダイアログボックスで、 IPspace を変更したり、クラスタ間 LIF の IP アドレスを追加または削除したりできます。

+
複数の IP アドレスを追加する場合は、カンマで区切ります。

** * 暗号化の変更 *
+
選択したピアクラスタの Change Encryption ダイアログボックスを開きます。ピア関係の暗号化を変更した場合、新しいパスフレーズを生成してピアクラスタで指定するか、ピアクラスタで生成済みの既存のパスフレーズを指定することができます。

+
暗号化ステータスが「 N/A 」の場合、このアクションは使用できません。



* * 削除 *
+
クラスタピア関係の削除ダイアログボックスを開きます。このダイアログボックスで、選択したピアクラスタ関係を削除できます。

* * 更新 *
+
ウィンドウ内の情報を更新します。

* * SVM の権限の管理 *
+
SVM で SVM ピア要求を自動的に承認できます。

* * ピアリングパスフレーズの生成 *
+
IPspace 、パスフレーズの有効期限、および権限を付与する SVM を指定して、ローカルクラスタの IPspace のパスフレーズを生成できます。

+
リモートクラスタでも同じピアリングパスフレーズを使用します。





== ピアクラスタリスト

* * ピアクラスタ *
+
関係内のピアクラスタの名前を示します。

* * 利用可能性 *
+
ピアクラスタを通信に使用できるかどうかを示します。

* * 認証ステータス *
+
ピアクラスタが認証済みかどうかを示します。

* * ローカルクラスタ IPspace *
+
ローカルクラスタピア関係に関連付けられている IPspace が表示されます。

* * ピアクラスタのクラスタ間 IP アドレス *
+
クラスタ間ピア関係に関連付けられている IP アドレスが表示されます。

* * 最終更新日時 *
+
ピアクラスタが最後に変更された日時が表示されます。

* * 暗号化 *
+
ピア関係の暗号化ステータスが表示されます。

+
[NOTE]
====
System Manager 9.6 以降では、 2 つのクラスタ間にピア関係を確立する際、デフォルトでピア関係が暗号化されます

====
+
** * N/A * ：暗号化は関係に適用されません。
** * none * ：ピア関係は暗号化されません。
** * tls_psk * ：ピア関係は暗号化されています。



