---
permalink: online-help-96-97/reference_namespace.html 
sidebar: sidebar 
keywords: junction, path, window, command, buttons, online, help, list 
summary: Junction Path メニューを使用して、 Storage Virtual Machine （ SVM ）の NAS ネームスペースを管理できます。 
---
= ジャンクションパスウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
Junction Path メニューを使用して、 Storage Virtual Machine （ SVM ）の NAS ネームスペースを管理できます。



== コマンドボタン

* * マウント *
+
ボリュームのマウントダイアログボックスを開きます。このダイアログボックスで、 SVM ネームスペースのジャンクションにボリュームをマウントできます。

* * Unmount *
+
ボリュームのアンマウントダイアログボックスを開きます。このダイアログボックスで、ボリュームを親ボリュームからアンマウントできます。

* * エクスポートポリシーの変更 *
+
エクスポートポリシーの変更ダイアログボックスを開きます。このダイアログボックスで、ボリュームに関連付けられている既存のエクスポートポリシーを変更できます。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== ジャンクションパスのリスト

* * パス *
+
マウントされたボリュームのジャンクションパスを指定します。ジャンクションパスをクリックすると、関連するボリュームと qtree を表示できます。

* * ストレージオブジェクト *
+
ジャンクションパスにマウントされたボリュームの名前を指定します。ボリュームに含まれる qtree を表示することもできます。

* * エクスポートポリシー *
+
マウントされたボリュームのエクスポートポリシーを指定します。

* * セキュリティ形式 *
+
ボリュームのセキュリティ形式を指定します。指定できる値は、 UNIX （ UNIX モードビット）、 NTFS （ CIFS ACL ）、 Mixed （ NFS 権限と CIFS 権限の混合）です。





== [ 詳細 ] タブ

選択したボリュームまたは qtree に関する、名前、ストレージオブジェクトのタイプ、マウントオブジェクトのジャンクションパス、エクスポートポリシーなどの基本的な情報が表示されます。選択したオブジェクトが qtree の場合、スペースのハードリミット、ソフトリミット、および使用状況が表示されます。
