---
permalink: online-help-96-97/reference_iscsi_window.html 
sidebar: sidebar 
keywords: iscsi, window, tab, command, button, storage, system, initiator, online, help 
summary: iSCSI ウィンドウでは、 iSCSI サービスの開始または停止、ストレージシステムの iSCSI ノード名の変更、ストレージシステムの iSCSI エイリアスの作成または変更を行うことができます。また、ストレージシステムに接続されている iSCSI イニシエータのイニシエータセキュリティ設定の追加や変更も可能です。 
---
= iSCSI ウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI ウィンドウでは、 iSCSI サービスの開始または停止、ストレージシステムの iSCSI ノード名の変更、ストレージシステムの iSCSI エイリアスの作成または変更を行うことができます。また、ストレージシステムに接続されている iSCSI イニシエータのイニシエータセキュリティ設定の追加や変更も可能です。



== タブ

* * サービス *
+
サービス * タブを使用して、 iSCSI サービスの開始または停止、ストレージ・システムの iSCSI ノード名の変更、ストレージ・システムの iSCSI エイリアスの作成または変更を行うことができます。

* * イニシエータセキュリティ *
+
[ * イニシエータ・セキュリティ * ] タブを使用して、ストレージ・システムに接続されている iSCSI イニシエータのイニシエータ・セキュリティ設定を追加または変更できます。





== コマンドボタン

* * 編集 * 。
+
Edit iSCSI Service Configurations （ iSCSI サービス設定の編集）ダイアログボックスが開きます。このダイアログボックスで、ストレージシステムの iSCSI ノード名と iSCSI エイリアスを変更できます。

* * 開始 *
+
iSCSI サービスを開始します。

* * 停止 *
+
iSCSI サービスを停止します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== 詳細領域

詳細領域には、 iSCSI サービスのステータス、 iSCSI ターゲットノード名、および iSCSI ターゲットエイリアスに関する情報が表示されます。この領域で、ネットワークインターフェイスに対して iSCSI サービスを有効または無効にできます。

* 関連情報 *

xref:task_creating_iscsi_aliases.adoc[iSCSI エイリアスを作成しています]

xref:task_enabling_or_disabling_iscsi_service_on_storage_system_interfaces.adoc[ストレージシステムインターフェイスでの iSCSI サービスの有効化と無効化]

xref:task_adding_security_method_for_iscsi_initiators.adoc[iSCSI イニシエータに対するセキュリティ方式の追加]

xref:task_editing_default_security_settings.adoc[デフォルトセキュリティ設定の編集]

xref:task_editing_initiator_security.adoc[イニシエータセキュリティを編集中です]

xref:task_changing_default_initiator_authentication_method.adoc[iSCSI イニシエータのデフォルトの認証方法を変更する]

xref:task_setting_default_security_for_initiators.adoc[iSCSI イニシエータにデフォルトセキュリティを設定します]

xref:task_starting_or_stopping_iscsi_service.adoc[iSCSI サービスを開始または停止しています]
