---
permalink: online-help-96-97/reference_nvme_subsystems_window.html 
sidebar: sidebar 
keywords: nvme, subsystems, window, table, toolbar, online, help, cluster 
summary: NVMe サブシステムウィンドウには、クラスタ内の NVMe サブシステムのインベントリリストがデフォルトで表示されます。リストをフィルタして、ある SVM に固有のサブシステムのみを表示することができます。また、 NVMe サブシステムを作成、編集、削除することもできます。このウィンドウにアクセスするには、 Storage NVMe サブシステムを選択します。 
---
= NVMe サフシステムウイントウ
:icons: font
:imagesdir: ../media/


[role="lead"]
NVMe サブシステムウィンドウには、クラスタ内の NVMe サブシステムのインベントリリストがデフォルトで表示されます。リストをフィルタして、ある SVM に固有のサブシステムのみを表示することができます。また、 NVMe サブシステムを作成、編集、削除することもできます。このウィンドウにアクセスするには、 * Storage * > * NVMe * > * subsystems * を選択します。

* <<GUID-1E417C67-1F31-4FA5-AAA7-2D5BB298C6AB,NVMe サブシステムテーブル>>
* <<SECTION_819274C0AB2341B0915167A78A41F1D8,ツールバー>>




== NVMe サブシステムテーブル

NVMe サブシステムテーブルには、クラスタ内の NVMe サブシステムのインベントリが表示されます。このリストを絞り込むには、「 * SVM * 」フィールドのドロップダウンメニューを使用して、その SVM に関連付けられている NVMe サブシステムのみを表示する SVM を選択します。[*Search] フィールドと [*Filtering*] ドロップダウンメニューを使用して、リストをさらにカスタマイズできます。

NVMe サブシステムテーブルには次の列があります。

* * （チェックボックス） *
+
処理を実行するサブシステムを指定できます。

+
チェックボックスをクリックしてサブシステムを選択し、実行する処理をツールバーでクリックします。

* * 名前 *
+
サブシステムの名前が表示されます。

+
検索 * フィールドにサブシステム名を入力すると、そのサブシステムを検索できます。

* * ホスト OS *
+
サブシステムに関連付けられているホスト OS の名前が表示されます。

* * ホスト NQN *
+
コントローラに接続された NQN が表示されます。NQN が複数ある場合はカンマで区切って表示されます。

* * 関連付けられている NVMe ネームスペース *
+
サブシステムに関連付けられている NVM ネームスペースの数が表示されます。数字にカーソルを合わせると、関連付けられているネームスペースのパスが表示されます。パスをクリックすると、 [ 名前空間の詳細 ] ウィンドウが表示されます。





== ツールバー

ツールバーは列ヘッダーの上にあります。ツールバーのフィールドとボタンを使用して、さまざまな操作を実行できます。

* * 検索 *
+
[ * 名前 * ] 列にある値を検索できます。

* * フィルタリング *
+
リストをフィルタするさまざまな方法をドロップダウンメニューから選択できます。

* * 作成 * 。
+
NVMe サブシステムの作成ダイアログボックスを開きます。このダイアログボックスで、 NVMe サブシステムを作成できます。

* * 編集 * 。
+
NVMe サブシステムの編集ダイアログボックスを開きます。このダイアログボックスで、既存の NVMe サブシステムを編集できます。

* * 削除 *
+
NVMe サブシステムの削除の確認ダイアログボックスを開きます。このダイアログボックスで、既存の NVMe サブシステムを削除できます。


