---
permalink: online-help-96-97/reference_efficiency_policies.html 
sidebar: sidebar 
keywords: efficiency, policies, window, command, buttons, online, help 
summary: 効率化ポリシーウィンドウを使用して、効率化ポリシーに関する情報を作成、表示、管理できます。 
---
= [ 効率化ポリシー ] ウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
効率化ポリシーウィンドウを使用して、効率化ポリシーに関する情報を作成、表示、管理できます。



== コマンドボタン

* * 追加 * 。
+
効率化ポリシーの追加ダイアログボックスを開きます。このダイアログボックスで、指定した期間（スケジュールベース）、またはボリュームデータの変更率が指定したしきい値（しきい値ベース）に達したときに、ボリュームに対して重複排除処理を実行できます。

* * 編集 * 。
+
効率化ポリシーの編集ダイアログボックスを開きます。このダイアログボックスで、重複排除処理のスケジュール、しきい値、 QoS タイプ、および最大実行時間を変更できます。

* * 削除 *
+
効率化ポリシーの削除ダイアログボックスを開きます。このダイアログボックスで、選択した効率化ポリシーを削除できます。

* * ステータス *
+
ドロップダウンメニューを開きます。選択した効率化ポリシーを有効または無効にするオプションがあります。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== 効率化ポリシーのリスト

* * ポリシー *
+
効率化ポリシーの名前を指定します。

* * ステータス *
+
効率化ポリシーのステータスを指定します。ステータスは、次のいずれかになります。

+
** 有効
+
効率化ポリシーを重複排除処理に割り当てることができるように指定します。

** 無効
+
効率化ポリシーが無効であることを示します。ポリシーを有効にするには、 status ドロップダウンメニューを使用してポリシーを有効にし、あとで重複排除処理に割り当てることができます。



* * 実行者 *
+
ストレージ効率化ポリシーをスケジュールとしきい値（変更ログのしきい値）のどちらに基づいて実行するかを指定します。

* * QoS ポリシー *
+
ストレージ効率化ポリシーの QoS タイプを指定します。QoS タイプは、次のいずれかになります。

+
** 背景（ Background ）
+
QoS ポリシーをバックグラウンドで実行するように指定します。このタイプを使用すると、クライアント処理へのパフォーマンスの影響を軽減できます。

** ベストエフォート
+
QoS ポリシーをベストエフォートベースで実行するように指定します。これにより、システムリソースの利用率を最大限に高めることができます。



* * 最大実行時間 *
+
効率化ポリシーの最大実行時間を指定します。この値を指定しない場合は、処理が完了するまで効率化ポリシーが実行されます。





== 詳細領域

効率化ポリシーのリストの下の領域には、選択した効率化ポリシーに関する追加情報が表示されます。スケジュールベースのポリシーのスケジュール名と詳細、およびしきい値ベースのポリシーのしきい値などが含まれます。
