---
permalink: online-help-96-97/reference_system_health_window.html 
sidebar: sidebar 
keywords: system, alerts, command, buttons, window, online, help 
summary: システムヘルスアラートの詳細については、 System Alerts （システムアラート）ウィンドウを参照してください。また、アラートの承認、削除、および抑制もこのウィンドウから実行できます。 
---
= System Alerts （システムアラート）ウィンドウ
:icons: font
:imagesdir: ../media/


[role="lead"]
システムヘルスアラートの詳細については、 System Alerts （システムアラート）ウィンドウを参照してください。また、アラートの承認、削除、および抑制もこのウィンドウから実行できます。



== コマンドボタン

* * 確認 *
+
選択したアラートを承認し、問題に対処中であることを示すことができます。このボタンをクリックしたユーザが「承認者」に設定されます。

* * 抑制 *
+
選択したアラートを抑制して、同じアラートが再び通知されないようにすることができます。ユーザは「抑制者」と特定されます。

* * 削除 *
+
選択したアラートを削除します。

* * 更新 *
+
ウィンドウ内の情報を更新します。





== アラートのリスト

* * サブシステム（番号警告数） *
+
SAS 接続、スイッチヘルス、 CIFS NDO 、 MetroCluster など、アラートが生成されるサブシステムの名前が表示されます。

* * アラート ID*
+
アラート ID が表示されます。

* * ノード *
+
アラートが生成されるノードの名前が表示されます。

* * 重大度 *
+
アラートの重大度を「 Unknown 」、「 Other 」、「 Information 」、「 Degraded 」、「 Minor 」、 メジャー ' クリティカル ' 致命的

* * リソース *
+
特定のシェルフやディスクなど、アラートを生成したリソースが表示されます。

* * 時間 *
+
アラートが生成された時刻が表示されます。





== 詳細領域

詳細領域には、アラートが生成された時刻や、そのアラートが承認されているかどうかなど、アラートに関する詳細情報が表示されます。また、考えられる原因、アラートによって発生する状態が与えるかもしれない影響、およびアラートによって報告された問題を修正するための推奨される対処方法なども示されます。

* 関連情報 *

xref:task_acknowledging_system_health_alerts.adoc[システムヘルスアラートの承認]

xref:task_suppressing_system_health_alerts.adoc[システムヘルスアラートの抑制]

xref:task_deleting_system_health_alerts.adoc[システムヘルスアラートの削除]
