---
permalink: online-help-96-97/task_editing_vault_relationships.html 
sidebar: sidebar 
keywords: edit, vault, relationships, system, manager, online, help, cluster, schedule 
summary: System Manager を使用して、クラスタの既存のポリシーまたはスケジュールを選択するか、新しいポリシーまたはスケジュールを作成して、バックアップ関係を編集することができます。ただし、既存のポリシーやスケジュールのパラメータを編集することはできません。 
---
= バックアップ関係を編集しています
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して、クラスタの既存のポリシーまたはスケジュールを選択するか、新しいポリシーまたはスケジュールを作成して、バックアップ関係を編集することができます。ただし、既存のポリシーやスケジュールのパラメータを編集することはできません。

ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. ポリシーまたはスケジュールを変更するバックアップ関係を選択し、 * 編集 * をクリックします。
. [ 関係の編集 * （ Edit Relationship * ） ] ダイアログボックスで、適切なアクションを選択する。
+
|===
| 状況 | 実行する処理 


 a| 
既存のポリシーを選択してください。
 a| 
[* 参照 ] をクリックし、既存のポリシーを選択します。ソースボリュームに関連付けられた Snapshot ポリシーと最も多くのラベルが一致するポリシーを選択できます。



 a| 
新しいポリシーを作成します。
 a| 
.. [ ポリシーの作成 *] をクリックします。
.. ポリシーの名前を指定します。
.. スケジュールされた転送の優先順位を設定します。
+
転送の優先順位を「低」にすると優先順位が最も低くなり、優先順位が「通常」の転送よりもあとにスケジュールされます。デフォルトでは、優先度は Normal に設定されます。

.. 転送中のデータを圧縮するには、 [ ネットワーク圧縮を有効にする *] チェックボックスをオンにします。
.. バックアップポリシーの SnapMirror ラベルとデスティネーションの保持数を指定します。
+
新しい SnapMirror ラベルを有効にするには、同じラベルの Snapshot コピーをソースボリュームに作成する必要があります。

.. [ 作成（ Create ） ] をクリックします。


|===
. 関係のスケジュールを指定します。
+
|===
| 状況 | 実行する処理 


 a| 
既存のスケジュールを割り当てる
 a| 
リストから既存のスケジュールを選択します。



 a| 
新しいスケジュールを作成する
 a| 
.. [ スケジュールの作成 *] をクリックします。
.. スケジュールの名前を指定します。
.. 次のいずれかのオプションを選択します。
+
*** * 基本 *
+
曜日、時刻、および転送間隔だけを指定する場合に選択します。

*** * 詳細 *
+
cron 形式のスケジュールを指定する場合に選択します。



.. [ 作成（ Create ） ] をクリックします。




 a| 
スケジュールを割り当てない
 a| 
「 * なし * 」を選択します。

|===
. [OK] をクリックします。


* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]
