---
permalink: online-help-96-97/task_setting_up_network_when_ip_address_range_is_enabled.html 
sidebar: sidebar 
keywords: setp, up, network, ip, address, range, enable, online, help 
summary: IP アドレス範囲を有効にしてネットワークを設定することができます。IP アドレス範囲を使用すると、同じネットマスク範囲または異なるネットマスク範囲の IP アドレスを入力できます。 
---
= IP アドレス範囲を有効にした状態でのネットワークの設定
:icons: font
:imagesdir: ../media/


[role="lead"]
IP アドレス範囲を有効にしてネットワークを設定することができます。IP アドレス範囲を使用すると、同じネットマスク範囲または異なるネットマスク範囲の IP アドレスを入力できます。

.手順
. [IP アドレス範囲 *] フィールドに IP アドレスの範囲を入力し、 [ 適用 *] をクリックします。
+
|===
| オプション | 説明 


 a| 
同じネットマスクの IP アドレスの範囲を使用しています
 a| 
IP アドレスの範囲を入力し、 * 適用 * をクリックします。IP アドレスがクラスタ管理、ノード管理、およびサービスプロセッサ管理のネットワークに順番に適用されます。



 a| 
異なるネットマスクの IP アドレスの範囲を使用する
 a| 
各 IP アドレス範囲を別々の行に入力し、 * 適用 * をクリックします。最初の IP アドレスがクラスタ管理に適用され、残りの IP アドレスがノード管理とサービスプロセッサ管理のネットワークに順番に適用されます。

|===
+
[NOTE]
====
クラスタ管理、ノード管理、およびサービスプロセッサ管理の IP アドレス範囲を入力した場合、それらのフィールドの IP アドレスの値を手動で変更することはできません。すべての IP アドレスが IPv4 アドレスであることを確認してください。

====
. ネットマスクとゲートウェイの詳細を入力します。
. Port * フィールドで、クラスタ管理用のポートを選択します。
. ノード管理の「 * Port * 」フィールドに「 * e0m * 」が指定されていない場合は、ポートの詳細を入力します。
+
[NOTE]
====
デフォルトでは、 Port フィールドには e0M と表示されます。

====
. サービスプロセッサ管理のデフォルト値を上書きする場合は、必須のゲートウェイの詳細が入力されていることを確認します。
. *DNS Details* フィールドを有効にした場合は、 DNS サーバーの詳細を入力します。
. [NTP Details] * フィールドを有効にした場合は、 NTP サーバの詳細を入力します。
+
[NOTE]
====
代替 NTP サーバの詳細はオプションです。

====
. [Submit （送信） ] をクリックします。




== 次に何をするか

サポートページにイベント通知を入力して、クラスタのセットアップを続行します。

* 関連情報 *

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/What_is_a_Service_Processor_and_how_do_I_use_it%3F["サービスプロセッサとは何ですか？また、どのように使用しますか？"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_configure_and_troubleshoot_NTP_on_clustered_Data_ONTAP_8.2_and_later_using_CLI["CLI を使用して clustered Data ONTAP 8.2 以降で NTP を設定およびトラブルシューティングする方法"]

https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 ドキュメンテーション・センター"]
