---
permalink: online-help-96-97/task_editing_mirror_relationships.html 
sidebar: sidebar 
keywords: system, manager, edit, mirror, relationships, online, help 
summary: System Manager を使用して、クラスタの既存のポリシーまたはスケジュールを選択するか、ポリシーまたはスケジュールを作成して、ミラー関係を編集することができます。 
---
= System Manager - ONTAP 9.7 以前を使用してミラー関係を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、ミラー関係を管理できます。休止したミラー関係の再開に加え、ミラー関係の更新、休止、初期化、再確立、削除、および編集を行うことができます。



== 関係を削除します

[role="lead"]
System Manager を使用して、ミラー関係を削除し、ソースボリュームとデスティネーションボリュームの間のミラー関係を完全に終了できます。ミラー関係を削除すると、ソースボリュームのベース Snapshot コピーが削除されます。

ミラー関係を削除する前に、その関係を解除することが推奨されます。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 削除するミラー関係を選択し、 * Delete * をクリックします。
. 確認のチェックボックスを選択してミラー関係を削除し、ベース Snapshot コピーを解放して、 * Delete * をクリックします。


関係が削除され、ソースボリュームのベース Snapshot コピーが削除されます。

* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]



== 関係を再同期する

[role="lead"]
System Manager を使用して、以前に解除したミラー関係を再確立できます。再同期操作を実行して、災害によってソースボリュームが機能しなくなった状態からリカバリできます。

ソースクラスタとデスティネーションクラスタ、およびソース SVM とデスティネーション SVM でピア関係が確立されている必要があります。

.このタスクについて
* 再同期操作を実行すると、ミラーデスティネーションの内容がソースボリュームの内容で上書きされます。
+
[NOTE]
====
** SnapLock 準拠ボリュームでは、アクティブファイルシステム内で共通の Snapshot コピーに関連するデータ変更は、現在のボリュームに設定されている有効期限まではロックされた Snapshot コピーに保持されます。
+
ボリュームの有効期限がすでに過ぎているか設定されていない場合は、 Snapshot コピーおよび共通の Snapshot コピーが 30 日間ロックされます。共通の Snapshot コピーからロックされた最新の Snapshot コピーまでの間の中間の Snapshot コピーはすべて削除されます。

** SnapLock Compliance ボリューム以外のボリュームでは、ベースの Snapshot コピーが作成されたあとにデスティネーションボリュームに書き込まれた新しいデータが原因によって失われる可能性があります。


====
* Protection ウィンドウの Last Transfer Error フィールドで再同期操作を実行するように推奨された場合は、まず関係を解除してから再同期処理を実行する必要があります。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 再同期するミラー関係を選択します。
. [* Operations] * > [* Resync] をクリックします。
. 確認のチェックボックスをオンにし、 * Resync * をクリックします。


* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]



== 休止した関係を再開します

[role="lead"]
System Manager を使用して、休止中のミラー関係を再開できます。関係を再開すると、ミラーデスティネーションへの通常のデータ転送が再開され、ミラー処理もすべて再開されます。

解除されたミラー関係をコマンドラインインターフェイス（ CLI ）で休止した場合は、 System Manager で再開することはできません。CLI を使用して関係を再開してください。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 再開するミラー関係を選択します。
. [* オペレーション * > * 再開 * （ Operations * > * Resume * ） ] をクリック
. 確認のチェックボックスをオンにし、 * Resume * （続行）をクリックします。


選択したミラー関係のミラーデスティネーションへのデータ転送が再開されます。

* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]



== 関係を更新します

[role="lead"]
System Manager を使用して、スケジュールされていないデスティネーションのミラー更新を開始できます。予定された停電、スケジュールされた保守、またはデータ移行によるデータ損失を防ぐために、手動更新が必要になる場合があります。

ミラー関係は SnapMirror 済みの状態である必要があります。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. データを更新するミラー関係を選択し、 * Operations * > * Update * をクリックします。
. 次のいずれかのオプションを選択します。
+
** ソースボリュームとデスティネーションボリュームの間の最新の共通の Snapshot コピーに基づく差分転送を実行するには、「 * on demand * 」を選択します。
** Select Snapshot copy * を選択し、転送する Snapshot コピーを指定します。


. 転送に使用するネットワーク帯域幅を制限するには、「 * 転送帯域幅を * に制限」を選択し、最大転送速度を指定します。
. [ 更新（ Update ） ] をクリックします。
. [ * 詳細 * ] タブで転送ステータスを確認します。


* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]



== 関係を休止します

[role="lead"]
System Manager を使用して、 Snapshot コピーを作成する前にミラーデスティネーションを休止して、安定した状態にすることができます。休止処理を実行すると、アクティブなミラー転送が完了したあと、ミラーリング関係の以降の転送が実行されなくなります。

休止できるのは、 SnapMirror 済み状態のミラー関係のみです。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 休止するミラー関係を選択します。
. [* 操作 *>] [ * 休止 ] をクリックします。
. 確認のチェックボックスをオンにし、 * 休止 * をクリックします。


* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]



== 関係を初期化

[role="lead"]
ミラー関係を開始する際には、関係を初期化する必要があります。関係を初期化すると、ソースボリュームからデスティネーションへのデータのベースライン転送が実行されます。System Manager を使用して、作成時に初期化していないミラー関係を初期化することができます。

.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 初期化するミラー関係を選択します。
. [* Operations] * > [* Initialize] をクリックします。
. 確認のチェックボックスをオンにし、 * Initialize * （初期化）をクリックします。
. [ 保護（ Protection ） ] ウィンドウで、ミラー関係のステータスを確認します。


Snapshot コピーが作成されてデスティネーションに転送されます。この Snapshot コピーは、以降の差分 Snapshot コピーのベースラインとして使用されます。

* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]



== 関係を編集します

[role="lead"]
System Manager を使用して、クラスタの既存のポリシーまたはスケジュールを選択するか、ポリシーまたはスケジュールを作成して、ミラー関係を編集することができます。

.このタスクについて
* Data ONTAP 8.2.1 のボリュームと ONTAP 8.3 以降のボリュームの間に作成されたミラー関係は編集できません。
* 既存のポリシーやスケジュールのパラメータを編集することはできません。
* バージョンに依存しないミラー関係、バックアップ関係、またはミラーとバックアップ関係について、ポリシーのタイプを変更することで関係のタイプを変更することができます。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. ポリシーまたはスケジュールを変更するミラー関係を選択し、 * Edit * をクリックします。
. ［ * 関係の編集 * ］ ダイアログボックスで、既存のポリシーを選択するか、ポリシーを作成します。
+
|===
| 状況 | 実行する処理 


 a| 
既存のポリシーを選択してください。
 a| 
[* 参照 ] をクリックし、既存のポリシーを選択します。



 a| 
ポリシーを作成する
 a| 
.. [ ポリシーの作成 *] をクリックします。
.. ポリシーの名前を指定します。
.. スケジュールされた転送の優先順位を設定します。
+
転送の優先順位を「低」にすると優先順位が最も低くなり、優先順位が「通常」の転送よりもあとにスケジュールされます。デフォルトでは、優先度は Normal に設定されます。

.. 「 all_source_snapshots 」ルールをミラーポリシーに含めるには、「 * すべてのソース Snapshot コピーを転送 * 」チェックボックスを選択します。これにより、ソースボリュームのすべての Snapshot コピーをバックアップできます。
.. 転送中のデータを圧縮するには、 [ ネットワーク圧縮を有効にする *] チェックボックスをオンにします。
.. [ 作成（ Create ） ] をクリックします。


|===
. 関係のスケジュールを指定します。
+
|===
| 状況 | 実行する処理 


 a| 
既存のスケジュールを割り当てる
 a| 
スケジュールのリストから既存のスケジュールを選択します。



 a| 
スケジュールを作成する
 a| 
.. [ スケジュールの作成 *] をクリックします。
.. スケジュールの名前を指定します。
.. [*Basic*] または [*Advanced*] を選択します。
+
*** basic は、曜日、時刻、および転送間隔だけを指定します。
*** advanced を指定すると、 cron 形式のスケジュールが作成されます。


.. [ 作成（ Create ） ] をクリックします。




 a| 
スケジュールを割り当てない
 a| 
「 * なし * 」を選択します。

|===
. [OK] をクリックして変更を保存します。


* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]
