---
permalink: online-help-96-97/task_editing_share_settings.html 
sidebar: sidebar 
keywords: edit, share, settings, system, manager, online, help 
summary: System Manager を使用して、シンボリックリンクの設定、共有に対するユーザやグループのアクセス権、共有へのアクセスの種類など、共有設定を変更することができます。また、 Hyper-V による共有の継続的可用性や Access-Based Enumeration （ ABE ；アクセスベースの列挙）を有効または無効にすることもできます。System Manager 9.6 以降では、 FlexGroup ボリュームの継続的可用性がサポートされます。 
---
= 共有設定を編集しています
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して、シンボリックリンクの設定、共有に対するユーザやグループのアクセス権、共有へのアクセスの種類など、共有設定を変更することができます。また、 Hyper-V による共有の継続的可用性や Access-Based Enumeration （ ABE ；アクセスベースの列挙）を有効または無効にすることもできます。System Manager 9.6 以降では、 FlexGroup ボリュームの継続的可用性がサポートされます。

.手順
. [* ストレージ *>* 共有 ] をクリックします。
. 共有のリストから変更する共有を選択し、 * 編集 * をクリックします。
. 共有設定の編集 * ダイアログボックスで、必要に応じて共有設定を変更します。
+
.. General * タブで、 Hyper-V による共有の継続的可用性を有効にします
+
継続的可用性を有効にすると、 SMB 3.0 をサポートする SMB 3.0 クライアントで、無停止運用時にファイルを継続して開いておくことができます。継続して開いておくように指定したファイルは、フェイルオーバー、ギブバック、 LIF の移行など、システムを停止させるイベントから保護されます。

.. [ * アクセス許可 * ] タブで、ユーザーまたはグループを追加し、アクセスの種類を指定するアクセス許可を割り当てます。
.. [ * オプション * （ * Options * ） ] タブで、必要なオプションを選択します。


. [ 保存して閉じる ] をクリックします。
. [* 共有 ] ウィンドウで選択した共有に加えた変更を確認します。


* 関連情報 *

xref:reference_shares_window.adoc[共有ウィンドウ]
