---
permalink: online-help-96-97/task_creating_mirror_relationship_from_destination_svm.html 
sidebar: sidebar 
keywords: create, mirror, relationship, destination, svm, online, help, system, manager 
summary: ONTAP System Manager を使用して、ミラー関係をデスティネーション Storage Virtual Machine （ SVM ）から作成し、ポリシーとスケジュールをそのミラー関係に割り当てることができます。ミラーコピーを作成しておけば、ソースボリュームのデータが破損した場合や失われた場合でも、データをすぐに使用できます。 
---
= デスティネーション SVM からミラー関係を作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager を使用して、ミラー関係をデスティネーション Storage Virtual Machine （ SVM ）から作成し、ポリシーとスケジュールをそのミラー関係に割り当てることができます。ミラーコピーを作成しておけば、ソースボリュームのデータが破損した場合や失われた場合でも、データをすぐに使用できます。

.作業を開始する前に
* ソースクラスタで ONTAP 8.2.2 以降が実行されている必要があります。
* ソースクラスタとデスティネーションクラスタで SnapMirror ライセンスが有効になっている必要があります。
+
[NOTE]
====
一部のプラットフォームでは、デスティネーションクラスタで SnapMirror ライセンスに加えて Data Protection Optimization （ DPO ）ライセンスが有効になっていれば、ソースクラスタで SnapMirror ライセンスが有効になっていなくてもかまいません。

====
* ボリュームのミラーリングで SnapLock ボリュームをソースとして選択する場合、デスティネーションクラスタに SnapMirror ライセンスと SnapLock ライセンスがインストールされている必要があります。
* ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。
* デスティネーション SVM の使用可能なスペースを確保する必要があります。
* 読み書き可能（ rw ）タイプのソースボリュームを用意しておく必要があります。
* FlexVol がオンラインであり、読み書き可能タイプである必要があります。
* SnapLock アグリゲートのタイプが同じである必要があります。
* ONTAP 9.2 以前のバージョンを実行しているクラスタから Security Assertion Markup Language （ SAML ）認証が有効になっているリモートクラスタに接続する場合は、リモートクラスタでパスワードベースの認証を有効にする必要があります。


.このタスクについて
* System Manager ではカスケード関係はサポートされません。
+
たとえば、関係のデスティネーションボリュームを別の関係のソースボリュームにすることはできません。

* MetroCluster 構成の同期元の SVM と同期先の SVM の間にミラー関係を作成することはできません。
* MetroCluster 構成の同期元の SVM 間にはミラー関係を作成できます。
* 同期元の SVM のボリュームからデータ提供用の SVM のボリュームへのミラー関係を作成できます。
* データ提供用の SVM のボリュームから同期元の SVM のデータ保護（ DP ）ボリュームへのミラー関係を作成できます。
* ミラー関係は、同じタイプの SnapLock 間でのみ作成できます。
+
たとえば、ソースボリュームが SnapLock Enterprise ボリュームの場合は、デスティネーションボリュームも SnapLock Enterprise ボリュームである必要があります。デスティネーション SVM SnapLock で同じタイプのアグリゲートを使用できることを確認する必要があります。

* ミラー関係用に作成されたデスティネーションボリュームはシンプロビジョニングされません。
* 一度に保護できるボリュームは最大 25 個です。
* ソースクラスタよりも古いバージョンの ONTAP をデスティネーションクラスタで実行している場合、 ONTAP ボリューム間にミラー関係 SnapLock を作成することはできません。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. [ ボリューム関係 * ] ウィンドウで、 [ * 作成 ] をクリックします。
. [* SVM を参照 * ] ダイアログボックスで、デスティネーションボリュームの SVM を選択します。
. [ 保護関係の作成 *] ダイアログボックスで、 [ 関係タイプ *] ドロップダウンリストから [ ミラー *] を選択します。
. クラスタ、 SVM 、およびソースボリュームを指定します。
+
指定したクラスタで ONTAP 9.3 より前のバージョンの ONTAP ソフトウェアが実行されている場合、ピア関係が設定された SVM だけが表示されます。指定したクラスタで ONTAP 9.3 以降が実行されている場合は、ピア関係が設定された SVM と許可された SVM が表示されます。

. FlexVol ボリュームの場合は、ボリューム名サフィックスを指定します。
+
ボリューム名サフィックスをソースボリュームの名前に追加したものがデスティネーションボリュームの名前として使用されます。

. [* 参照 ] をクリックし、ミラーポリシーを変更します。
. 既存のスケジュールのリストから関係のスケジュールを選択します。
. 関係の初期化を選択してミラー関係を初期化します。
. FabricPool 対応アグリゲートを有効にし、適切な階層化ポリシーを選択します。
. [ 作成（ Create ） ] をクリックします。


デスティネーションボリュームを作成するように選択した場合は、 type _dp_is のデスティネーションボリュームが作成され、言語属性はソースボリュームと同じになります。

ソースボリュームとデスティネーションボリュームの間にミラー関係が作成されます。関係を初期化するように選択した場合は、ベース Snapshot コピーがデスティネーションボリュームに転送されます。

* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]
