---
permalink: online-help-96-97/task_adding_disks_to_storage_pool.html 
sidebar: sidebar 
keywords: system, manager, ssd, storage, pool, disk, online, help 
summary: System Manager を使用して、既存のストレージプールに SSD を追加してキャッシュサイズを拡張できます。 
---
= ストレージプールにディスクを追加します
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して、既存のストレージプールに SSD を追加してキャッシュサイズを拡張できます。

ストレージプール経由で SSD と SSD スペアを割り当てるためには、 HA ペアの両方のノードが稼働している必要があります。

.このタスクについて
* ストレージプールに追加した SSD は、ストレージプールキャッシュを使用する各アグリゲートと、ストレージプールの空きスペースに、均等に配分されます。
* ストレージプールへのディスクの追加に SSD を使用する際、 System Manager は、 SSD RAID グループにホットスペアルールを適用します。
+
たとえば、 SSD RAID グループに 10 個の SSD があり、オプション「 raid.min_spare_count 」がノードレベルで「 1 」に設定されている場合、 System Manager は 1 個の SSD をホットスペアとして残し、他の 9 個の SSD を SSD 関連の操作に使用します。

* System Manager を使用してディスクをストレージプールに追加する場合、パーティショニングされた SSD は使用できません。


.手順
. [ * ストレージ * > * アグリゲートとディスク * > * ストレージプール * ] をクリックします。
. [ * ストレージプール * ] ウィンドウで、ストレージプールを選択し、 [ * ディスクの追加 * ] をクリックします。
. [ * ディスクの追加 * ] ダイアログボックスで、追加するディスクの数を指定します。
. 「 * 次へ * 」をクリックします。
. サマリー * ダイアログボックスで、各アグリゲートとストレージプールの空きスペースにどのようにキャッシュが分散されているかを確認します。
. [ 追加（ Add ） ] をクリックします。


* 関連情報 *

xref:reference_storage_pools_window.adoc[ストレージプールウィンドウ]
