---
permalink: online-help-96-97/task_creating_network_interfaces.html 
sidebar: sidebar 
keywords: create, network, interface, online, help, system, manager, lif, intercluster, svm 
summary: System Manager を使用して、 Storage Virtual Machine （ SVM ）からのデータアクセス、 SVM の管理、クラスタ間接続を行うためのネットワークインターフェイスまたは LIF を作成できます。 
---
= ネットワークインターフェイスを作成
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して、 Storage Virtual Machine （ SVM ）からのデータアクセス、 SVM の管理、クラスタ間接続を行うためのネットワークインターフェイスまたは LIF を作成できます。

サブネットに関連付けたブロードキャストドメインにポートを割り当てておきます。

.このタスクについて
* LIF の作成時には、 Dynamic DNS （ DDNS ；動的 DNS ）がデフォルトで有効になります。
+
ただし、 iSCSI 、 NVMe 、 FC / FCoE のいずれかのプロトコルを使用するクラスタ間通信用の LIF 、または管理アクセス専用の LIF を設定する場合は、 DDNS が無効になります。

* IP アドレスは、サブネットを使用しても使用しなくても指定できます。
* ポートがデグレード状態の場合、 System Manager でネットワークインターフェイスを作成することはできません。
+
このような場合は、コマンドラインインターフェイス（ CLI ）を使用してネットワークインターフェイスを作成してください。

* NVMeoF データ LIF を作成するには、 SVM がセットアップ済みで、 SVM に NVMe サービスがあり、 NVMeoF 対応アダプタが使用可能である必要があります。
* NVMe プロトコルは、選択した SVM に NVMe サービスが設定されている場合にのみ有効になります。


.手順
. [ * ネットワーク * ] > [* ネットワーク・インターフェイス * ] をクリックします。
. [ 作成（ Create ） ] をクリックします。
. Create Network Interface * ダイアログボックスで、インターフェイス名を指定します。
. インターフェイスロールを指定します。
+
|===
| 状況 | 作業 


 a| 
ネットワークインターフェイスをデータ LIF に関連付けます
 a| 
.. [*Serves Data*] を選択します。
.. ネットワークインターフェイスの SVM を選択してください。




 a| 
ネットワークインターフェイスをクラスタ間 LIF に関連付けます
 a| 
.. 「 * クラスタ間接続 * 」を選択します。
.. ネットワークインターフェイスの IPspace を選択します。


|===
. 適切なプロトコルを選択します。
+
インターフェイスは、このプロトコルを使用して、 SVM からデータにアクセスします。

+
[NOTE]
====
NVMe プロトコルを選択すると、残りのプロトコルは無効になります。NAS （ CIFS および NFS ）プロトコルがサポートされている場合、それらのプロトコルは引き続き使用できます。NVMe プロトコルを選択すると NVMe 転送フィールドが表示され、 FC-NVMe プロトコルが転送プロトコルとして表示されます。

====
. データ LIF で管理アクセスを有効にする場合は、 * 管理アクセスの有効化 * チェックボックスを選択します。
+
クラスタ間 LIF 、または FC / FCoE プロトコルや NVMe プロトコルを使用する LIF では、管理アクセスを有効にすることはできません。

. IP アドレスを割り当てます。
+
|===
| 状況 | 作業 


 a| 
サブネットを使用して IP アドレスを指定します
 a| 
.. サブネットを使用する * を選択します。
.. Add Details ダイアログボックスで、 IP アドレスを割り当てるサブネットを選択します。
+
クラスタ間 LIF の場合、選択した IPspace に関連付けられているサブネットだけが表示されます。

.. インターフェイスに特定の IP アドレスを割り当てる場合は、 * 特定の IP アドレスを使用する * を選択して、 IP アドレスを入力します。
+
指定した IP アドレスがサブネット内にない場合、追加されます。

.. [OK] をクリックします。




 a| 
サブネットを使用せずに手動で IP アドレスを指定します
 a| 
.. サブネットなし * を選択します。
.. [ 詳細の追加 ] ダイアログボックスで、次の手順を実行します。
+
... IP アドレスとネットワークマスクまたはプレフィックスを指定します。
... オプション：ゲートウェイを指定します。
... Destination フィールドにデフォルト値を使用しない場合は、新しい宛先値を指定します。
+
送信先の値を指定しない場合は、 IP アドレスのファミリーに基づいて、 Destination フィールドにデフォルト値が設定されます。



+
ルートが存在しない場合は、ゲートウェイとデスティネーションに基づいて新しいルートが自動的に作成されます。

.. [OK] をクリックします。


|===
. ポート * の詳細領域から必要なポートを選択します。
+
** データ LIF の場合、ポートの詳細領域には、 SVM の IPspace に関連付けられたブロードキャストドメインにあるすべてのポートが表示されます。
** クラスタ間 LIF の場合、ポートの詳細領域には、要求された IPspace に関連付けられたブロードキャストドメインにあるすべてのポートが表示されます。
** NVMe プロトコルが選択されている場合、ポートの詳細領域には NVMe 対応アダプタのみが表示されます。


. DDNS を有効にするには、 * Dynamic DNS （ DDNS ） * チェックボックスを選択します。
. [ 作成（ Create ） ] をクリックします。


* 関連情報 *

xref:reference_network_window.adoc[[ ネットワーク ] ウィンドウ]

xref:task_configuring_iscsi_protocol_on_svms.adoc[SVM で iSCSI プロトコルを設定します]

xref:task_configuring_node_details_system_manager.adoc[ノードのネットワークの詳細を設定]
