---
permalink: online-help-96-97/task_creating_cluster_peer_relationships.html 
sidebar: sidebar 
keywords: system, manager, create, cluster, peer, relationships, online, help 
summary: 認証されたクラスタピア関係を作成してクラスタを接続し、ピア関係にあるクラスタ間で安全に通信できるようにすることができます。 
---
= クラスタピア関係を作成
:icons: font
:imagesdir: ../media/


[role="lead"]
認証されたクラスタピア関係を作成してクラスタを接続し、ピア関係にあるクラスタ間で安全に通信できるようにすることができます。

.作業を開始する前に
* この作業の実行に関する要件を確認して満たしておく必要があります。
+
link:reference_prerequisites_for_cluster_peering.md#["クラスタピアリングの前提条件"]

* クラスタ間論理インターフェイス（ LIF ）を作成しておく必要があります。
* 各クラスタで実行している ONTAP のバージョンを確認しておく必要があります。


.このタスクについて
* Data ONTAP 8.2.2 以前を実行するクラスタとの間にピア関係を作成する場合は、 CLI を使用する必要があります。
* ONTAP 9.5 を実行しているクラスタと ONTAP 9.6 を実行しているクラスタの間にピア関係を作成できます。ただし、 ONTAP 9.5 では暗号化がサポートされていないため、ピア関係を暗号化することはできません。
* MetroCluster 構成では、プライマリクラスタと外部クラスタの間にピア関係を作成する場合、セカンダリサイトのクラスタと外部クラスタの間にもピア関係を作成することを推奨します。
* クラスタピア関係の認証には、カスタムのパスフレーズかシステム生成のパスフレーズを使用できます。ただし、両方のクラスタのパスフレーズが一致している必要があります。


.手順
. [ * Configuration * ] > [* Advanced Cluster Setup* ] をクリックします。
. 「 * ターゲットクラスタのクラスタ間 LIF IP アドレス」フィールドに、リモートクラスタのクラスタ間 LIF の IP アドレスを入力します。
. ONTAP 9.5 を実行しているクラスタと ONTAP 9.6 を実行しているクラスタの間にピア関係を作成する場合はチェックボックスを選択します。
+
ピア関係は暗号化されません。チェックボックスを選択しないとピア関係は確立されません。

. パスフレーズ * フィールドで、クラスタピア関係のパスフレーズを指定します。
+
カスタムのパスフレーズを作成すると、認証されたクラスタピア関係を確立するために、指定したパスフレーズがピアクラスタのパスフレーズに照らして検証されます。

+
ローカルクラスタとリモートクラスタの名前が同じ場合にカスタムのパスフレーズを使用すると、リモートクラスタのエイリアスが作成されます。

. リモートクラスタからパスフレーズを生成するには、リモートクラスタの管理 IP アドレスを入力します。
. クラスタピアリングを開始します。
+
|===
| 状況 | 手順 


 a| 
イニシエータクラスタからクラスタピアリングを開始します
 a| 
[* クラスタピアリングの開始 * ] をクリックします。



 a| 
リモートクラスタからクラスタピアリングを開始する（カスタムのパスフレーズを作成している場合に適用）
 a| 
.. リモートクラスタの管理 IP アドレスを入力します。
.. リモートクラスタにアクセスするには、 * 管理 URL * リンクをクリックしてください。
.. Create Cluster Peering * をクリックします。
.. イニシエータクラスタのクラスタ間 LIF の IP アドレスとパスフレーズを指定します。
.. [ * ピアリングの開始 * ] をクリックします。
.. イニシエータクラスタにアクセスし、 * ピアリングの検証 * をクリックします。


|===




== 次に何をするか

ピアリングプロセスを続行するには、 SVM ピアリングウィンドウで SVM の詳細を指定する必要があります。
