---
permalink: online-help-96-97/task_resynchronizing_mirror_relationships.html 
sidebar: sidebar 
keywords: resync, mirror, relationship, operation, online, help 
summary: 以前に解除したミラー関係を再確立できます。再同期操作を実行して、災害によってソースボリュームが機能しなくなった状態からリカバリできます。 
---
= ミラー関係を再同期中です
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以前に解除したミラー関係を再確立できます。再同期操作を実行して、災害によってソースボリュームが機能しなくなった状態からリカバリできます。

ソースクラスタとデスティネーションクラスタ、およびソース SVM とデスティネーション SVM でピア関係が確立されている必要があります。

.このタスクについて
* 再同期操作を実行すると、ミラーデスティネーションの内容がソースボリュームの内容で上書きされます。
+
[NOTE]
====
** SnapLock 準拠ボリュームでは、アクティブファイルシステム内で共通の Snapshot コピーに関連するデータ変更は、現在のボリュームに設定されている有効期限まではロックされた Snapshot コピーに保持されます。
+
ボリュームの有効期限がすでに過ぎているか設定されていない場合は、 Snapshot コピーおよび共通の Snapshot コピーが 30 日間ロックされます。共通の Snapshot コピーからロックされた最新の Snapshot コピーまでの間の中間の Snapshot コピーはすべて削除されます。

** SnapLock Compliance ボリューム以外のボリュームでは、ベースの Snapshot コピーが作成されたあとにデスティネーションボリュームに書き込まれた新しいデータが原因によって失われる可能性があります。


====
* Protection ウィンドウの Last Transfer Error フィールドで再同期操作を実行するように推奨された場合は、まず関係を解除してから再同期処理を実行する必要があります。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 再同期するミラー関係を選択します。
. [* Operations] * > [* Resync] をクリックします。
. 確認のチェックボックスをオンにし、 * Resync * をクリックします。


* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]
