---
permalink: online-help-96-97/task_changing_peering_encryption_status.html 
sidebar: sidebar 
keywords: change, peer, encryption, status, system, manager, cluster, online, help 
summary: System Manager を使用して、選択したクラスタのピアリングの暗号化ステータスを変更できます。 
---
= ピアリングの暗号化ステータスを変更しています
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して、選択したクラスタのピアリングの暗号化ステータスを変更できます。

暗号化ステータスは有効または無効にできます。[ 有効 ] から [ 無効 ] または [ 無効 ] から [ 有効 ] にステータスを変更するには、 [ * 暗号化の変更 * ] を選択します。

.手順
. [ * Configuration * ] > [* Cluster Peers* ] をクリックします。
. ピアクラスタを選択し、 * Edit * をクリックします
+
ドロップダウンメニューが表示されます。

. ［ * 暗号化の変更 * ］ をクリックします。
+
暗号化ステータスが「 N/A 」の場合、このアクションは使用できません。

+
[ 暗号化の変更 ] ダイアログボックスが表示されます。現在の暗号化ステータスがボタンに表示されます。

. ボタンをスライドしてピアリングの暗号化ステータスを変更し、次に進みます。
+
** 現在の暗号化ステータスが「 none 」の場合は、トグルボタンをスライドしてステータスを「 tls_psk 」に変更することで暗号化を有効にできます。
** 現在の暗号化ステータスが「 TLS_PSK 」の場合は、トグルボタンをスライドしてステータスを「 none 」に変更することで暗号化を無効にできます。


. ピアリングの暗号化を有効または無効にしたら、新しいパスフレーズを生成してピアクラスタで指定するか、ピアクラスタで生成済みの既存のパスフレーズを適用することができます。
+
[NOTE]
====
ローカルサイトで使用しているパスフレーズがリモートサイトで使用しているパスフレーズと一致しないと、クラスタピア関係は正しく機能しません。

====
+
次のいずれかを選択します。

+
** * パスフレーズを生成 * ：手順に進みます <<STEP_1ABAF15926174E709CA59192E200ABE3,#step_1ABAF15926174E709CA59192E200ABE3>>。
** * 既存のパスフレーズを使用 * ：手順に進みます <<STEP_2EFD822431974811AD2260C3F31DC977,#step_2EFD822431974811AD2260C3F31DC977>>。


. [*Generate a passphrase* （パスフレーズの生成） ] を選択した場合は、必要なフィールドに入力します
+
** * IPspace * ：ドロップダウンメニューから IPspace を選択します。
** * パスフレーズの有効期限 * ：パスフレーズを有効にする期間をドロップダウンメニューから選択します。
** * SVM 権限 * ：次のいずれかを選択します。
+
*** * すべての SVM * 。すべての SVM にクラスタへのアクセスを許可します。
*** * 選択した SVM * 。クラスタへのアクセスを許可する SVM を指定します。指定するフィールドで SVM 名を選択します。




. リモートクラスタの有効なクラスタバージョンが ONTAP 9.6 より前の場合はチェックボックスを選択します。選択しないとパスフレーズの生成が失敗します。
. [ 適用（ Apply ） ] をクリックします。
+
関係のパスフレーズが生成されて表示されます。パスフレーズはコピーするか E メールで送信することができます。

+
リモートクラスタでパスフレーズを指定するまで、ローカルクラスタの認証ステータスは、選択したパスフレーズの有効期間に「 ok_and_offer 」と表示されます。

. リモートクラスタで新しいパスフレーズを生成済みの場合は、次の手順を実行します。
+
.. [ * 既存のパスフレーズを使用する * ] をクリックします。
.. 「 * Passphrase * 」フィールドに、リモートクラスタで生成されたパスフレーズと同じパスフレーズを入力します。
.. [ 適用（ Apply ） ] をクリックします。



