---
permalink: online-help-96-97/task_adding_licenses.html 
sidebar: sidebar 
keywords: system, manager, add, license, storage, software, online, help 
summary: ストレージシステムソフトウェアが工場出荷時にインストールされている場合は、 System Manager によってそのソフトウェアがライセンスのリストに自動的に追加されます。ソフトウェアが工場出荷時にインストールされていない場合や追加のソフトウェアライセンスを追加する場合は、 System Manager を使用してソフトウェアライセンスを追加できます。 
---
= ライセンスを追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステムソフトウェアが工場出荷時にインストールされている場合は、 System Manager によってそのソフトウェアがライセンスのリストに自動的に追加されます。ソフトウェアが工場出荷時にインストールされていない場合や追加のソフトウェアライセンスを追加する場合は、 System Manager を使用してソフトウェアライセンスを追加できます。

特定の ONTAP サービスのソフトウェアライセンスコードを用意しておく必要があります。

.このタスクについて
* MetroCluster 構成で新しいライセンスを追加するときは、セカンダリサイトのクラスタにもライセンスを追加することを推奨します。
* System Manager を使用して Cloud Volumes ONTAP ライセンスを追加することはできません。
+
Cloud Volumes ONTAP ライセンスは、ライセンスページに表示されません。System Manager では、 Cloud Volumes ONTAP ライセンスのライセンス使用権リスクに関するアラートは通知されません。

* アップロードできるのは、容量ベースのライセンスだけです。
+
容量ベースのライセンスのタイプは「 JSON 」です。



.手順
. [* Configuration * （設定 * ） ] > [* Cluster * （クラスタ * ） ] > [* Licenses * （ライセンス *
. [ 追加（ Add ） ] をクリックします。
. [ ライセンスの追加 *] ダイアログボックスで、次の手順を実行します。
+
|===
| 状況 | 手順 


 a| 
特定の ONTAP サービスのライセンスを追加します
 a| 
.. ソフトウェアライセンスキーを入力します。
+
ソフトウェアライセンスキーをカンマで区切って入力することで複数のライセンスを追加できます。

.. [ 追加（ Add ） ] をクリックします。




 a| 
容量ベースのライセンスを追加します
 a| 
.. 参照をクリックし、容量ベースのライセンスファイルを選択します。
.. [ 追加（ Add ） ] をクリックします。




 a| 
特定の ONTAP サービスのライセンスと容量ベースのライセンスを追加する
 a| 
.. ソフトウェアライセンスキーを入力します。
+
ソフトウェアライセンスキーをカンマで区切って入力することで複数のライセンスを追加できます。

.. 参照をクリックし、容量ベースのライセンスファイルを選択します。
.. [ 追加（ Add ） ] をクリックします。


|===
+
新しいライセンスが追加されます。

+
[Add License Status] ダイアログボックスに、正常に追加されたライセンスのリストが表示されます。このダイアログボックスには、追加されなかったライセンスのライセンスキーもその理由とともに表示されます。

. [* 閉じる * ] をクリックします。


ソフトウェアライセンスがストレージシステムに追加され、 Licenses window のライセンスのリストに表示されます。

* 関連情報 *

xref:reference_licenses_window.adoc[ライセンスウィンドウ]
