---
permalink: online-help-96-97/task_managing_svm_relationships.html 
sidebar: sidebar 
keywords: system, manager, manage, svm, online, help, relationship 
summary: System Manager を使用して、 SVM 関係の初期化、 SVM 関係の更新、デスティネーション SVM のアクティブ化、ソース SVM からのデータの再同期、デスティネーション SVM からのデータの再同期、ソース SVM の再アクティブ化など、 SVM 関係に対するさまざまな処理を実行できます。 
---
= SVM 関係の管理
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して、 SVM 関係の初期化、 SVM 関係の更新、デスティネーション SVM のアクティブ化、ソース SVM からのデータの再同期、デスティネーション SVM からのデータの再同期、ソース SVM の再アクティブ化など、 SVM 関係に対するさまざまな処理を実行できます。

.作業を開始する前に
* SVM 関係を初期化するには、ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。
* SVM 関係を更新するには、 SVM 関係が初期化されて SnapMirror 済みの状態である必要があります。
* ソース SVM を再アクティブ化するには、デスティネーション SVM からのデータの再同期（逆再同期）処理を実行しておく必要があります。
* SVM 関係を作成する際にソース SVM の設定をコピーするオプションを選択した場合は、 SVM 関係をアクティブ化するためにソース SVM を停止する必要があります。
* ソースクラスタとデスティネーションクラスタで SnapMirror ライセンスが有効になっている必要があります。
* ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。
* デスティネーションクラスタの使用可能なスペースを確保する必要があります。
* ソース SVM に SVM ピアリングの権限が必要です。
* デスティネーション SVM のアクティブ化、ソース SVM からの再同期、デスティネーション SVM からの再同期（逆再同期）、およびソース SVM の再アクティブ化を行うには、 SVM 関係を解除する必要があります。
* ソース SVM を再アクティブ化するには、 SVM の逆方向の関係が存在し、かつ SnapMirror 済みの状態である必要があります。


.手順
. [ * 保護 * > * SVM 関係 * ] をクリックします。
. SVM 関係を選択し、該当する操作を実行します。
+
|===
| 状況 | 実行する処理 


 a| 
SVM 関係を初期化
 a| 
.. [* Operations] * > [* Initialize] をクリックします。
+
初期化（ Initialize ）ダイアログボックスが表示されます。

.. [Initialize （初期化） ] をクリックします




 a| 
SVM 関係を更新
 a| 
.. [* 操作 *>* 更新 *] をクリックします。
+
[ 更新（ Update ） ] ダイアログボックスが表示されます。

.. [ 更新（ Update ） ] をクリックします。




 a| 
デスティネーション SVM のアクティブ化デスティネーション SVM のアクティブ化では、スケジュールされた SnapMirror 転送の休止、実行中の SnapMirror 転送の中止、 SVM 関係の解除、デスティネーション SVM の起動が実行されます。
 a| 
.. Operations * > * Activate Destination SVM * をクリックします。
+
デスティネーション SVM のアクティブ化ダイアログボックスが表示されます。

.. 「 * OK 」を選択してデスティネーション SVM をアクティブ化し、関係を解除します * 。
.. [Activate （有効化） ] をクリックします




 a| 
ソース SVM からデータを再同期します。再同期処理では、 SVM 設定のベースラインが再設定されます。ソース SVM から再同期を実行して、 2 つの SVM 間で解除された関係を再確立できます。再同期が完了すると、デスティネーション SVM とソース SVM に同じ情報が格納され、デスティネーション SVM で以降の更新が予定されます。
 a| 
.. [* Operations] * > [* Resync from Source SVM* ] をクリックします。
+
ソース SVM から再同期（ Resync from Source SVM ）ダイアログボックスが表示されます。

.. 「 * OK 」を選択すると、デスティネーション SVM * にある新しいデータがすべて削除されます。
.. [* Resync] をクリックします。




 a| 
デスティネーション SVM からデータを再同期する（逆再同期）デスティネーション SVM からデータを再同期すると、 2 つの SVM 間に新しい関係を作成できます。この処理の実行中は、デスティネーション SVM がデータの提供を継続し、ソース SVM がデスティネーション SVM の設定とデータをバックアップします。
 a| 
.. Operations * > * Resync from Destination SVM （逆再同期） * をクリックします。
+
デスティネーション SVM からの再同期（逆再同期）ダイアログボックスが表示されます。

.. SVM に複数の関係がある場合は、「 * この SVM に複数の関係があります。他の関係を解除する * 」チェックボックスを選択します。
.. 「 * OK 」を選択して、ソース SVM * の新しいデータを削除します。
.. 逆再同期 * をクリックします。




 a| 
ソース SVM を再アクティブ化するソース SVM の再アクティブ化では、ソース SVM とデスティネーション SVM 間の SVM 関係の保護と再作成が行われます。SVM 関係を作成する際にソース SVM の設定をコピーするオプションを選択した場合は、デスティネーション SVM でデータの処理が中止されます。
 a| 
.. [* Operations] * > [* Reactivate Source SVM* ] をクリックします。
+
ソース SVM の再アクティブ化ダイアログボックスが表示されます。

.. デスティネーション SVM への再アクティブ化を開始するには、 * Initiate Reactivation * をクリックします。
.. [ 完了（ Done ） ] をクリックします。


|===

