---
permalink: online-help-96-97/task_provisioning_storage_by_creating_aggregate_manually.html 
sidebar: sidebar 
keywords: provision, storage, create, aggregate, manually, online, help, hdd, ssd, system, manager 
summary: HDD のみまたは SSD のみで構成されるアグリゲートは、 System Manager を使用して手動で作成できます。 
---
= System Manager - ONTAP 9.7 以前を使用してストレージをプロビジョニングするためのアグリゲートを手動で作成します
:icons: font
:imagesdir: ../media/


[role="lead"]
HDD のみまたは SSD のみで構成されるアグリゲートは、 ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して手動で作成できます。

ディスクはすべて同じサイズである必要があります。

.このタスクについて
* ONTAP Select で 4 ノードクラスタのアグリゲートを作成する場合、デフォルトではミラーアグリゲートのオプションが選択されます。
* ONTAP 9.0 以降では、ディスクサイズが 10TB 以上のアグリゲートを作成できます。
* アグリゲートディスクのディスクタイプが FSAS または MSATA で、ディスクサイズが 10TB 以上の場合、選択できる RAID タイプは RAID-TEC のみです。


.手順
. 次のいずれかの方法を使用してアグリゲートを作成します。
+
** [ * アプリケーションと階層 * > * ストレージ階層 * > * アグリゲートの追加 * ] をクリックします。
** [ * ストレージ * > * アグリゲートとディスク * > * アグリゲート * > * 作成 * ] をクリックします。


. アグリゲートを作成するには、 * アグリゲートを手動で作成 * オプションを有効にしてください。
. アグリゲートを作成するには、次の手順
+
.. アグリゲート名、ディスクタイプ、およびアグリゲートに含めるディスクまたはパーティションの数を指定します。
+
ディスクサイズが最大のディスクグループに対して、最小限のホットスペアのルールが適用されます。

.. アグリゲートの RAID 構成を変更します。
+
... [ 変更（ Change ） ] をクリックします。
... RAID 構成の変更ダイアログボックスで、 RAID タイプと RAID グループサイズを指定します。
+
共有ディスクでは、 RAID DP と RAID-TEC の 2 つの RAID タイプがサポートされます。

... [ 保存（ Save ） ] をクリックします。


.. アグリゲートをミラーする場合は、 [ このアグリゲートをミラーリングする * ] チェックボックスをオンにします。
+
MetroCluster 構成の場合、ミラーされていないアグリゲートは作成できません。したがって、 MetroCluster 構成では、ミラーリングオプションがデフォルトで有効になります。



. [ 作成（ Create ） ] をクリックします。


指定した構成でアグリゲートが作成され、アグリゲートウィンドウのアグリゲートのリストに追加されます。
