---
permalink: online-help-96-97/task_reverse_resynchronizing_snapmirror_relationships.html 
sidebar: sidebar 
keywords: reverse, resync, mirror, relationship, system, manager, online, help 
summary: System Manager を使用して、以前に解除したミラー関係を再確立できます。逆再同期操作を実行すると、ソースボリュームとデスティネーションボリュームの機能が入れ替わります。 
---
= ミラー関係を逆再同期しています
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して、以前に解除したミラー関係を再確立できます。逆再同期操作を実行すると、ソースボリュームとデスティネーションボリュームの機能が入れ替わります。

ソースボリュームはオンラインである必要があります。

.このタスクについて
* デスティネーションボリュームでデータを提供しながら、ソースボリュームを修理または交換したり、ソースボリュームを更新したり、システムの元の構成を再確立したりできます。
* 逆再同期を実行すると、ミラーソースの内容がデスティネーションボリュームの内容で上書きされます。
+
[NOTE]
====
** SnapLock 準拠ボリュームでは、アクティブファイルシステム内で共通の Snapshot コピーに関連するデータ変更は、現在のボリュームに設定されている有効期限まではロックされた Snapshot コピーに保持されます。
+
ボリュームの有効期限がすでに過ぎているか設定されていない場合は、 Snapshot コピーおよび共通の Snapshot コピーが 30 日間ロックされます。共通の Snapshot コピーからロックされた最新の Snapshot コピーまでの間の中間の Snapshot コピーはすべて削除されます。

** SnapLock Compliance ボリューム以外のボリュームでは、ベースの Snapshot コピーが作成されたあとにソースボリュームに書き込まれた新しいデータが原因によって失われる可能性があります。


====
* 逆再同期の実行時は、関係のミラーポリシーが DPDefault に設定され、ミラースケジュールが None に設定されます。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. 反転するミラー関係を選択します。
. [* Operations] * > [* Reverse Resync] をクリックします。
. 確認のチェックボックスをオンにし、 * 逆再同期 * をクリックします。


* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]
