---
permalink: online-help-96-97/task_creating_vault_relationship_from_destination_svm.html 
sidebar: sidebar 
keywords: system, manager, create, vault, relationship, destination, svm, online, help 
summary: System Manager を使用して、バックアップ関係をデスティネーション Storage Virtual Machine （ SVM ）から作成し、バックアップポリシーを割り当てて SnapVault を作成することができます。システムでデータの消失や破損が発生した場合、 SnapVault デスティネーションからバックアップデータをリストアできます。 
---
= デスティネーション SVM からバックアップ関係を作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して、バックアップ関係をデスティネーション Storage Virtual Machine （ SVM ）から作成し、バックアップポリシーを割り当てて SnapVault を作成することができます。システムでデータの消失や破損が発生した場合、 SnapVault デスティネーションからバックアップデータをリストアできます。

.作業を開始する前に
* ソースクラスタで ONTAP 8.2.2 以降が実行されている必要があります。
* ソースクラスタとデスティネーションクラスタの両方で SnapVault ライセンスまたは SnapMirror ライセンスが有効になっている必要があります。
+
[NOTE]
====
一部のプラットフォームでは、デスティネーションクラスタで SnapVault ライセンスまたは SnapMirror ライセンスに加えて DPO ライセンスが有効になっていれば、ソースクラスタで SnapVault ライセンスまたは SnapMirror ライセンスが有効になっていなくてもかまいません。

====
* ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。
* デスティネーション SVM の使用可能なスペースを確保する必要があります。
* ソースアグリゲートとデスティネーションアグリゲートはどちらも 64 ビットである必要があります。
* 読み書き可能（ rw ）タイプのソースボリュームを用意しておく必要があります。
* バックアップ（ XDP ）ポリシーが存在する必要があります。
+
バックアップポリシーが存在しない場合は、新規に作成するか、自動的に割り当てられるデフォルトのバックアップポリシー（ XDPDefault ）を使用する必要があります。

* FlexVol ボリュームがオンラインであり、読み取り / 書き込み可能である必要があります。
* SnapLock アグリゲートのタイプが同じである必要があります。
* ONTAP 9.2 以前のバージョンを実行しているクラスタから SAML 認証が有効になっているリモートクラスタに接続する場合は、リモートクラスタでパスワードベースの認証を有効にする必要があります。


.このタスクについて
* System Manager ではカスケード関係はサポートされません。
+
たとえば、関係のデスティネーションボリュームを別の関係のソースボリュームにすることはできません。

* MetroCluster 構成の同期元の SVM と同期先の SVM の間にバックアップ関係を作成することはできません。
* MetroCluster 構成の同期元の SVM 間にバックアップ関係を作成できます。
* 同期元の SVM のボリュームからデータ提供用の SVM のボリュームへのバックアップ関係を作成できます。
* データ提供用の SVM のボリュームから同期元の SVM のデータ保護（ DP ）ボリュームへのバックアップ関係を作成できます。
* バックアップ関係は、 SnapLock 以外のボリューム（プライマリ）と SnapLock のデスティネーションボリューム（セカンダリ）の間でのみ作成できます。
* 一度に保護できるボリュームは最大 25 個です。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. [ リレーションシップ *] ウィンドウで、 [ 作成 *] をクリックします。
. [* SVM を参照 * ] ダイアログボックスで、デスティネーションボリュームの SVM を選択します。
. [ 保護関係の作成 * （ Create Protection Relationship Relationship * ） ] ダイアログボックスで、 [ 関係タイプ * （ Relationship Type * ） ] ドロップダウンリストから [ * ボールト * （ * Vault * ） ] を選択する。
. クラスタ、 SVM 、およびソースボリュームを指定します。
+
指定したクラスタで ONTAP 9.3 より前のバージョンの ONTAP ソフトウェアが実行されている場合、ピア関係が設定された SVM だけが表示されます。指定したクラスタで ONTAP 9.3 以降が実行されている場合は、ピア関係が設定された SVM と許可された SVM が表示されます。

. ボリューム名サフィックスを入力します。
+
ボリューム名サフィックスをソースボリュームの名前に追加したものがデスティネーションボリュームの名前として使用されます。

. SnapLock ボリュームを作成する場合は、デフォルトの保持期間を指定します。
+
デフォルトの保持期間は、 1~70 年、または Infinite Volume の任意の値に設定できます。

. * 参照 * をクリックし、バックアップポリシーを変更します。
. 既存のスケジュールのリストから関係のスケジュールを選択します。
. バックアップ関係を初期化するには、 * Initialize Relationship * を選択します。
. SnapLock アグリゲートを有効にし、 SnapLock Compliance アグリゲートまたは SnapLock Enterprise アグリゲートを選択します。
. FabricPool 対応アグリゲートを有効にし、適切な階層化ポリシーを選択します。
. 選択したボリュームでラベルが一致するかどうかを確認するには、 * Validate * をクリックします。
. [ 作成（ Create ） ] をクリックします。


デスティネーションボリュームを作成するように選択した場合は、タイプが _dp_is のボリュームが次のデフォルト設定で作成されます。

* 自動拡張は有効になります。
* 重複排除はユーザの設定に応じて有効または無効になります。設定しない場合は、ソースボリュームの設定と同じになります。
* 圧縮は無効になります。
* 言語属性はソースボリュームと同じになります。


デスティネーションボリュームとソースボリュームの間のバックアップ関係が作成されます。関係を初期化するように選択した場合は、ベース Snapshot コピーがデスティネーションボリュームに転送されます。

* 関連情報 *

xref:reference_protection_window.adoc[保護ウィンドウ]
