---
permalink: online-help-96-97/task_creating_local_user_group.html 
sidebar: sidebar 
keywords: create, local, window, group, online, help, system, manager 
summary: System Manager を使用して Windows ローカルグループを作成し、 Storage Virtual Machine （ SVM ）に格納されたデータに SMB 接続経由でアクセスする際の認証に使用できます。また、管理アクティビティの実行時にグループのメンバーが利用できるユーザ権限と機能を定義した権限を割り当てることができます。 
---
= Windows ローカルグループを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して Windows ローカルグループを作成し、 Storage Virtual Machine （ SVM ）に格納されたデータに SMB 接続経由でアクセスする際の認証に使用できます。また、管理アクティビティの実行時にグループのメンバーが利用できるユーザ権限と機能を定義した権限を割り当てることができます。

SVM 用に CIFS サーバが設定されている必要があります。

.このタスクについて
* グループ名を指定する際、ローカルドメイン名は指定してもしなくてもかまいません。
+
ローカルドメインは SVM の CIFS サーバの名前です。たとえば、 SVM の CIFS サーバの名前が「 CIFS_SERVER 」で、「 engineering 」グループを作成する場合は、グループ名として「 engineering 」または「 CIFS_SERVER\engineering 」を指定できます。

+
ローカルドメインをグループ名の一部として使用する場合のルールを次に示します。

+
** 指定できるのは、グループを適用する SVM のローカルドメイン名だけです。
+
たとえば、ローカル CIFS サーバ名が「 cifs_server 」の場合、グループ名に「 CORP_SERVER\group1 」を指定することはできません。

** 「 BUILTIN 」をグループ名のローカルドメインとして使用することはできません。
+
たとえば、「 BUILTIN\group1 」という名前のグループは作成できません。

** Active Directory ドメインをグループ名のローカルドメインとして使用することはできません。
+
たとえば 'AD_DOM\group1 という名前のグループは作成できません "`AD_DOM`" は Active Directory ドメインの名前です



* すでに存在するグループ名は使用できません。
* 指定するグループ名は次の要件を満たす必要があります。
+
** 256 文字以内にする必要があります
** 末尾をピリオドにすることはできません
** カンマは使用できません
** 次の印字可能文字を含めることはできません： " / \ [ ] ： | <> + = ；？* @
** ASCII 範囲 1~31 の印字できない文字を含めることはできません




.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Host Users and Groups* （ホストユーザーとグループ * ） ] ペインで、 [* Windows* ] をクリックします。
. [* グループ *] タブで、 [* 作成 *] をクリックします。
. [ グループの作成 * ] ダイアログボックスで、グループの名前と、新しいグループの識別に役立つ概要を指定します。
. グループに一連の権限を割り当てます。
+
サポートされる定義済みの権限の中から選択できます。

. [Add *] をクリックして、ユーザをグループに追加します。
. [ グループへのメンバーの追加 *] ダイアログボックスで、次のいずれかの操作を実行します。
+
** 特定のローカルグループに追加する Active Directory ユーザまたは Active Directory グループを指定します。
** SVM の使用可能なローカルユーザのリストからユーザを選択します。
** [OK] をクリックします。


. [ 作成（ Create ） ] をクリックします。


Windows ローカルグループが作成され、 [ グループ ] ウィンドウに表示されます。

* 関連情報 *

xref:reference_windows_window.adoc[Windows ウィンドウ]
