---
permalink: online-help-96-97/task_creating_node_management_logical_interface.html 
sidebar: sidebar 
keywords: system, manager, create, node, management, logical, interface, online, help 
summary: System Manager を使用して、クラスタ内の特定のノードを管理するための専用のノード管理論理インターフェイス（ LIF ）を作成できます。この LIF は、ノードのシステムメンテナンスを管理するために使用できます。 
---
= ノード管理論理インターフェイスを作成します
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して、クラスタ内の特定のノードを管理するための専用のノード管理論理インターフェイス（ LIF ）を作成できます。この LIF は、ノードのシステムメンテナンスを管理するために使用できます。

.手順
. [ * Configuration * ] > [* Cluster*] > [* Configuration Updates* ] をクリックします。
. ノード * タブで、ノード管理 LIF を作成するノードを選択し、 * ノード管理 LIF の作成 * をクリックします。
. Create Node-Management LIF * ダイアログボックスで、ノード管理 LIF の名前を指定します。
. ノード管理 LIF に IP アドレスを割り当てます。
+
|===
| 状況 | 作業 


 a| 
サブネットを使用して IP アドレスを指定します
 a| 
.. サブネットを使用する * を選択します。
.. Add Details ダイアログボックスで、 IP アドレスを割り当てるサブネットを選択します。
+
クラスタ間 LIF の場合、選択した IPspace に関連付けられているサブネットだけが表示されます。

.. LIF に特定の IP アドレスを割り当てる場合は、「 * 特定の IP アドレスを使用する * 」を選択して、 IP アドレスを入力します。
+
指定した IP アドレスがサブネット内にない場合、追加されます。

.. [OK] をクリックします。




 a| 
サブネットを使用せずに手動で IP アドレスを指定します
 a| 
.. サブネットなし * を選択します。
.. [ 詳細の追加 ] ダイアログボックスで、次の手順を実行します。
+
... IP アドレスとネットワークマスクまたはプレフィックスを指定します。
... オプション：ゲートウェイを指定します。
... Destination フィールドにデフォルト値を使用しない場合は、新しい宛先値を指定します。
+
値を指定しない場合は、 IP アドレスファミリーに基づいてデフォルト値が Destination フィールドに入力されます。



+
ルートが存在しない場合は、ゲートウェイとデスティネーションに基づいて新しいルートが自動的に作成されます。

.. [OK] をクリックします。


|===
. ポートの詳細 * 領域から必要なポートを選択します。
. [ 作成（ Create ） ] をクリックします。




== 次に何をするか

既存のノード管理 LIF を削除する場合は、コマンドラインインターフェイス（ CLI ）を使用する必要があります。
