---
permalink: online-help-96-97/task_provisioning_storage_by_creating_flash_pool_aggregate_manually.html 
sidebar: sidebar 
keywords: provision, system, manager, storage, create, flash, pool, aggregate, manually, online, help, hdd 
summary: System Manager を使用して、 Flash Pool アグリゲートを手動で作成したり、既存の HDD アグリゲートに SSD を追加して Flash Pool アグリゲートに変換したりできます。新しい HDD アグリゲートを作成する場合、 SSD キャッシュをプロビジョニングして、 Flash Pool アグリゲートを作成できます。 
---
= System Manager - ONTAP 9.7 以前を使用して、ストレージをプロビジョニングし、 Flash Pool アグリゲートを手動で作成します
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager クラシック（ ONTAP 9.7 以前で使用可能）を使用して、 Flash Pool アグリゲートを手動で作成したり、 SSD を追加して既存の HDD アグリゲートを Flash Pool アグリゲートに変換したりできます。新しい HDD アグリゲートを作成する場合、 SSD キャッシュをプロビジョニングして、 Flash Pool アグリゲートを作成できます。

.作業を開始する前に
* Flash Pool アグリゲートの SSD 層のサイズと構成について、プラットフォームとワークロードそれぞれに固有なベストプラクティスに注意する必要があります。
* すべての HDD を初期化する必要があります。
* アグリゲートに SSD を追加する場合は、既存の SSD と専用の SSD がすべて同じサイズである必要があります。


.このタスクについて
* Flash Pool アグリゲートの作成にはパーティショニングされた SSD は使用できません。
* キャッシュソースがストレージプールの場合、アグリゲートをミラーすることはできません。
* ONTAP 9.0 以降では、ディスクサイズが 10TB 以上のアグリゲートを作成できます。
* アグリゲートディスクのディスクタイプが FSAS または MSATA で、ディスクサイズが 10TB 以上の場合、 RAID-TEC のみを使用できます。


.手順
. 次のいずれかの方法を使用してアグリゲートを作成します。
+
** [ * アプリケーションと階層 * > * ストレージ階層 * > * アグリゲートの追加 * ] をクリックします。
** [ * ストレージ * > * アグリゲートとディスク * > * アグリゲート * > * 作成 * ] をクリックします。


. アグリゲートを作成するには、 * アグリゲートを手動で作成 * オプションを有効にしてください。
. アグリゲートの作成 * ウィンドウで、アグリゲート名、ディスクタイプ、およびアグリゲートに HDD を含めるディスクまたはパーティションの数を指定します。
. アグリゲートをミラーする場合は、 [ このアグリゲートをミラーリングする * ] チェックボックスをオンにします。
+
MetroCluster 構成の場合、ミラーされていないアグリゲートは作成できません。したがって、 MetroCluster 構成では、ミラーリングオプションがデフォルトで有効になります。

. [ * このアグリゲートで Flash Pool キャッシュを使用する * ] をクリックします。
. キャッシュソースを指定します。
+
|===
| キャッシュソース | 作業 


 a| 
ストレージプール
 a| 
.. キャッシュソースとして * ストレージプール * を選択します。
.. キャッシュを提供するストレージプールを選択し、キャッシュサイズを指定します。
.. 必要に応じて RAID タイプを変更します。




 a| 
専用 SSD
 a| 
.. キャッシュソースとして専用 SSD * を選択します。
.. アグリゲートに含める SSD のサイズと数を選択します。
.. 必要に応じて RAID 構成を変更します。
+
... [ 変更（ Change ） ] をクリックします。
... RAID 構成の変更ダイアログボックスで、 RAID タイプと RAID グループサイズを指定します。
... [ 保存（ Save ） ] をクリックします。




|===
. [ 作成（ Create ） ] をクリックします。


指定した構成で Flash Pool アグリゲートが作成され、アグリゲートウィンドウのアグリゲートのリストに追加されます。

* 関連情報 *

xref:concept_how_storage_pool_works.adoc[ストレージプールの仕組み]

http://www.netapp.com/us/media/tr-4070.pdf["ネットアップテクニカルレポート 4070 ：『 Flash Pool Design and Implementation 』"^]
