---
permalink: online-help-96-97/task_enabling_saml_authentication.html 
sidebar: sidebar 
keywords: system, manager, enable, saml, authentication, idp, security, markup, language, secure, identity, provide, online, help 
summary: System Manager では、セキュアなアイデンティティプロバイダ（ IdP ）を使用してリモートユーザがログインできるように、 Security Assertion Markup Language （ SAML ）認証を設定できます。 
---
= SAML 認証の有効化
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager では、セキュアなアイデンティティプロバイダ（ IdP ）を使用してリモートユーザがログインできるように、 Security Assertion Markup Language （ SAML ）認証を設定できます。

.作業を開始する前に
* リモート認証に使用する IdP を設定する必要があります。
+
[NOTE]
====
設定済みの IdP から提供されたドキュメントを参照してください。

====
* IdP の URI が必要です。


System Manager で検証済みの IdP は、 Shibboleth および Active Directory フェデレーションサービスです。

[NOTE]
====
SAML 認証を有効にした場合、 System Manager の GUI にアクセスできるのはリモートユーザだけです。ローカルユーザは、 SAML 認証を有効にしたあとで System Manager GUI にアクセスできません。

====
.手順
. [ * Configuration * ] > [* Cluster *] > [* Authentication *] をクリックします。
. Enable SAML authentication * チェックボックスをオンにします。
. SAML 認証を使用するように System Manager を設定します。
+
.. IdP の URI を入力します。
.. ホストシステムの IP アドレスを入力します。
.. 必要に応じて、ホストシステムの証明書を変更します。


. [* Retrieve Host Metadata* （ホストメタデータの取得） ] をクリックして、ホスト URI とホストメタデータの情報を取得します。
. ホスト URI またはホストメタデータの詳細をコピーし、 IdP にアクセスして、ホスト URI またはホストメタデータの詳細と信頼ルールを IdP ウィンドウで指定します。
+
[NOTE]
====
設定済みの IdP から提供されたドキュメントを参照してください。

====
. [ 保存（ Save ） ] をクリックします。
+
IdP のログインウィンドウが表示されます。

. IdP のログインウィンドウを使用して System Manager にログインします。
+
IdP の設定後にユーザが完全修飾ドメイン名（ FQDN ）、 IPv6 、またはクラスタ管理 LIF を使用してログインしようとすると、 IdP の設定で指定したホストシステムの IP アドレスに IP アドレスが自動的に変更されます。



* 関連情報 *

xref:task_accessing_cluster_by_using_system_manager_brower_based_gui.adoc[ONTAP System Manager のブラウザベースのグラフィカルインターフェイスを使用したクラスタへのアクセス]
