---
permalink: online-help-96-97/task_creating_local_windows_user_accounts.html 
sidebar: sidebar 
keywords: create, local, windows, user, account, online, help, system, manager, svm, cifs 
summary: System Manager を使用して Windows ローカルユーザアカウントを作成し、 Storage Virtual Machine （ SVM ）に格納されたデータに SMB 接続経由でアクセスする際の認証に使用できます。Windows ローカルユーザアカウントは、 CIFS セッションを作成する際の認証にも使用できます。 
---
= Windows ローカルユーザアカウントを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して Windows ローカルユーザアカウントを作成し、 Storage Virtual Machine （ SVM ）に格納されたデータに SMB 接続経由でアクセスする際の認証に使用できます。Windows ローカルユーザアカウントは、 CIFS セッションを作成する際の認証にも使用できます。

.作業を開始する前に
* SVM 用に CIFS サーバが設定されている必要があります。


Windows ローカルユーザの名前は次の要件を満たす必要があります。

* 20 文字以内にする必要があります
* 末尾をピリオドにすることはできません
* カンマは使用できません
* 次の印字可能文字を含めることはできません： " / \ [ ] ： | <> + = ；？* @
* ASCII 範囲 1~31 の印字できない文字を含めることはできません


パスワードは次の基準を満たしている必要があります。

* 6 文字以上にする必要があります
* ユーザアカウント名を含めることはできません
* 次の 4 種類のうちの 3 種類以上の文字を含める必要があります。
+
** 大文字のアルファベット（ A~Z ）
** 小文字のアルファベット（ a~z ）
** 数字（ 0~9 ）
** 特殊文字： ~ ！@#0^&*_-+=`\|()[]:;"<> 、 .？/




.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Host Users and Groups* （ホストユーザーとグループ * ） ] ペインで、 [* Windows* ] をクリックします。
. [*Users*] タブで、 [*Create] をクリックします。
. ローカルユーザの名前を指定します。
. ローカルユーザのフルネームとこの新しいユーザの特定に役立つ概要を指定します。
. ローカルユーザのパスワードを入力し、確認のためにもう一度入力します。
+
パスワードの要件を満たしている必要があります。

. [Add *] をクリックして、グループメンバーシップをユーザに割り当てます。
. Add Groups * ウィンドウで、 SVM 内の使用可能なグループのリストからグループを選択します。
. ユーザー作成後にこのアカウントを無効にするには、 * このアカウントを無効にする * を選択します。
. [ 作成（ Create ） ] をクリックします。


Windows ローカルユーザアカウントが作成され、選択したグループのメンバーシップが割り当てられます。ユーザーアカウントは、 *Users* タブに表示されます。

* 関連情報 *

xref:reference_windows_window.adoc[Windows ウィンドウ]
