---
permalink: online-help-96-97/task_providing_cache_by_adding_ssd_disks.html 
sidebar: sidebar 
keywords: provision, cache, aggregate, add, ssd, system, manager, storage, pool 
summary: System Manager でストレージプールまたは専用 SSD を追加してキャッシュをプロビジョニングするには、パーティションに分割されたディスクを含まないルート以外の既存の HDD アグリゲートまたはルートアグリゲートを Flash Pool アグリゲートに変換します。 
---
= SSD の追加によるアグリゲートへのキャッシュのプロビジョニング
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager でストレージプールまたは専用 SSD を追加してキャッシュをプロビジョニングするには、パーティションに分割されたディスクを含まないルート以外の既存の HDD アグリゲートまたはルートアグリゲートを Flash Pool アグリゲートに変換します。

.作業を開始する前に
* アグリゲートがオンラインになっている必要があります。
* キャッシュディスクとして割り当てることができる十分な数のスペア SSD または割り当て単位がストレージプールに必要です。
* クラスタ内のすべてのノードで ONTAP 8.3 以降が実行されている必要があります。
+
クラスタに複数のバージョンが混在している場合は、コマンドラインインターフェイスを使用して Flash Pool アグリゲートを作成し、 SSD キャッシュをプロビジョニングしてください。

* Flash Pool アグリゲートに変換できる、 HDD で構成された、ルートではない有効な 64 ビットのアグリゲートを特定しておく必要があります。
* アレイ LUN を含むアグリゲートは使用できません。


Flash Pool アグリゲートの SSD 層のサイズと構成について、プラットフォームとワークロードそれぞれに固有なベストプラクティスに注意する必要があります。

.手順
. 次のいずれかの方法を選択します。
+
** [* アプリケーションと階層 *>* ストレージ階層 *] をクリックします。
** Storage * > * Aggregates & Disks * > * Aggregates * の順にクリックします


. [ * ストレージ階層 * ] ウィンドウでアグリゲートを選択し、 [ * その他の操作 * > * キャッシュの追加 * ] をクリックします。
+
[NOTE]
====
キャッシュの追加は FabricPool 対応アグリゲートではサポートされません。

====
. [ キャッシュの追加 *] ダイアログボックスで、適切なアクションを実行します。
+
|===
| 選択したキャッシュソース | 手順 


 a| 
ストレージプール
 a| 
.. キャッシュを提供するストレージプールを選択します。
.. キャッシュサイズを指定します。
.. 必要に応じて RAID タイプを変更します。




 a| 
専用 SSD
 a| 
使用する SSD のサイズと数を選択し、必要に応じて RAID 構成を変更します。

.. [ 変更（ Change ） ] をクリックします。
.. RAID 構成の変更ダイアログボックスで、 RAID タイプと RAID グループサイズを指定し、 * 保存 * をクリックします。


|===
. [ 追加（ Add ） ] をクリックします。
+
ミラーされたアグリゲートの場合、 Add Cache （キャッシュの追加）ダイアログボックスに、選択した数の 2 倍のディスクが追加されることを示す情報が表示されます。

. [ キャッシュの追加 *] ダイアログボックスで、 [ はい *] をクリックします。


選択したアグリゲートにキャッシュディスクが追加されます。

* 関連情報 *

http://www.netapp.com/us/media/tr-4070.pdf["ネットアップテクニカルレポート 4070 ：『 Flash Pool Design and Implementation 』"^]
