---
permalink: online-help-96-97/task_creating_svm_peers.html 
sidebar: sidebar 
keywords: create, svm, peers, relationship, data, protection, online, help 
summary: SVM ピアリングを使用すると、データ保護のために 2 つの Storage Virtual Machine （ SVM ）間のピア関係を確立できます。 
---
= SVM ピアを作成
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM ピアリングを使用すると、データ保護のために 2 つの Storage Virtual Machine （ SVM ）間のピア関係を確立できます。

ピア関係を確立する SVM が配置されたクラスタ間でピア関係を作成しておく必要があります。

.このタスクについて
* ターゲットクラスタとして選択できるクラスタは、 SVM ピアを作成する際に * Configuration * > * SVM peers * ウィンドウに表示されます。
* ターゲット SVM が ONTAP 9.2 以前を実行するシステムのクラスタにある場合、 System Manager を使用して SVM ピアリングを承認することはできません。
+
[NOTE]
====
この場合は、コマンドラインインターフェイス（ CLI ）を使用して SVM ピアリングを承認します。

====


.手順
. イニシエータ SVM を選択します。
. 許可される SVM のリストからターゲット SVM を選択します。
. ターゲット SVM の名前を入力します。 * Enter an SVM * field 。
+
[NOTE]
====
ナビゲート方法として * Configuration * > * SVM peers * ウィンドウがある場合は、ピアクラスタのリストからターゲット SVM を選択する必要があります。

====
. SVM ピアリングを開始します。
+
|===
| 状況 | 手順 


 a| 
イニシエータクラスタから SVM ピアリングを開始します
 a| 
SVM ピアリングの開始をクリックします。



 a| 
リモートクラスタからの SVM ピアリングを承認します
 a| 
[NOTE]
====
許可されていない SVM に該当します

====
.. リモートクラスタの管理アドレスを指定します。
.. * 管理 URL * リンクをクリックして、リモートクラスタの SVM ピアウィンドウにアクセスします。
.. リモートクラスタで、 * Pending SVM Peer * 要求を承認します。
.. イニシエータクラスタにアクセスし、 * ピアリングの検証 * をクリックします。


|===
. [* Continue （続行） ] をクリックします




== 次に何をするか

クラスタ間 LIF 、クラスタピア関係、および SVM ピア関係は、概要ウィンドウで確認できます。

System Manager を使用してピア関係を作成する場合、暗号化ステータスはデフォルトで「 enabled 」になります。
