---
permalink: online-help-96-97/task_creating_qos_policy_groups.html 
sidebar: sidebar 
keywords: online, help, create, qos, policy, groups, system, manager, quality, service 
summary: System Manager でストレージ QoS ポリシーグループを作成して、ワークロードのスループットを制限したり、ワークロードのパフォーマンスを監視したりすることができます。 
---
= QoS ポリシーグループを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager でストレージ QoS ポリシーグループを作成して、ワークロードのスループットを制限したり、ワークロードのパフォーマンスを監視したりすることができます。

.手順
. [ * ストレージ * > * SVMs * ] をクリックします。
. SVM を選択し、 * SVM 設定 * をクリックします。
. [* Policies] ペインで、 [* QoS Policy Groups] をクリックします。
. [* QoS ポリシーグループ *] ウィンドウで、 [*Create] をクリックします。
. [ ポリシーグループの作成 *] ダイアログボックスで、ポリシーのグループ名を指定します。
. 最小スループット制限を指定します。
+
** System Manager 9.5 では、パフォーマンスがオールフラッシュで最適化されている場合にのみ最小スループット制限を設定できます。System Manager 9.6 では、 ONTAP Select Premium システムにも最小スループット制限を設定できます。
** FabricPool 対応アグリゲートでは、ボリュームの最小スループット制限を設定することはできません。
** 最小スループット値を指定しない場合、または最小スループット値が 0 に設定されている場合は、自動的に「なし」という値が表示されます。
+
この値では大文字と小文字が区別されます。



. 最大スループット制限を指定します。
+
** 最小スループット制限と最大スループット制限の単位は同じにする必要があります。
** 最小スループット制限を指定しない場合は、 IOPS 、 B/ 秒、 KB/ 秒、 MB/ 秒などの単位で最大スループット制限を設定できます。
** 最大スループット制限を指定しない場合は、自動的に「無制限」という値が表示されます。
+
この値では大文字と小文字が区別されます。指定した単位は無視されます。



. [OK] をクリックします。

