---
permalink: online-help-96-97/task_creating_mirror_vault_relationship_from_destination_svm.html 
sidebar: sidebar 
keywords: system, manager, create, mirror, vault, relationship, destination, svm, online, help 
summary: System Manager を使用して、ミラーとバックアップ関係をデスティネーション Storage Virtual Machine （ SVM ）から作成することができます。この関係を作成すると、ソースボリュームからデスティネーションボリュームにデータを定期的に転送して、データの保護を強化できます。また、ソースボリュームのバックアップを作成して、データを長期にわたって保持することもできます。 
---
= デスティネーション SVM からミラーとバックアップ関係を作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
System Manager を使用して、ミラーとバックアップ関係をデスティネーション Storage Virtual Machine （ SVM ）から作成することができます。この関係を作成すると、ソースボリュームからデスティネーションボリュームにデータを定期的に転送して、データの保護を強化できます。また、ソースボリュームのバックアップを作成して、データを長期にわたって保持することもできます。

.作業を開始する前に
* デスティネーションクラスタで ONTAP 8.3.2 以降が実行されている必要があります。
* ソースクラスタとデスティネーションクラスタで SnapMirror ライセンスが有効になっている必要があります。
+
[NOTE]
====
一部のプラットフォームでは、デスティネーションクラスタで SnapMirror ライセンスに加えて Data Protection Optimization （ DPO ）ライセンスが有効になっていれば、ソースクラスタで SnapMirror ライセンスが有効になっていなくてもかまいません。

====
* ソースクラスタとデスティネーションクラスタで正常なピア関係が確立されている必要があります。
* デスティネーション SVM の使用可能なスペースを確保する必要があります。
* ソースアグリゲートとデスティネーションアグリゲートはどちらも 64 ビットである必要があります。
* 読み書き可能（ rw ）タイプのソースボリュームを用意しておく必要があります。
* SnapLock アグリゲートのタイプが同じである必要があります。
* ONTAP 9.2 以前のバージョンを実行しているクラスタから SAML 認証が有効になっているリモートクラスタに接続する場合は、リモートクラスタでパスワードベースの認証を有効にする必要があります。


.このタスクについて
* System Manager ではカスケード関係はサポートされません。
+
たとえば、関係のデスティネーションボリュームを別の関係のソースボリュームにすることはできません。

* MetroCluster 構成の同期元の SVM と同期先の SVM の間には、ミラーとバックアップ関係を作成することはできません。
* MetroCluster 構成の同期元の SVM 間には、ミラーとバックアップ関係を作成できます。
* 同期元の SVM のボリュームからデータ提供用の SVM のボリュームへのミラーとバックアップ関係を作成できます。
* データ提供用の SVM から同期元の SVM の DP ボリュームへのミラーとバックアップ関係を作成できます。
* 一度に保護できるボリュームは最大 25 個です。


.手順
. [* 保護 *>] 、 [* ボリューム関係 *] の順にクリックします。
. [ リレーションシップ *] ウィンドウで、 [ 作成 *] をクリックします。
. [* SVM を参照 * ] ダイアログボックスで、デスティネーションボリュームの SVM を選択します。
. [ 保護関係の作成 * （ Create Protection Relationship Relationship * ） ] ダイアログボックスで、 [ 関係タイプ * （ Relationship Type * ） ] ドロップダウンリストから [ * ミラーとバックアップ * （ * Mirror and Vault * ） ] を選択する。
. クラスタ、 SVM 、およびソースボリュームを指定します。
+
指定したクラスタで ONTAP 9.3 より前のバージョンの ONTAP ソフトウェアが実行されている場合、ピア関係が設定された SVM だけが表示されます。指定したクラスタで ONTAP 9.3 以降が実行されている場合は、ピア関係が設定された SVM と許可された SVM が表示されます。

. ボリューム名サフィックスを入力します。
+
ボリューム名サフィックスをソースボリュームの名前に追加したものがデスティネーションボリュームの名前として使用されます。

. 参照（ * Browse ）をクリックし、ミラーとバックアップポリシーを変更します。
+
ソースボリュームに関連付けられた Snapshot ポリシーと最も多くのラベルが一致するポリシーを選択できます。

. 既存のスケジュールのリストから関係のスケジュールを選択します。
. 関係を初期化するには、「関係の初期化」を選択してください。
. FabricPool 対応アグリゲートを有効にし、適切な階層化ポリシーを選択します。
. 選択したボリュームでラベルが一致するかどうかを確認するには、 * Validate * をクリックします。
. [ 作成（ Create ） ] をクリックします。

