---
permalink: online-help-96-97/task_changing_raid_group_when_adding_capacity_disks.html 
sidebar: sidebar 
keywords: change, raid, group, add, capacity, disk, online, help, hdd 
summary: アグリゲートにデータディスク（ HDD ）を追加するときに、ディスクを追加する RAID グループを System Manager で変更することができます。 
---
= System Manager - ONTAP 9.7 以前を使用してデータディスクを追加する場合は、 RAID グループを変更してください
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アグリゲートにデータディスク（ HDD ）を追加するときに、 ONTAP System Manager クラシック（ ONTAP 9.7 以前でサポート）を使用して、ディスクを追加する RAID グループを変更できます。

.このタスクについて
* RAID タイプが RAID-DP であり、 FSAS または MSATA タイプのディスクをサイズが 10TB 以上の場合、それらを追加できるのは「特別な RAID グループ」のみで、「新規 RAID グループ」または「すべての RAID グループ」には追加できません。
+
これらのディスクは、既存のアグリゲートのサイズにダウンサイズされて追加されます。

* RAID グループが RAID-TEC の場合 'FSAS または MSATA タイプのディスクを 10 TB 以上のサイズで追加する場合は ' すべての RAID グループ ' 新しい RAID グループ ' および特別な RAID グループに追加できます
+
これらのディスクは、既存のアグリゲートのサイズにダウンサイズされて追加されます。



.手順
. 次のいずれかの方法を選択します。
+
** [* アプリケーションと階層 *>* ストレージ階層 *] をクリックします。
** Storage * > * Aggregates & Disks * > * Aggregates * の順にクリックします


. 「 * ストレージ階層 * 」ウィンドウで、データディスクを追加するアグリゲートを選択し、メニューをクリックします。その他の操作 [ 容量の追加 ] 。
. [ 容量の追加 *] ダイアログボックスで、次の手順を実行します。
+
.. [ 変更（ Change ） ] をクリックします。
.. RAID 構成の変更 * ダイアログボックスで、データディスクを追加する RAID グループを指定します。
+
デフォルト値「 All RAID groups 」を「 S pecSpecific RAID group 」または「 New RAID group 」に変更できます。

.. [ 保存（ Save ） ] をクリックします。



