---
permalink: nfs-config-esxi/reference_where_to_find_additional_information.html 
sidebar: sidebar 
keywords: successful, test, nfs, client, access, configuration, san, protocol, complete, protect, root, volume, comprehensive, technical, report, goal, where to find additional information 
summary: NFS クライアントアクセスをテストしたあと、 NFS の追加設定を行ったり、 SAN アクセスを追加したりできます。プロトコルアクセスが完了したら、のルートボリュームを保護する必要があります。これらの目標の達成に役立つ包括的なコンテンツとテクニカルレポートをご用意しています。 
---
= 追加情報の参照先
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS クライアントアクセスをテストしたあと、 NFS の追加設定を行ったり、 SAN アクセスを追加したりできます。プロトコルアクセスが完了したら、のルートボリュームを保護する必要があります。これらの目標の達成に役立つ包括的なコンテンツとテクニカルレポートをご用意しています。



== NFS の設定

NFS アクセスについてさらに詳しく設定するには、以下のコンテンツおよびテクニカルレポートを参照してください。

* https://docs.netapp.com/us-en/ontap/nfs-config/index.html["NFS の設定"^]
+
CLI コマンドを使用して、新しいボリュームまたは qtree に格納されているファイルへの NFS クライアントアクセスを設定する高度な方法について説明します。

* https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS の管理"^]
+
認証、許可、セキュリティなど、 NFS プロトコルを使用したファイルアクセスを管理する方法について説明しています。

* http://www.netapp.com/us/media/tr-4597.pdf["ネットアップテクニカルレポート 4597 ：『 VMware vSphere with ONTAP 』"^]
+
ONTAP および VMware vSphere のサーバ仮想化環境を使用する際のベストプラクティスを紹介しています。

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["ネットアップテクニカルレポート 4668 ：『 Name Services Best Practices 』"^]
+
LDAP 、 NIS 、 DNS 、およびローカルユーザ / グループファイルを認証用に設定する際の、ベストプラクティス、制限、推奨事項、および考慮事項をまとめています。

* http://www.netapp.com/us/media/tr-4067.pdf["ネットアップテクニカルレポート 4067 ：『 NFS Best Practice and Implementation 』"^]
+
NFSv4 に焦点を当てて ONTAP の概要を説明しています。





== ルートボリュームの保護

SVM でプロトコルを設定したら、ルートボリュームを保護してください。

* https://docs.netapp.com/us-en/ontap/data-protection/index.html["データ保護"^]
+
負荷共有ミラーを作成してルートボリュームを保護する方法について説明しています。これは、 NAS 対応の SVM に対するネットアップのベストプラクティスです。また、 SVM ルートボリュームを負荷共有ミラーから昇格させてボリュームの障害や消失からリカバリする簡単な方法についても説明しています。


