---
permalink: fc-config-rhel/index.html 
sidebar: sidebar 
keywords: quick, set, up, fc, service, storage, virtual, machine, svm, provision, lun, fc, host, bus, adapter, hba, red, hat, enterprise, linux, server, configuration 
summary: このコンテンツでは、 Storage Virtual Machine に FC サービスをセットアップし、 LUN をプロビジョニングし、 Red Hat Enterprise Linux サーバで FC ホストバスアダプタを使用して LUN を使用できるように設定するまでの簡単な方法について説明しています。 
---
= Red Hat Enterprise Linux 向けの FC の設定の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
このコンテンツでは、 Storage Virtual Machine （ SVM ）に FC サービスをセットアップし、 LUN をプロビジョニングし、 Red Hat Enterprise Linux サーバで FC ホストバスアダプタ（ HBA ）を使用して LUN を使用できるように設定するまでの簡単な方法について説明しています。

このコンテンツは、次の前提に基づいています。

* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
* 背景にある概念について詳しく確認する必要はありません。
* ONTAP 9.7 以降では、 ONTAP システムマネージャ UI ではなく、 ONTAP 9.7 以前のリリースで _Classic_System Manager UI を使用する場合。
+
https://docs.netapp.com/us-en/ontap/["ONTAP System Manager のドキュメント"^]

* ホストで Red Hat Enterprise Linux 6.4 以降のサポート対象バージョンが実行されている。
* 従来の FC HBA およびスイッチを使用している。
+
この内容は、 Fibre Channel over Ethernet （ FCoE ）には対応していません。

* クラスタの各ノードに使用可能な FC ターゲットポートが少なくとも 2 つある。
+
オンボード FC および UTA2 （別名「 CNA 」）ポート、および一部のアダプタは設定が可能です。これらのポートは ONTAP のコマンドラインインターフェイス（ CLI ）で設定しますが、本書では説明しません。

* FC SAN ブートを設定しない。


上記の想定条件に該当しない場合は、次の資料を参照してください。

* https://docs.netapp.com/us-en/ontap/san-admin/index.html["SAN 管理"^]
* https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN の設定"^]
* https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html["Linux Unified Host Utilities 7.1 のインストール"^]

