---
permalink: iscsi-config-rhel/index.html 
sidebar: sidebar 
keywords: iscsi, service, storage, virtual, machine, svm, lun, initiator, red, hat, enterprise, linux, server, configuration, configuration 
summary: このコンテンツでは、 Storage Virtual Machine に iSCSI サービスをセットアップし、 LUN をプロビジョニングし、 Red Hat Enterprise Linux サーバで iSCSI イニシエータを使用して LUN を使用できるように設定するまでの簡単な方法について説明しています。 
---
= Red Hat Enterprise Linux 向けの iSCSI の設定の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
このコンテンツでは、 Storage Virtual Machine （ SVM ）に iSCSI サービスをセットアップし、 LUN をプロビジョニングし、 Red Hat Enterprise Linux サーバで iSCSI イニシエータを使用して LUN を使用できるように設定するまでの簡単な方法について説明しています。

このコンテンツは、次の前提に基づいています。

* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
* 背景にある概念について詳しく確認する必要はありません。
* ONTAP 9.7 以降では、 ONTAP システムマネージャ UI ではなく、 ONTAP 9.7 以前のリリースで _Classic_System Manager UI を使用する場合。
+
https://docs.netapp.com/us-en/ontap/["ONTAP System Manager のドキュメント"^]

* RHEL シリーズ 6.4 以降のサポート対象バージョンを実行している Red Hat Enterprise Linux ホストで iSCSI ソフトウェアイニシエータを使用している。
* ネットワークで IPv4 アドレスを使用している。
* 次のいずれかの方法で論理インターフェイスにアドレスを割り当てる。
+
** 定義したサブネットから自動で割り当てられます
** 既存のサブネットから選択したアドレスを使用して、手動で割り当てます
** 既存のサブネットに追加するアドレスを使用して、手動で割り当てます


* iSCSI SAN ブートを設定しない。


上記の想定条件に該当しない場合は、次の資料を参照してください。

* https://docs.netapp.com/us-en/ontap/san-admin/index.html["SAN 管理"^]
* https://docs.netapp.com/us-en/ontap/san-config/index.html["SAN の設定"^]
* https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html["Linux Unified Host Utilities 7.1 のインストール"^]

