---
permalink: volume-move/index.html 
sidebar: sidebar 
keywords: nondisruptive, data, volume, node, storage, virtual, machine, svm, ontap, cluster, volume move overview, move, overview 
summary: このコンテンツを使用すると、 ONTAP 9 クラスタの同じ Storage Virtual Machine （ SVM ）内のノード間で、データボリュームを無停止で移動できます。 
---
= ボリューム移動の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
このコンテンツを使用すると、 ONTAP 9 クラスタの同じ Storage Virtual Machine （ SVM ）内のノード間で、データボリュームを無停止で移動できます。



== このコンテンツを使用するための要件

このコンテンツを使用する前に、次の条件を満たしていることを確認してください。

* クラスタで ONTAP 9 を実行している。
* クラスタ管理者の権限が必要です。
* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
* 背景にある概念について詳しく確認する必要はありません。
* System Manager を使用する。
+
一部のタスクでは、 ONTAP コマンドラインインターフェイス（ CLI ）を使用する必要があります。

* ONTAP 9.7 以降では、 ONTAP システムマネージャ UI ではなく、 ONTAP 9.7 以前のリリースで _Classic_System Manager UI を使用する場合。
+
https://docs.netapp.com/us-en/ontap/["ONTAP System Manager のドキュメント"^]

* 移動するボリュームがわかっている。
+
移動するボリュームを決定する際には、 Active IQ Unified Manager （旧 OnCommand Unified Manager ）を使用できます。

* 移動するボリュームはデータボリュームです。
* 新規または転用するハードウェアの設置が完了しており、すでにアグリゲートがある。
* クラスタに LUN がある場合、すべてのノードから LUN ごとにパスが 2 つ確保されている。
* クラスタネットワークポートでフロー制御が有効になっていません。
* ボリュームにネームスペースが含まれている場合、クラスタで ONTAP 9.6 以降が実行されている。
+
ONTAP 9.5 を実行する NVMe 構成では、ボリューム移動はサポートされません。



上記の想定条件に該当しない場合は、本書の代わりに次のドキュメントを参照してください。

* https://docs.netapp.com/us-en/ontap/volumes/index.html["論理ストレージ管理"^]
+
CLI を使用してボリュームを移動する方法について説明します。





== ボリューム移動の代替手段

ボリュームを移動する前に、次の方法の方が適しているかどうかを確認してください。

* コントローラを無停止でインプレースアップグレードする場合は、アグリゲートの再配置（ ARL ）を使用できないかどうかを検討してください。 ARL は物理的なデータ移動を必要としません。
+
https://docs.netapp.com/us-en/ontap/high-availability/index.html["高可用性"^]

* 移動するのが LUN のみで、ボリュームは移動しない場合は、 LUN の移動メカニズムを使用できます。
+
https://docs.netapp.com/us-en/ontap/san-admin/index.html["SAN 管理"^]


