---
permalink: peering/index.html 
sidebar: sidebar 
keywords: cluster, administrator, create, authenticated, peer, relationship, svm, enable, communicate, replicate, data 
summary: このコンテンツでは、クラスタ管理者が、異なるクラスタのボリューム間でデータをレプリケートできるように、クラスタ間および SVM 間に認証されたピア関係を作成してクラスタ間の相互通信を可能にする方法について説明します。 
---
= クラスタと SVM のピアリングの概要
:icons: font
:imagesdir: ../media/


[role="lead"]
このコンテンツでは、クラスタ管理者が、異なるクラスタのボリューム間でデータをレプリケートできるように、クラスタ間および SVM 間に認証されたピア関係を作成してクラスタ間の相互通信を可能にする方法について説明します。

ONTAP 9.3 の ONTAP System Manager では、クラスタ間および SVM 間のピア関係をより簡単に設定できるようになりました。このコンテンツでは、 ONTAP 9 のすべてのバージョンのクラスタピアリング手順と SVM ピアリング手順について説明します。使用している ONTAP のバージョンに適した手順を使用してください。

このコンテンツは、クラスタピア関係と SVM ピア関係を作成する場合にご利用ください。想定している状況は次のとおりです。

* クラスタで ONTAP 9 を実行している。
* 認証されたクラスタピア関係を必要としている。
* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
* 背景にある概念について詳しく確認する必要はありません。
* ONTAP のコマンドラインインターフェイスや自動スクリプトツールではなく、 System Manager を使用する。
* ONTAP 9.7 以降では、 ONTAP システムマネージャ UI ではなく、 ONTAP 9.7 以前のリリースで _Classic_System Manager UI を使用する場合。
+
https://docs.netapp.com/us-en/ontap/["ONTAP System Manager のドキュメント"^]



上記の想定条件に該当しない場合は、次の資料を参照してください。

* https://docs.netapp.com/us-en/ontap/peering/index.html["クラスタと SVM のピアリング"^]
+
クラスタピア関係と SVM ピア関係をコマンドラインインターフェイスを使用して設定する方法について説明しています。

* https://docs.netapp.com/us-en/ontap/networking/index.html["Network Management の略"^]
+
サブネット、クラスタ間 LIF 、ルート、ファイアウォールポリシーなど、さまざまなネットワークコンポーネントをコマンドラインインターフェイスを使用して設定する方法について説明しています。


