---
permalink: smb-config/index.html 
sidebar: sidebar 
keywords: content, describe, smb, cifs, access, volume, exist, storage, virtual, machine, svm 
summary: このコンテンツでは、新規または既存の Storage Virtual Machine （ SVM ）の新しいボリュームに対する SMB / CIFS アクセスを設定する簡単な方法について説明しています。 
---
= SMB / CIFS の設定の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
このコンテンツでは、新規または既存の Storage Virtual Machine （ SVM ）の新しいボリュームに対する SMB / CIFS アクセスを設定する簡単な方法について説明しています。

このコンテンツは、ボリュームへのアクセスを設定する場合に使用します。想定している状況は次のとおりです。

* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
* 背景にある概念について詳しく確認する必要はありません。
* ONTAP 9.7 以降では、 ONTAP システムマネージャ UI ではなく、 ONTAP 9.7 以前のリリースで _Classic_System Manager UI を使用する場合。
* データネットワークでデフォルトの IPspace 、デフォルトのブロードキャストドメイン、およびデフォルトのフェイルオーバーグループを使用する。
+
データネットワークがフラット構成であれば、これらのデフォルトのオブジェクトを使用することで、リンク障害の発生時に LIF が確実に正しくフェイルオーバーされます。デフォルトのオブジェクトを使用しない場合は、を参照してください https://docs.netapp.com/us-en/ontap/networking/index.html["ネットワーク管理マニュアル"^] LIF パスのフェイルオーバーを設定する方法については、を参照してください。

* 新しいボリュームを NTFS ファイル権限を使用して保護する。




== ONTAP でこれを行うその他の方法

ここでは、 System Manager Classic （ ONTAP 9.7 以前）を使用した SMB / CIFS ストレージのプロビジョニングについて説明します。

[cols="2"]
|===
| 実行するタスク | 参照するコンテンツ 


| System Manager 次世代型（ ONTAP 9.7 以降） | link:https://docs.netapp.com/us-en/ontap/task_nas_provision_windows_smb.html["SMB を使用して Windows サーバ用の NAS ストレージをプロビジョニングする"^] 


| コマンドラインインターフェイス | link:https://docs.netapp.com/us-en/ontap/smb-config/index.html["CLI を使用した SMB の設定の概要"^] 
|===