---
permalink: smb-config/index.html 
sidebar: sidebar 
keywords: content, describe, smb, cifs, access, volume, exist, storage, virtual, machine, svm, system manager classic 
summary: ONTAP System Manager の従来のインターフェイス（ ONTAP 9.7 以前）を使用して、新規または既存の Storage Virtual Machine （ SVM ）の新しいボリュームに対する SMB / CIFS アクセスを簡単に設定できます。 
---
= SMB / CIFS の設定の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager の従来のインターフェイス（ ONTAP 9.7 以前）を使用して、新規または既存の Storage Virtual Machine （ SVM ）の新しいボリュームに対する SMB / CIFS アクセスを簡単に設定できます。

この手順は、ボリュームへのアクセスを設定する場合に使用します。

* すべての利用可能なオプション（ ONTAP 9.7 以前）について検討するのではなく、ベストプラクティスを使用することを推奨します。
* データネットワークでデフォルトの IPspace 、デフォルトのブロードキャストドメイン、およびデフォルトのフェイルオーバーグループを使用する。
+
データネットワークがフラット構成であれば、これらのデフォルトのオブジェクトを使用することで、リンク障害の発生時に LIF が確実に正しくフェイルオーバーされます。デフォルトのオブジェクトを使用しない場合は、を参照してください https://docs.netapp.com/us-en/ontap/networking/index.html["ネットワーク管理マニュアル"^] LIF パスのフェイルオーバーを設定する方法については、を参照してください。

* 新しいボリュームを NTFS ファイル権限を使用して保護する。


ONTAP の SMB プロトコル機能の範囲の詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap/smb-admin/index.html["SMB リファレンスの概要"^]。



== ONTAP でこれを行うその他の方法

[cols="2"]
|===
| 実行するタスク | 参照するコンテンツ 


| 再設計された System Manager （ ONTAP 9.7 以降で使用可能） | link:https://docs.netapp.com/us-en/ontap/task_nas_provision_windows_smb.html["SMB を使用して Windows サーバ用の NAS ストレージをプロビジョニングする"^] 


| ONTAP のコマンドラインインターフェイス | link:https://docs.netapp.com/us-en/ontap/smb-config/index.html["CLI を使用した SMB の設定の概要"^] 
|===