---
permalink: smb-config/reference_where_to_find_additional_information.html 
sidebar: sidebar 
keywords: successful, test, cifs, client, access, advance, configuration, san, access, protocol, complete, root, volume, svm, comprehensive, technical, report, achieve, goal, where to find additional information 
summary: CIFS クライアントアクセスをテストしたあと、 CIFS の高度な設定を行ったり、 SAN アクセスを追加したりできます。プロトコルアクセスが完了したら、 SVM のルートボリュームを保護する必要があります。これらの目標の達成に役立つ包括的なコンテンツとテクニカルレポートをご用意しています。 
---
= 追加情報の参照先
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS クライアントアクセスをテストしたあと、 CIFS の高度な設定を行ったり、 SAN アクセスを追加したりできます。プロトコルアクセスが完了したら、 SVM のルートボリュームを保護する必要があります。これらの目標の達成に役立つ包括的なコンテンツとテクニカルレポートをご用意しています。



== CIFS / SMB の設定

CIFS アクセスについてさらに詳しく設定するには、次のコンテンツおよびテクニカルレポートを参照してください。

* https://docs.netapp.com/us-en/ontap/smb-admin/index.html["CIFS の管理"^]
+
CIFS / SMB プロトコルを使用したファイルアクセスを設定および管理する方法について説明しています。

* http://www.netapp.com/us/media/tr-4191.pdf["ネットアップテクニカルレポート 4191 ：『 Best Practices for Clustered Data ONTAP 8.2 Windows File Services 』"^]
+
SMB の導入やその他の Windows ファイルサービスの機能の概要に加え、 ONTAP に関する推奨事項や基本的なトラブルシューティング情報を紹介しています。

* http://www.netapp.com/us/media/tr-3740.pdf["ネットアップテクニカルレポート 3740 ：『 SMB 2 Next-Generation CIFS Protocol in Data ONTAP 』"^]
+
SMB 2 の機能について、設定に関する詳細や ONTAP での実装に関する情報を紹介しています。





== ルートボリュームの保護

SVM でプロトコルを設定したら、ルートボリュームを保護してください。

* https://docs.netapp.com/us-en/ontap/data-protection/index.html["データ保護"^]
+
負荷共有ミラーを作成して SVM ルートボリュームを保護する方法について説明しています。これは、 NAS 対応の SVM に対するネットアップのベストプラクティスです。また、 SVM ルートボリュームを負荷共有ミラーから昇格させてボリュームの障害や消失からリカバリする簡単な方法についても説明しています


