---
permalink: smb-config/task_deciding_where_to_provision_new_volume.html 
sidebar: sidebar 
keywords: create, cifs, volume, place, exist, storage, virtual, machine, svm, configuration, require, decision, workflow, decide where to provision the new volume 
summary: 新しい CIFS ボリュームを作成する前に、そのボリュームを既存の Storage Virtual Machine （ SVM ）に配置するかどうかを決め、既存の SVM に配置する場合はどのような設定が必要になるかについても確認しておく必要があります。これにより、ワークフローが決まります。 
---
= 新しいボリュームをプロビジョニングする場所を決定します
:icons: font
:imagesdir: ../media/


[role="lead"]
新しい CIFS ボリュームを作成する前に、そのボリュームを既存の Storage Virtual Machine （ SVM ）に配置するかどうかを決め、既存の SVM に配置する場合はどのような設定が必要になるかについても確認しておく必要があります。これにより、ワークフローが決まります。



== 手順

* 新しい SVM にボリュームをプロビジョニングする場合は、 CIFS 対応 SVM を新規に作成します。
+
xref:task_creating_protocol_enabled_svm.adoc[CIFS 対応 SVM の新規作成]

+
既存の SVM で CIFS を有効にしていない場合は、この手順に従ってください。

* CIFS が有効になっているが設定はまだ完了していない既存の SVM にボリュームをプロビジョニングする場合は、既存の SVM に対する CIFS / SMB アクセスを設定します。
+
xref:task_configuring_access_to_existing_svm.adoc[既存の SVM で CIFS / SMB アクセスを設定]

+
このコンテンツで手順を使用して SAN アクセス用の SVM を作成している場合は、この手順に従ってください。

* CIFS アクセスの設定が完了している既存の SVM にボリュームをプロビジョニングする場合は、 CIFS 対応 SVM に CIFS ボリュームを追加します。
+
xref:concept_adding_protocol_volume_to_protocol_enabled_svm.adoc[CIFS 対応 SVM への CIFS ボリュームの追加]


