---
permalink: nas-multiprotocol-config/reference_where_to_find_additional_information.html 
sidebar: sidebar 
keywords: test, cifs, nfs, client, access, perform, advanced, configuration, san, access, procotol, root, volume, svm, comprehensive, report, achieve, goal, where to find additional information 
summary: CIFS および NFS のクライアントアクセスをテストしたあと、 CIFS と NFS の高度な設定を行ったり、 SAN アクセスを追加したりできます。プロトコルアクセスが完了したら、 SVM のルートボリュームを保護する必要があります。このような目標の達成に役立つ包括的なコンテンツやテクニカルレポートをご用意しています。 
---
= 追加情報の参照先
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS および NFS のクライアントアクセスをテストしたあと、 CIFS と NFS の高度な設定を行ったり、 SAN アクセスを追加したりできます。プロトコルアクセスが完了したら、 SVM のルートボリュームを保護する必要があります。これらの目標の達成に役立つ包括的なコンテンツとテクニカルレポートをご用意しています。



== CIFS / SMB の設定

CIFS アクセスについてさらに詳しく設定するには、次の情報とテクニカルレポートを参照してください。

* https://docs.netapp.com/us-en/ontap/smb-admin/index.html["CIFS の管理"^]
+
CIFS / SMB プロトコルを使用したファイルアクセスを設定および管理する方法について説明しています。

* http://www.netapp.com/us/media/tr-4191.pdf["ネットアップテクニカルレポート 4191 ：『 Best Practices Guide for clustered Data ONTAP 8.2 Windows File Services 』"^]
+
SMB の導入やその他の Windows ファイルサービスの機能の概要に加え、 ONTAP に関する推奨事項や基本的なトラブルシューティング情報を紹介しています。

* http://www.netapp.com/us/media/tr-3740.pdf["ネットアップテクニカルレポート 3740 ：『 SMB 2 Next-Generation CIFS Protocol in Data ONTAP 』"^]
+
SMB 2 の機能について、設定に関する詳細や ONTAP での実装に関する情報を紹介しています。





== NFS の設定

NFS アクセスについてさらに詳しく設定するには、以下の情報とテクニカルレポートを参照してください。

* https://docs.netapp.com/us-en/ontap/nfs-admin/index.html["NFS の管理"^]
+
NFS プロトコルを使用したファイルアクセスを設定および管理する方法について説明しています。

* http://www.netapp.com/us/media/tr-4067.pdf["ネットアップテクニカルレポート 4067 ：『 NFS Best Practice and Implementation 』"^]
+
NFSv3 および NFSv4 の運用ガイドであり、 NFSv4 を中心に ONTAP オペレーティングシステムの概要を説明しています。

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["ネットアップテクニカルレポート 4668 ：『 Name Services Best Practices 』"^]
+
LDAP 、 NIS 、 DNS 、およびローカルユーザ / グループファイルを認証用に設定する際の、ベストプラクティス、制限、推奨事項、および考慮事項をまとめています。

* https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf["ネットアップテクニカルレポート 4616 ：『 NFS Kerberos in ONTAP with Microsoft Active Directory 』"^]
* https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf["ネットアップテクニカルレポート 4835 ：『 How to Configure LDAP in ONTAP 』"^]
* http://www.netapp.com/us/media/tr-3580.pdf["ネットアップテクニカルレポート 3580 ：『 NFSv4 の拡張内容とベスト・プラクティス・ガイド - Data ONTAP での実装』"^]
+
ONTAP を実行するシステムに接続された AIX 、 Linux 、または Solaris クライアントに NFSv4 のコンポーネントを実装する際のベストプラクティスを紹介しています。





== ルートボリュームの保護

SVM でプロトコルを設定したら、ルートボリュームを保護してください。

* https://docs.netapp.com/us-en/ontap/data-protection/index.html["データ保護"^]
+
負荷共有ミラーを作成して SVM ルートボリュームを保護する方法について説明しています。これは、 NAS 対応の SVM に対するネットアップのベストプラクティスです。また、 SVM ルートボリュームを負荷共有ミラーから昇格させてボリュームの障害や消失からリカバリする簡単な方法についても説明しています


