---
permalink: expansion/task_ensuring_hardware_level_ha_is_enabled.html 
sidebar: sidebar 
keywords: install, controller, module, reuse, maintenance, mode, ha, state, hardware-level, enable, ensure hardware-level ha is enabled 
summary: 新しく取り付けたコントローラモジュールが、新しいものではなく再利用されたものである場合は、メンテナンスモードに切り替えて、モジュールの HA の状態が HA に設定されていることを確認する必要があります。 
---
= ハードウェアレベルの HA が有効になっていることを確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
新しく設置したコントローラモジュールが、新しくではなく再利用された場合 - メンテナンスモードに切り替えて、モジュールの HA の状態が HA に設定されていることを確認する必要があります。

新しいコントローラモジュールを使用する場合は、 HA がデフォルトで有効になるため、この手順はスキップできます。それ以外の場合は、両方のノードでこの手順を実行する必要があります。

.手順
. 最初のノードでメンテナンスモードに切り替えます。
+
.. halt と入力してノードシェルを終了します。
+
LOADER プロンプトが表示されます。

.. 「 boot_ontap maint 」と入力して保守モードに切り替えます。
+
情報が表示されると、メンテナンスモードのプロンプトが表示されます。



. メンテナンスモードで、コントローラモジュールとシャーシが HA 状態であることを確認します。
+
.. 「 ha-config show 」と入力して、コントローラモジュールとシャーシの HA 状態を表示します。
.. 表示されたコントローラの状態が「 ha 」でない場合は、「 ha-config modify controller ha 」と入力します。
.. 表示されたシャーシの状態が「 ha 」でない場合は、「 ha-config modify chassis ha 」と入力します。
.. 「 ha-config show 」と入力して、コントローラモジュールとシャーシの両方で HA が有効になっていることを確認します。


. ONTAP に戻る：
+
.. 保守モードを終了するには 'halt と入力します
.. 「 boot_ontap 」と入力して ONTAP をブートします
.. ノードがブートし、クラスタセットアップウィザードがコンソール上で自動的に起動するまで待ちます。
.. Enter キーを 4 回押して、ノード管理 LIF の既存の設定をそのまま使用します。
.. ノードに admin ユーザとしてログインしますパスワードは必要ありません


. クラスタに追加するもう一方のノードで、この手順を繰り返します。

