---
permalink: nfs-config/index.html 
sidebar: sidebar 
keywords: nfs, access, volume, exist, storage, virtual, machine, svm, decide 
summary: このコンテンツでは、新規または既存の Storage Virtual Machine （ SVM ）の新しいボリュームに対する NFS アクセスを設定する簡単な方法について説明しています。 
---
= NFS 構成の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
このコンテンツでは、新規または既存の Storage Virtual Machine （ SVM ）の新しいボリュームに対する NFS アクセスを設定する簡単な方法について説明しています。

このコンテンツは、ボリュームへのアクセスを設定する場合に使用します。想定している状況は次のとおりです。

* NFSv4 または NFSv4.1 ではなく、 NFSv3 を使用して NFS アクセスを行う。
* すべての選択肢について検討するのではなく、ベストプラクティスに従う。
* 背景にある概念について詳しく確認する必要はありません。
* ONTAP 9.7 以降では、 ONTAP システムマネージャ UI ではなく、 ONTAP 9.7 以前のリリースで _Classic_System Manager UI を使用する場合。
* データネットワークでデフォルトの IPspace 、デフォルトのブロードキャストドメイン、およびデフォルトのフェイルオーバーグループを使用する。
+
データネットワークがフラット構成であれば、これらのデフォルトのオブジェクトを使用することで、リンク障害の発生時に LIF が確実に正しくフェイルオーバーされます。デフォルトのオブジェクトを使用しない場合は、を参照してください https://docs.netapp.com/us-en/ontap/networking/index.html["ネットワーク管理マニュアル"^] LIF パスのフェイルオーバーを設定する方法については、を参照してください。

* 新しいボリュームを UNIX ファイル権限を使用して保護する。
* LDAP を使用する場合は、 Active Directory から提供されます。




== ONTAP でこれを行うその他の方法

ここでは、 System Manager Classic （ ONTAP 9.7 以前）を使用した NFS ストレージのプロビジョニングについて説明します。

[cols="2"]
|===
| 実行するタスク | 参照するコンテンツ 


| System Manager 次世代型（ ONTAP 9.7 以降） | link:https://docs.netapp.com/us-en/ontap/task_nas_provision_linux_nfs.html["NFS を使用して Linux サーバ用の NAS ストレージをプロビジョニング"^] 


| コマンドラインインターフェイス | link:https://docs.netapp.com/us-en/ontap/nfs-config/index.html["CLI を使用した NFS の設定の概要"^] 
|===